[SofaBaseTopology] Fix Crash when loading a vtk file generated by Gmsh using TetrahedronSetTopologyContainer as container
sofa-framework/sofa pull request #1008
Opened 2019-04-26 14:26 UTC by olivier-goury

Good afternoon!
This PR proposes a fix for a crash when loading a vtk file that was generated by Gmsh.
--------------
 myNode.createObject('MeshVTKLoader', name='loader', filename='gmshMesh.vtk')
 myNode.createObject('TetrahedronSetTopologyContainer', src="@loader")
--------------
The mesh generated by default with Gmsh gives a list of edges and triangles that is incomplete and contains only edges and triangles on the boundary of the mesh. However the list of Tetrahedra is complete. This leads to a crash when using a TetrahedronSetTopologyContainer.
This PR tries to address this problem.

Cheers!
Olivier

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2019-04-26 15:12 UTC, epernod commented
Hi,
not sure to understand, are the edges in the VTK correct regarding the tetra? Or do they correspond to the border?

2019-04-26 15:20 UTC, olivier-goury commented
> Hi,
> not sure to understand, are the edges in the VTK correct regarding the tetra? Or do they correspond to the border?

There are not consistent with the tetra. Basically, the tetra information contains all the tetras as you would expect, but the edges and triangles correspond only to the boundary of the mesh.

2019-04-26 15:42 UTC, epernod commented
Ok and you want to keep them or you want to recompute them? 
It is not easy to read the fixin the PR.

I made some change recently in the container to be sure that all info edges/triangles and tetrahedra are coherent.
If you want to create the border topology you should use TopologicalMapping. Or link data by data to different containers and not using src.

Otherwise to recompute the sub element, you should use a "hidden" option in the VTKLoader: See what has been done for Gmsh in PR #986

2019-04-26 16:06 UTC, olivier-goury commented
Hi,
I don't actually want to use them, it's just that it was crashing! I created the mesh in Gmsh but exported it in vtk. Exporting it in the msh format does not lead to a crash indeed.
I can understand that my fix is not super clear!  
Essentially, in the code when it starts using the edges and something goes wrong, I move on to the option like if no edges had been given (For example in the function createEdgesInTetrahedronArray() with the if (hasEdges) ). I hope it clarifies a little bit.

2019-04-30 13:22 UTC, epernod commented on SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
> +                if (foundEdge == false)  // The edges and triangles in this mesh are only on the border: this mesh was probably created using Gmsh
and what happen if it enter this case? 
The container will stay without edges?

2019-05-07 09:18 UTC, guparan requested changes

2019-05-07 09:18 UTC, guparan commented on SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
> +    }}
This block still needs some indentation

2019-05-07 09:18 UTC, guparan commented on SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyContainer.cpp
> +        while(i<numTriangles && foundEdge==true)
`for ( size_t i = 0 ; (i < numTriangles) &&  (foundEdge == true) ; ++i )` ?

2019-05-07 09:18 UTC, guparan commented on SofaKernel/modules/SofaBaseTopology/TriangleSetTopologyContainer.cpp
> +            while(j<3 && foundEdge==true)
`for ( unsigned int j = 0 ; (j < 3) && (foundEdge == true) ; ++j )` ?

2019-05-07 09:18 UTC, guparan commented on SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
> +        while(i<numTetra && foundEdge == true)
`for ( size_t i = 0 ; (i < numTetra) && (foundEdge == true) ; ++i )` ?

2019-05-07 09:18 UTC, guparan commented on SofaKernel/modules/SofaBaseTopology/TetrahedronSetTopologyContainer.cpp
> +            while(j<6 && foundEdge == true)
`for ( EdgeID j = 0 ; (j < 6) && (foundEdge == true) ; ++j )` ?

2019-05-07 09:53 UTC, olivier-goury commented
Thanks for your comments Guillaume, I agree with your changes!

2019-05-07 11:04 UTC, guparan approved these changes

2019-05-08 10:27 UTC, epernod approved these changes

2019-05-08 10:38 UTC, epernod commented
I'm ok with the change regarding the edges. I can't see some border effect right now... and as all the non regression tests are green I'm 99% confident!
I just added some additional warning and tests inside the tetrahedron methods you fixed to match what has been done inside the TriangleSetTopologyContainer. You could double check if needed.
Thanks, I missed those one.
:+1:

2019-05-09 08:52 UTC, merged