Containers
sofa-framework/sofa pull request #113
Opened 2017-01-03 14:52 UTC by matthieu-nesme

solving #107 

Adding move constructor and move assignment operator to helper containers.

2017-01-03 14:59 UTC, guparan commented on SofaKernel/framework/sofa/helper/set.h
> +* _set library is free software; you can redistribute it and/or modify it     *
I guess some "find+replace" went wrong here.

2017-01-03 15:38 UTC, matthieu-nesme commented
:D corrected

2017-01-03 15:50 UTC, guparan requested changes
Thanks for your fix but you forgot two "_set" typos :(

2017-01-03 15:50 UTC, guparan commented on SofaKernel/framework/sofa/helper/set.h
> +* _set library is free software; you can redistribute it and/or modify it     *
You forgot this one ;)

2017-01-03 15:50 UTC, guparan commented on SofaKernel/framework/sofa/helper/set.h
> +* along with _set library; if not, write to the Free Software Foundation,     *
And this one ;)

2017-01-04 08:31 UTC, matthieu-nesme commented
Corrected again...
This code is pure c++, no need for special assignees.
I let you update your changelog if you want to incorporate this PR.

2017-01-06 14:09 UTC, damienmarchal commented
@guparan  Is there is still something to change ?

2017-01-10 16:25 UTC, JeremieA commented
Hello,

The issue I have with this approach is that this make it very invasive, as Sofa is adding operators in std namespace for all types, even not its own. So within an application that could also does the same, we would get conflicts / redefinition / ambiguity compiler errors, or worse silently override the application's own operators that could have relied on a different string syntax.

I agree that the approach of subclassing the standard containers just to be able to package them within a Data is wrong. In our current branch we are refactoring the approach, relying more on `DataTypeInfo` to generically access features like string parsing, without having to put them in the type itself. But this is work in progress so it is not ready to be pushed yet. So in the meantime this change could be pushed, but with the understanding that it may be a temporary solution only.

Jeremie.

2017-01-11 09:17 UTC, matthieu-nesme commented
@JeremieA I was waiting for this remark :) I totally agree. My point was to wait for an eventual (quite improbable) conflict. But if you think the conflict could be silent, indeed it's a problem.

2017-01-19 09:10 UTC, damienmarchal commented
[ci-build]

2017-01-19 09:42 UTC, damienmarchal commented
This PR: 
  - [ ] does not breaks compilation on the CI.
  - [x] does not generates new warnings or test failure. 
  - [x] does not break existing scenes.
  - [x] does not break API compatibility.  
  - [x] is now 1 week old.

2017-01-19 09:42 UTC, damienmarchal commented
[ci-build]

2017-01-19 11:10 UTC, damienmarchal commented
[ci-build]

2017-01-20 11:41 UTC, damienmarchal commented
[ci-build]

2017-01-20 13:40 UTC, damienmarchal commented
[ci-build]
Tada !!

2017-01-20 13:48 UTC, guparan commented
[ci-build]

2017-01-20 14:03 UTC, damienmarchal commented
[ci-build]
Tudu !

2017-01-20 14:24 UTC, guparan commented
[ci-build]

2017-01-20 14:29 UTC, guparan commented
[ci-build]

2017-01-20 16:18 UTC, damienmarchal commented
[ci-build]

2017-01-20 16:26 UTC, damienmarchal commented
[ci-build]

2017-01-23 09:52 UTC, damienmarchal commented
[ci-build]

2017-01-23 10:44 UTC, damienmarchal commented
[ci-build]

2017-01-23 13:43 UTC, damienmarchal commented
[ci-build]

2017-01-23 13:46 UTC, damienmarchal commented
[ci-build]

2017-01-23 14:00 UTC, damienmarchal commented
[ci-build]

2017-01-23 14:01 UTC, damienmarchal commented
[ci-build]

2017-01-26 08:22 UTC, merged

2017-05-22 22:05 UTC, damienmarchal commented
Hi all,

I have opened a new PR in WIP to handle the cleaning of set & vector.

It currently contains an attempt to remove the std namespace "pollution" in commit https://github.com/sofa-framework/sofa/pull/278/commits/d3ecab1eaa7f2f29242aacf646910b2eb3ab47dd

Feedback & contribution in #278