[SphFluid plugin] Reorder plugin code and scenes files
sofa-framework/sofa pull request #1165
Opened 2019-10-02 00:42 UTC by epernod

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2019-10-02 09:54 UTC, guparan requested changes

2019-10-02 09:54 UTC, guparan commented on applications/plugins/SofaSphFluid/src/SofaSphFluid/config.h.in
> -#  define SOFA_TARGET SofaSphFluid
This should be kept :)

2019-10-02 12:19 UTC, damienmarchal commented
Hello @epernod,

For the future: 
Shouldn't we move the SpatialGridContainer into SofaVolumetricData ? In addition there is in SofaEulerianFluid some dedicated data structure for storing the quantities. 
Merging al that could be intereting. 

Shouldn't we merge everything into a single SofaFluids plugins ?

2019-10-02 12:53 UTC, epernod commented
@damienmarchal yes totally agree on the different points. But as you say: "for the future".
I will move one step at a time, by making this plugin works again first.

But indeed it is a topic I wanted to speak about but the meeting was already too long.
It would be good to either merge some plugins or have some high level option in the cmake of sofa, for example, SOFA_HAVE_FLUID which will add, Sph, Eulerian, Volumetric rendering plugins etc...

2019-10-02 13:00 UTC, epernod commented
@damienmarchal it could be useful (for me at least) to open issue(s) to where there is duplicated code or same algo needed.

2019-10-05 21:02 UTC, fredroy commented
[ci-build][with-regression-tests][with-scene-tests]

2019-10-09 08:47 UTC, guparan approved these changes

2019-10-10 07:45 UTC, merged