[QtGui] Add option in gui to display Data Graph
sofa-framework/sofa pull request #1187
Opened 2019-10-14 14:01 UTC by epernod

WIP project: Add window to display Data graph using NodeEditor library.

To use it, install NodeEditor.
check option in CMake: SOFA_BUILD_NODEGRAPH
and until better setup, manually set: 
- NODEEDITOR_INCLUDE_PATH to NodeEditor-install/include
- NODEEDITOR_LIBRARY_RELEASE  to  NodeEditor-install/lib/nodes.lib

DataGraph can be displayed in top menu: Edit->Data Graph...

![graphData_01](https://user-images.githubusercontent.com/21199245/66757185-e1f85280-ee9b-11e9-87ff-3a828322598b.jpg)
![graphData_03](https://user-images.githubusercontent.com/21199245/66757188-e45aac80-ee9b-11e9-8065-6f379be060b4.jpg)

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2019-10-14 14:05 UTC, epernod commented
my bad, changes from PR #1181 are included here....

2019-10-16 15:05 UTC, epernod commented
@damienmarchal for you, the last changes allow to retrieve pointer to BaseData (child and parent) which have been manually connected in the graph.
Ya plus qu'a dans runSofa2... comme on dit!

![graphData_05](https://user-images.githubusercontent.com/21199245/66931733-d2614100-f036-11e9-83c3-f1ce11c1fe77.jpg)
![graphData_06](https://user-images.githubusercontent.com/21199245/66931740-d3926e00-f036-11e9-93d5-51920e3736f2.jpg)

2019-10-23 14:09 UTC, guparan requested changes

2019-10-23 14:09 UTC, guparan commented on applications/sofa/gui/qt/CMakeLists.txt
> +
Find dependency packages before source files (l.65)
```cmake
# NodeEditor
option(SOFAGUIQT_ENABLE_NODEGRAPH "Build the Node graph representation. NodeEditor library is needed." OFF)
if(SOFAGUIQT_ENABLE_NODEGRAPH)
    find_package(NodeEditor REQUIRED)
endif()
sofa_set_01(SOFAGUIQT_HAVE_NODEEDITOR VALUE ${SOFAGUIQT_ENABLE_NODEGRAPH} BOTH_SCOPES)
```

Then add a if block in source files (here)
```cmake
# NodeEditor
if(SOFAGUIQT_ENABLE_NODEGRAPH)
    list(APPEND MOC_HEADER_FILES 
        SofaWindowDataGraph.h
        dataGraph/SofaComponentNodeModel.h
        )
    list(APPEND SOURCE_FILES 
        SofaWindowDataGraph.cpp
        dataGraph/SofaComponentNodeModel.cpp
        )
endif()
```

2019-10-23 14:09 UTC, guparan commented on applications/sofa/gui/qt/CMakeLists.txt
> +
```cmake
if(SOFAGUIQT_ENABLE_NODEGRAPH)
    target_link_libraries(${PROJECT_NAME} PUBLIC ${NODEEDITOR_LIBRARY})
    sofa_install_libraries(LIBRARIES ${NODEEDITOR_LIBRARY})
    target_include_directories(${PROJECT_NAME} PUBLIC "$<BUILD_INTERFACE:${NODEEDITOR_INCLUDES}>")
endif()
```

2019-10-23 14:09 UTC, guparan commented on applications/sofa/gui/qt/RealGUI.cpp
> +      #endif
No indentation for preprocessor directives :-)

2019-10-23 14:09 UTC, guparan commented on applications/sofa/gui/qt/CMakeLists.txt
> +
What is tricky with `*_HAVE_*` variables is to keep them up-to-date when the option is disabled.
That is why `sofa_set_01` must stay out of the `if(SOFAGUIQT_ENABLE_NODEGRAPH)` block.

2019-10-24 09:41 UTC, guparan requested changes

2019-10-24 09:41 UTC, guparan commented on applications/sofa/gui/qt/CMakeLists.txt
> +    include_directories(${NODEEDITOR_INCLUDE_PATH})
This is redundant with the `target_include_directories` below (the latter is better).

2019-10-24 09:41 UTC, guparan commented on applications/sofa/gui/qt/CMakeLists.txt
> +    target_include_directories(${PROJECT_NAME} PUBLIC "$<BUILD_INTERFACE:${NODEEDITOR_INCLUDES}>")
So this should use NODEEDITOR_INCLUDE_PATH

2019-10-28 09:06 UTC, guparan requested changes
Sorry @epernod but I didn't see that one last thing is missing: the *Config.cmake.in part of [my small tutorial](https://gist.github.com/guparan/0b0ed00ad60b740f85b794cdff255229).
With your PR, it should be done in SofaGuiConfig.cmake.in :wink:

2019-10-28 10:00 UTC, epernod commented
@guparan here it is... Not 100% sure of what I did.
Is it:
```if(SOFAGUIQT_HAVE_NODEEDITOR)```  or ```if (SOFAGUIQT_ENABLE_NODEGRAPH)``` ?

just another question, in your tuto why is there ZLIB dependency SofaGeneral/SofaGeneralConfig.cmake.in and not in SofaGeneralLoader/SofaGeneralLoaderConfig.cmake.in ?

2019-10-28 11:05 UTC, guparan commented
You should not have created a SofaGuiConfig.cmake.in in `sofa/gui/qt`. This file already exists and is in `<sofa_root>/SofaGui`. See my answer to your 2nd question below.

> @guparan here it is... Not 100% sure of what I did.
> Is it:
> `if(SOFAGUIQT_HAVE_NODEEDITOR)` or `if (SOFAGUIQT_ENABLE_NODEGRAPH)` ?

It's `if(SOFAGUIQT_HAVE_NODEEDITOR)` 

> just another question, in your tuto why is there ZLIB dependency SofaGeneral/SofaGeneralConfig.cmake.in and not in SofaGeneralLoader/SofaGeneralLoaderConfig.cmake.in ?

Because, from CMake point of view, SofaGeneral is a package and SofaGeneralLoader is not (it's only a target). 
A CMake package is something that can be loaded with `find_package` and that defines targets (most of the time: libraries to link with `target_link_libraries`).
The XXXConfig.cmake.in file defines what the XXX package must do when someone calls `find_package(XXX)`. Typically, it will `find_package` the packages needed by it's own targets. Otherwise, at configure step, CMake will see that a target's dependency cannot be found for this package. See #1198 as example.

In SOFA, the packages are: 
  - the 8 main packages: SofaFramework, SofaSimulation, SofaBase, SofaCommon, SofaGeneral, SofaAdvanced, SofaMisc, SofaGui.
  - the plugins
  - the "pluginized" modules (targets that have become packages)

2019-10-28 13:45 UTC, guparan approved these changes

2019-10-28 16:50 UTC, guparan commented
[ci-build][with-all-tests]

2019-10-29 10:38 UTC, epernod commented
-> Ready? 🐱

2019-10-30 16:03 UTC, merged