[Modularization] SofaValidation
sofa-framework/sofa pull request #1302
Opened 2020-03-30 22:44 UTC by fredroy

#1300 

(+Cleaning, +Fix in SofaGuiQt)
Add header config file to runSofa

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2020-03-31 21:10 UTC, fredroy commented
[ci-build][with-all-tests]

2020-04-08 08:33 UTC, damienmarchal commented on applications/projects/runSofa/Main.cpp
> +#ifdef RUNSOFA_ENABLE_VALIDATION
I'm not fan

2020-04-08 08:45 UTC, guparan requested changes

2020-04-08 08:45 UTC, guparan commented on modules/SofaValidation/CMakeLists.txt
> +    INCLUDE_SOURCE_DIR "{SOFAVALIDATION_SRC}"
A `$` is missing here.

2020-04-22 09:58 UTC, guparan requested changes

2020-04-22 09:58 UTC, guparan commented on applications/plugins/Flexible/CMakeLists.txt
> +find_package(SofaValidation REQUIRED)
Add in FlexibleConfig.cmake.in : `find_package(SofaValidation REQUIRED)`

2020-04-22 09:58 UTC, guparan commented on applications/plugins/SofaCUDA/CMakeLists.txt
> +find_package(SofaValidation REQUIRED)
Add in SofaCUDAConfig.cmake.in : `find_package(SofaValidation REQUIRED)`

2020-04-22 09:58 UTC, guparan commented on applications/projects/SofaPhysicsAPI/CMakeLists.txt
> +find_package(SofaValidation REQUIRED)
Add in SofaPhysicsAPIConfig.cmake.in : `find_package(SofaValidation REQUIRED)`

2020-05-11 08:06 UTC, fredroy commented
[ci-build][with-all-tests]

2020-05-11 12:06 UTC, merged