[Sofa] Remove Collections
sofa-framework/sofa pull request #1314
Opened 2020-04-02 22:07 UTC by fredroy

Big Big PR for:
- remove collections (SofaComponent*, except for SofaComponentAll)
- now SofaBase/SofaCommon/SofaGeneral/SofaAdvanced/SofaMisc are packages (find_package SofaBase) and are modules as well (target_link_libraries SofaBase)
- Add a new module in SofaBase, including all essential utilities for scenes (i.e RequiredPlugin, AddRepo, etc)
- Change previous SofaMisc module to SofaMiscExtra (to avoid confusion with the metapackage SofaMisc)

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2020-04-03 07:13 UTC, fredroy commented
[ci-build][with-all-tests]

2020-04-08 09:26 UTC, epernod requested changes

2020-04-08 09:26 UTC, epernod commented on applications/sofa/gui/qt/dataGraph/SofaComponentNodeModel.h
> +class SofaNodeData : public NodeData
Found one error ;)

2020-04-08 09:26 UTC, epernod commented on SofaKernel/modules/SofaCore/src/sofa/core/objectmodel/Base.h
> +    class SOFA_CORE_API SofaInfo : public ComponentInfo
find the another one.

2020-04-08 09:47 UTC, guparan requested changes

2020-04-08 09:47 UTC, guparan commented on applications/collections/SofaComponentAll/initComponentAll.cpp
>  #endif
Should not change.

2020-04-08 10:06 UTC, damienmarchal commented on applications/collections/CMakeLists.txt
> +# sofa_add_collection(SofaComponentBase SofaComponentBase ON)
vire ça

2020-04-16 15:34 UTC, merged