[SofaGui] Pass QDocBrowser as an option
sofa-framework/sofa pull request #1315
Opened 2020-04-02 23:28 UTC by epernod

- QDocBrowser will be build by default if Qt5WebEngine is found.
- Add option in cmake to enable the QDocBrowser (If I did it well) that will set Qt5WebEngine as required to warn user to install it if they want the browser.

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2020-04-03 08:27 UTC, guparan commented
Thanks @epernod but why?
@damienmarchal, your opinion on this?

2020-04-03 09:03 UTC, epernod commented
I did like for QtChart. As it is not a module installed by default in Qt. 
Otherwise be sure to tell user to install that module when installing Qt.

2020-04-03 09:04 UTC, jnbrunet commented
Just my 2 cents, if there is an option to disable it, I'll probably use it even tho I have Qt5WebEngine installed, since I like to keep only the minimum options activated to reduce compilation time.

2020-04-06 19:43 UTC, damienmarchal commented
Hi all, 

Thanks Erik for the PR. 

I'm not opposed to have this kind of option but I think it would be better to have and implementation that is not based on #ifdef (for reason we already discussed a lot).

2020-04-08 10:26 UTC, guparan requested changes
- I would rename SOFAGUIQT_ENABLE_DOCBROWSER  into SOFAGUIQT_ENABLE_QDOCBROWSER
- To avoid duplicated variables, use SOFAGUIQT_HAVE_QT5_WEBENGINE in code. 
- In applications/sofa/gui/qt/SofaGuiQt.h.in, you have to add:
  ```cmake
  #cmakedefine01 SOFAGUIQT_HAVE_QT5_WEBENGINE
  ```

2020-04-08 10:26 UTC, guparan commented on applications/sofa/gui/qt/CMakeLists.txt
> +endif()
This should be enough:
```cmake
# QDocBrowser
option(SOFAGUIQT_ENABLE_QDOCBROWSER "Build the QDocBrowser. Qt5WebEngine is needed." OFF)
if (SOFAGUIQT_ENABLE_QDOCBROWSER)
    sofa_find_package(Qt5 COMPONENTS WebEngine WebEngineWidgets REQUIRED BOTH_SCOPES)
    set(QT_TARGETS ${QT_TARGETS} Qt5::WebEngine Qt5::WebEngineWidgets)
endif()
```

2020-05-05 14:04 UTC, guparan commented
I added the missing "enable by default if QDocBrowser is found" part :wink: 
Looks good now!

2020-05-05 14:07 UTC, guparan approved these changes

2020-05-06 14:37 UTC, merged