Inf removeqwt
sofa-framework/sofa pull request #1512
Opened 2020-09-30 15:44 UTC by epernod

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2020-10-01 06:53 UTC, epernod commented
[ci-build][with-all-tests]

2020-10-06 15:15 UTC, guparan requested changes

2020-10-06 15:15 UTC, guparan commented on modules/SofaGuiQt/CMakeLists.txt
> -
Do not forget to also propagate this removal to SofaGuiQtConfig.cmake.in :+1:

2020-10-07 10:00 UTC, guparan requested changes

2020-10-07 10:00 UTC, guparan commented on modules/SofaGuiQt/src/sofa/gui/qt/config.h.in
> +#define SOFAGUI_ENABLE_NATIVE_MENU ${SOFAGUI_USE_NATIVE_MENU}
#cmakedefine01 SOFAGUI_ENABLE_NATIVE_MENU

2020-10-07 10:00 UTC, guparan commented on modules/SofaGuiQt/CMakeLists.txt
> +
Unnecessary

2020-10-08 12:41 UTC, damienmarchal commented
Hi guys... @guparan ask for change...but the PR is flagged as ready.

2020-10-08 12:42 UTC, guparan commented
Changes have been done during the meeting, we're good to go :+1:

2020-10-09 12:15 UTC, merged

2020-10-09 12:15 UTC, damienmarchal commented
Thanks @epernod