Cleanwarning
sofa-framework/sofa pull request #1549
Opened 2020-10-18 09:32 UTC by courtecuisse

This pr clean most of warnings
The code has never been changed in terms of runtime, but sometimes one may thing that warning were here to detect potential error (passthrough in a case for instance).
The main remaining warning is the alreadydefine class but i will do that in a separate pr since I'm scared it changes behavior on other platforms.

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2021-07-19 16:07 UTC, guparan commented
I just updated this PR. To be reviewed again.
@courtecuisse if you are not willing to read/acknowledge the work done by reviewers, then I will take the decisions and potentially (surely?) mess your work.
Cheers :v:

2021-07-19 16:08 UTC, guparan commented
[ci-build][with-all-tests]

2021-07-20 07:45 UTC, fredroy requested changes

2021-07-20 07:45 UTC, fredroy commented on SofaKernel/modules/SofaHelper/src/sofa/helper/visual/Transformation.h
> +    Transformation(const Transformation & r) { this->operator=(r); }
```suggestion
```
There is already a copy constructor (doing the same)

2021-07-20 10:17 UTC, guparan commented on applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaStandardTetrahedralFEMForceField.cu
>      StandardTetrahedralFEMForceFieldCuda_PointsAccumulation_kernel<float><<<grid2, threads>>>(nbPoints, nbMaxTetraPerNode, (const float*) contribTetra, (const int*) neighbourhoodPoints, (float*) f);
Why not `threads2` on line 1274 ?

2021-07-21 08:16 UTC, guparan commented on applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaStandardTetrahedralFEMForceField.cu
>      StandardTetrahedralFEMForceFieldCuda_PointsAccumulation_kernel<float><<<grid2, threads>>>(nbPoints, nbMaxTetraPerNode, (const float*) contribTetra, (const int*) neighbourhoodPoints, (float*) f);
StandardTetrahedralFEMForceFieldCuda3d_addForce uses `thread2` line 1312.
Thus, I will change line 1274 to use `thread2`.

2021-07-21 08:22 UTC, merged