[Sofa] Regroup miniFlowVR-related things
sofa-framework/sofa pull request #1616
Opened 2020-11-20 17:38 UTC by fredroy

miniFlowVR, an extlib of Sofa, is used for 
- managing a file format for DistanceGrid (component of plugin SofaDistanceGrid)
- as a dependency for meshconv, a commandline utility for meshes and used mainly to create the previous file format for DistanceGrid.

So as it seems was related to DistanceGrid:
 - miniFlowVR was moved into SofaDistanceGrid (and thus depolluting the main tree of Sofa with the extlib thing)
 - as a small consequence, move meshconv into SofaDistanceGrid.

It is deemed OK as:
 - it seems not a lof of people uses meshconv as it is (I remember fixing the compilation ages ago and nobody said anything). Moreover, even its CMakefile was quite ill-formed. 
 - meshconv was originally a part of FlowVR itself apparently, so it makes sense to regroup of all of these codes.

Additionnally, SofaDistanceGrid was cleanup (reorganizing files like the template, cleaner CMake etc)

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2020-12-08 10:28 UTC, fredroy commented
[ci-build][with-all-tests]

2021-01-06 09:36 UTC, epernod requested changes

2021-01-06 09:36 UTC, epernod commented on applications/plugins/SofaDistanceGrid/CMakeLists.txt
> +find_package(SofaGeneral REQUIRED) # SofaUserInteraction
This should not be used anymore

2021-01-06 09:36 UTC, epernod commented on applications/plugins/SofaDistanceGrid/SofaDistanceGridConfig.cmake.in
> +find_package(SofaGeneral QUIET REQUIRED)
This should not be used anymore

2021-01-06 09:37 UTC, epernod approved these changes

2021-01-06 10:49 UTC, merged