Beam plastic
sofa-framework/sofa pull request #1618
Opened 2020-11-23 10:42 UTC by Camille-K

Here is a new plugin which implements a beam force field component with plastic behaviour (to model nonlinear and permanent deformation).

The general structure is inspired from the BeamFEMForceField component. At the moment, I kept the new component in a dedicated plugin (BeamPlastic), but I guess it could be moved to where the BeamFEMFF component already is (providing the PR is mergeable).

Two pull-requested files (in applications/plugins/BeamPlastic/quadrature) were implemented by someone else and published under the open source Boost Software License 1.0 (BSL-1.0). I mentioned this in both files headers, but I don't know if the BSL-1.0 is compatible with the SOFA license. If not, these files can be removed and I can re-implement the corresponding methods (for reduced gaussian integration).

The code compiles on my side, and the two provided example files work fine, but there are quiet a few things that could/should be improved (including unit tests). I have already noted some of them, but as this is my first PR I'm not familiar with how or where these should be discussed.
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2020-12-09 09:57 UTC, damienmarchal commented
Hello @Camille-K 

Thanks for the PR:
several comments to be conformant with sofa coding standards:
- use #pragma once everywhere
- use c++11 compact namespaces eg
```cpp
namespace sofa::core::objectmodel {}
```
- about namespace, the current idea in sofa is that each plugin's namespace should have the name of the plugin. 
Eg:
```cpp
namespace sofa::plugin::beamplastic::component 
{
   class BeamPlasticForceField {};
   class StiffnessContainer {};
   class PoissonContainer {};
}
```
- rename basic_example in just example
- there shouldn't have no definition(code) in the .h, only declaration. 
- shouldn't PlasticConstitutiveLaw::getXXXX be pure virtual ?

2020-12-09 09:59 UTC, fredroy commented
- PoissonContainer/StiffnessContainer are already present in SofaSimpleFem
- It should follow guidelines from PluginExample (name, folder, etc)

2021-03-29 12:40 UTC, alxbilger requested changes
Overall, the quality of the code is good. The major concern I have is the huge length of the inl file. I don't mind keeping it like that, but if you can, try to split it into several files.

2021-03-29 12:40 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +    m_edgeHandler = new BeamFFEdgeHandler(this, &m_beamsData);
I reckon it would be best to use a std::unique_ptr instead of a raw pointer. If you do that, you can get rid of the destructor implementation

2021-03-29 12:40 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +    if (constitutiveModel == "RambergOsgood")
Is it planned to add more constitutive models? Currently you only have one and it adds complexity to handle multiple constitutive models but having only one.

2021-03-29 12:40 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +        fem::RambergOsgood<DataTypes> *RambergOsgoodModel = new (fem::RambergOsgood<DataTypes>)(youngModulus, yieldStress);
If you keep handling more than one constitutive models, please use a sd::unique_ptr instead of a raw pointer. I guess you have a memory leak here...

2021-03-29 12:40 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +    if (m_topology==NULL)
Prefer nullptr over NULL (not the only place)

2021-03-29 12:40 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +    size_t n = m_indexedElements->size();
when you have such declarations of variables, make them const

2021-03-29 12:40 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +        phiY = (Real)(12.0*_E*_Iy / (kappaZ*_G*_A*L2));
Why casting to Real, whereas you have declared phiY a double?

2021-03-29 12:40 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +    //serr<<"BeamPlasticFEMForceField<DataTypes>::reset"<<sendl;
Please remove uncessary commented code

2021-03-29 12:40 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +    std::vector<defaulttype::Vector3> centrelinePoints[1];
There is no point to declare an array of one element.

2021-03-29 12:40 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +    double threshold = 1e2; //TO DO: choose adapted threshold
Isn't it a magic number that you need to provide as a Data?

2021-11-19 13:51 UTC, alxbilger requested changes

2021-11-19 13:51 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.h
> +        GaussPoint3() {}
m_mechanicalState must be initialized

2021-11-19 13:51 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.h
> +    BeamPlasticFEMForceField<DataTypes>* ff;
I think it is not used. Please remove it.

2021-11-19 13:51 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.h
> +    BaseMeshTopology* m_topology;
You already have a variable pointing to the topology (l_topology). I recommend to use it, and remove this one. Also, m_topology is not initialized to nullptr

2021-11-19 13:51 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.h
> +    double m_lastUpdatedStep;
This class member is not initialized in any of the constructor

2021-11-19 13:51 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +        for (int i = 1; i < _nbCentrelineSeg; i++)
Declaration of 'i' hides previous local declaration

2021-11-19 13:51 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +        for (int i = 1; i < _nbCentrelineSeg; i++)
Declaration of 'i' hides previous local declaration

2021-11-19 13:51 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +        Mat<3, 1, Real> u = N*disp;
Declaration of 'u' hides previous local declaration

2021-11-19 13:51 UTC, alxbilger commented on applications/plugins/BeamPlastic/constitutiveLaw/PlasticConstitutiveLaw.h
> +    typedef Eigen::Matrix<double, 6, 1> VoigtTensor;
Is Eigen required here?

2021-11-19 13:51 UTC, alxbilger commented on applications/plugins/BeamPlastic/quadrature/quadrature.h
> +/******************************************************************************/
Is the license ok?

2021-11-19 13:51 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +        const double beta = 0.5; // Indicates the proportion of Kinematic vs isotropic hardening. beta=0 <=> kinematic, beta=1 <=> isotropic
Is it supposed to vary?

2021-11-19 13:51 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +BeamPlasticFEMForceField<DataTypes>::BeamPlasticFEMForceField(Real poissonRatio, Real youngModulus, Real yieldStress, Real zSection,
Some parameters are unused

2021-11-19 13:51 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +    const Matrix6x6& C = m_beamsData.getValue()[index]._materialBehaviour;
`C` is not used. You can remove it

2021-11-19 13:51 UTC, alxbilger commented on applications/plugins/BeamPlastic/forceField/BeamPlasticFEMForceField.inl
> +    const Matrix6x6& C = m_beamsData.getValue()[index]._materialBehaviour; //Matrix D in Krabbenhoft's
C is not used. You can remove it

2021-11-19 13:55 UTC, alxbilger commented
@Camille-K there are several places where you declare variables with the same name than another variable already declared before. Please keep names unique

2023-03-08 08:20 UTC, fredroy commented
[ci-build][with-all-tests][force-full-build]

2025-03-10 05:37 UTC, fredroy commented
[ci-build][with-all-tests][force-full-build]

2025-04-02 23:29 UTC, fredroy commented
[ci-build][with-all-tests][force-full-build]

2025-04-09 07:42 UTC, closed without merging