Improve background v20.12
sofa-framework/sofa pull request #1758
Opened 2021-01-29 12:03 UTC by hugtalbot

Changes:
- changes the old fashion SOFA logo in background
- make it repeatable
- change ERROR msg into warning message when SOFA is launched for the first time and some folder are not existing (e.g. screenshots)

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-01-29 12:15 UTC, damienmarchal commented
We want a picture in the PR :)

2021-01-29 12:50 UTC, damienmarchal commented
So you dropped the sober design for this one. 
Mais où va le monde ?

2021-01-29 12:55 UTC, fredroy commented on modules/SofaGuiQt/src/sofa/gui/qt/viewer/GLBackend.cpp
> +    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
really needed ? it is already in the Texture::init() function

2021-01-29 15:04 UTC, guparan commented on modules/SofaGuiCommon/src/sofa/gui/BaseGUI.cpp
> +            msg_warning("BaseGUI") << "Created directory: " << path;
Not needed, already done in v20.12

2021-01-29 16:30 UTC, guparan commented on modules/SofaGuiCommon/src/sofa/gui/BaseGUI.cpp
> +            msg_warning("BaseGUI") << "Created directory: " << path;
v20.12 only (will be in a PR after release is out)

2021-01-29 16:42 UTC, fredroy approved these changes

2021-01-29 16:44 UTC, fredroy commented
I approve the code, not necessarily the design itself 🥸 (but i am ok with it nevertheless)

2021-02-01 08:14 UTC, guparan requested changes
On my Windows: 
```
[ERROR]   [ImageCImg] Caught exception while loading: [instance(0,0,0,0,0000000000000000,non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file 'C:/dev/sofa/fork/src/share/textures/SOFA_logo.bmp'.
[ERROR]   [Texture] invalid texture type.
```

Also, I do not agree with this design. 
It could be nice to have other proposals. I'll do one. :+1:

2021-02-01 10:10 UTC, guparan commented
BMP must be 24bits.
Here is my best proposal:
![SOFA_logo_v4](https://user-images.githubusercontent.com/1651667/106444492-21c2bf00-647e-11eb-9fa4-d8070e7f975d.png)

2021-02-01 10:16 UTC, damienmarchal commented
> BMP must be 24bits.
> Here is my best proposal:
> ![SOFA_logo_v4](https://user-images.githubusercontent.com/1651667/106444492-21c2bf00-647e-11eb-9fa4-d8070e7f975d.png)

best one so-far :)

2021-02-01 10:23 UTC, guparan commented
I also changed the code in GLBackend.cpp to remove the "moving background when resizing" effect.
```cpp
double coordWidth = int(screenWidth / w) + 1;
double coordHeight = int(screenHeight / h) + 1;

glColor3f(1.0f, 1.0f, 1.0f);
glBegin(GL_QUADS);
glTexCoord2d(0.0,            0.0);             glVertex3d( -w*coordWidth, -h*coordHeight, 0.0 );
glTexCoord2d(coordWidth*2.0, 0.0);             glVertex3d(  w*coordWidth, -h*coordHeight, 0.0 );
glTexCoord2d(coordWidth*2.0, coordHeight*2.0); glVertex3d(  w*coordWidth,  h*coordHeight, 0.0 );
glTexCoord2d(0.0,            coordHeight*2.0); glVertex3d( -w*coordWidth,  h*coordHeight, 0.0 );
glEnd();
```
@fredroy could you review this before I push it in the PR please ?

2021-02-02 16:12 UTC, epernod commented
I agree with the gray scale version... even if I know I will always turn to full black background to better see mesh details.

2021-02-02 16:14 UTC, epernod commented
> 
> 
> I also changed the code in GLBackend.cpp to remove the "background is moving when I resize the window" effect.
> 
> ```c++
> double coordWidth = int(screenWidth / w) + 1;
> double coordHeight = int(screenHeight / h) + 1;
> 
> glColor3f(1.0f, 1.0f, 1.0f);
> glBegin(GL_QUADS);
> glTexCoord2d(0.0,            0.0);             glVertex3d( -w*coordWidth, -h*coordHeight, 0.0 );
> glTexCoord2d(coordWidth*2.0, 0.0);             glVertex3d(  w*coordWidth, -h*coordHeight, 0.0 );
> glTexCoord2d(coordWidth*2.0, coordHeight*2.0); glVertex3d(  w*coordWidth,  h*coordHeight, 0.0 );
> glTexCoord2d(0.0,            coordHeight*2.0); glVertex3d( -w*coordWidth,  h*coordHeight, 0.0 );
> glEnd();
> ```
> 
> @fredroy could you review this before I push it in the PR please ?

```double coordWidth = int(screenWidth / w) + 1;```
will give warning conversion and why +1 ?

2021-02-03 09:33 UTC, guparan commented
> 
> 
> > I also changed the code in GLBackend.cpp to remove the "background is moving when I resize the window" effect.
> > ```c++
> > double coordWidth = int(screenWidth / w) + 1;
> > double coordHeight = int(screenHeight / h) + 1;
> > 
> > glColor3f(1.0f, 1.0f, 1.0f);
> > glBegin(GL_QUADS);
> > glTexCoord2d(0.0,            0.0);             glVertex3d( -w*coordWidth, -h*coordHeight, 0.0 );
> > glTexCoord2d(coordWidth*2.0, 0.0);             glVertex3d(  w*coordWidth, -h*coordHeight, 0.0 );
> > glTexCoord2d(coordWidth*2.0, coordHeight*2.0); glVertex3d(  w*coordWidth,  h*coordHeight, 0.0 );
> > glTexCoord2d(0.0,            coordHeight*2.0); glVertex3d( -w*coordWidth,  h*coordHeight, 0.0 );
> > glEnd();
> > ```
> > 
> > 
> > @fredroy could you review this before I push it in the PR please ?
> 
> `double coordWidth = int(screenWidth / w) + 1;`
> will give warning conversion and why +1 ?

+1 because we want to know how many entire texture we have to display to cover **at least** screenWidth and screenHeight. Thus we do an integer division and add 1 to handle all the cases where `screenWidth % w != 0` (almost all the cases)`.
Not sure this was very clear :eyes:

2021-02-10 10:28 UTC, merged