[SofaExporter] Add option for obj export
sofa-framework/sofa pull request #1789
Opened 2021-02-05 15:16 UTC by hugtalbot

Fix #1784

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-02-12 23:19 UTC, epernod requested changes

2021-02-12 23:19 UTC, epernod commented on modules/SofaExporter/src/SofaExporter/MeshExporter.cpp
> +bool MeshExporter::writeMeshObj()
Isn't it a duplication of : sofa-src\modules\SofaExporter\src\SofaExporter\OBJExporter.cpp
which already use  #include <sofa/simulation/ExportOBJVisitor.h>
which call void VisualModelImpl::exportOBJ  on each visulaModel...
.... ok so the answer to my question is not exactly the same... but... what a mess!

2021-02-15 19:19 UTC, epernod commented on modules/SofaExporter/src/SofaExporter/MeshExporter.cpp
> +bool MeshExporter::writeMeshObj()
Good question, I would say use assimp or:

1. Move the code out from VisualModelImpl::exportOBJ which is the most complete inside a class OBJWritter which export the mesh checking which info are available (normals, uv, etc.)
2. Either remove or update ObjExporter (SOFA component) to use ObjWritter internally
3. Do the same for SofaExporter
4. take a coffee
5. Update sofa/simulation/ExportOBJVisitor.h to create a ObjExporter each time a VisualModel is encounter.

2021-02-17 09:44 UTC, damienmarchal commented on modules/SofaExporter/src/SofaExporter/MeshExporter.cpp
> +        for (Size i=0 ; i<m_inputtopology->getNbEdges() ; i++)
sofa::Index vs sofa::Size ?

2021-02-25 22:22 UTC, fredroy commented
Looks fine for me

2021-02-25 22:23 UTC, fredroy approved these changes

2021-02-26 08:43 UTC, merged