[SofaKernel] Port Quat from Defaulttype to Sofa.Type
sofa-framework/sofa pull request #1790
Opened 2021-02-05 17:38 UTC by fredroy

... and DualQuat.

WIP

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-02-07 20:22 UTC, fredroy commented
[ci-build][force-full-build][with-all-tests]

2021-02-17 09:58 UTC, guparan requested changes

2021-02-17 09:58 UTC, guparan commented on SofaKernel/modules/Sofa.Type/src/sofa/type/Quat.h
> +     between the Quatnions' orientations, by "flipping" the source Quatnion if needed (see
Auto-replace issue :eyes:

2021-02-17 09:58 UTC, guparan commented on SofaKernel/modules/Sofa.Type/src/sofa/type/Quat.h
> +    /// Thanks to https://github.com/mrdoob/three.js/blob/dev/src/math/Quatnion.js#L199
Auto-replace issue :eyes:

2021-02-17 09:58 UTC, guparan commented on SofaKernel/modules/Sofa.Type/src/sofa/type/Quat.inl
> + between the Quatnions' orientations, by "flipping" the source Quatnion if needed (see
Auto-replace issue :eyes:

2021-02-17 09:58 UTC, guparan commented on SofaKernel/modules/Sofa.Type/src/sofa/type/Quat.inl
> +    //calculate Quatnion.
Auto-replace issue :eyes:

2021-02-17 09:58 UTC, guparan commented on SofaKernel/modules/Sofa.Type/compat/sofa/defaulttype/MatSym.h
> +// SOFA_DEPRECATED_HEADER(v21.12, "sofa/type/MatSym.h")
Add a quick comment to explain why we keep that.

2021-02-17 09:58 UTC, guparan commented on SofaKernel/modules/Sofa.Type/compat/sofa/defaulttype/Quat.h
> +// SOFA_DEPRECATED_HEADER(v21.12, "sofa/type/Quat.h")
Add a quick comment to explain why we keep that.

2021-02-17 09:58 UTC, guparan commented on SofaKernel/modules/Sofa.Type/compat/sofa/helper/DualQuat.h
> +// SOFA_DEPRECATED_HEADER(v21.12, "sofa/type/DualQuat.h")
Add a quick comment to explain why we keep that.

2021-02-17 09:58 UTC, guparan commented on SofaKernel/modules/Sofa.Type/compat/sofa/helper/DualQuat.inl
> +// SOFA_DEPRECATED_HEADER(v21.12, "sofa/type/DualQuat.inl")
Add a quick comment to explain why we keep that.

2021-02-17 09:58 UTC, guparan commented on SofaKernel/modules/Sofa.Type/compat/sofa/helper/Quater.h
> +//SOFA_DEPRECATED_HEADER(v21.12, "sofa/type/Quat.h")
Add a quick comment to explain why we keep that.

2021-02-17 09:58 UTC, guparan commented on SofaKernel/modules/Sofa.Type/compat/sofa/helper/Quater.inl
> +// SOFA_DEPRECATED_HEADER(v21.12, "sofa/type/Quat.inl")
Add a quick comment to explain why we keep that.

2021-02-17 09:58 UTC, guparan commented on SofaKernel/modules/Sofa.Type/src/sofa/type/MatSym.h
> +            //msg_error("MatSym") << "invertMatrix (general case) finds too small determinant: " << pivot << " for matrix = " << from;
To be removed?

2021-02-17 09:58 UTC, guparan commented on SofaKernel/modules/Sofa.Type/src/sofa/type/MatSym.h
> +        //msg_error("MatSym") << "invertMatrix (special case 3x3) finds too small determinant: " << det << " for matrix = " << from;
To be removed?

2021-02-17 09:58 UTC, guparan commented on SofaKernel/modules/Sofa.Type/src/sofa/type/MatSym.h
> +        //msg_error("MatSym") << "invertMatrix (special case 2x2) finds too small determinant: " << det << " for matrix = " << from;
To be removed?

2021-02-17 09:58 UTC, guparan commented on SofaKernel/modules/Sofa.Type/src/sofa/type/Quat.h
> +    /// Returns true if norm of Quatnion is one, false otherwise.
Auto-replace issue :eyes:

2021-02-18 11:48 UTC, fredroy commented
[ci-build][force-full-build][with-all-tests]

2021-02-24 16:40 UTC, merged