[CGAL] Fix compilation errors related to SOFA.GL and types converted to DataTypes
sofa-framework/sofa pull request #2065
Opened 2021-05-06 15:04 UTC by pedroperrusi

Hello Everyone,

@ziqiu-zeng  noticed compilation errors in the CGALPlugin with the latest changes in SOFA.

Here are the quick fixes we came up together.

Please let us know if anything else should be needed

Pedro

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-05-06 15:16 UTC, fredroy commented
I just saw that only `applications/plugins/CGALPlugin/src/CGALPlugin/CuboidMesh.inl` needs OpenGL (calling directly gl*() functions).
I guess it was easier for you to include directly Sofa.GL but in my mind, it would be better to remove all the direct calls to OpenGL and use the drawtool functions (from `sofa/helper/visual/DrawTool.h`), especially it seems it is only to render points and tetrahedra.
Thus you wont need Sofa.GL (and be able to compile CGALPlugin without OpenGL)

2021-05-07 08:39 UTC, pedroperrusi commented
I completely agree @fredroy 
There seems to be a lot to refactor and clean in the CGALPlugin and maybe it deserves a big PR on its own.
I'll modernize our calls to the draw functions on this component and let you know when I'm done

2021-05-10 11:46 UTC, fredroy requested changes
Just correct a typo (suggestion) and we are good to go

2021-05-10 11:46 UTC, fredroy commented on applications/plugins/CGALPlugin/src/CGALPlugin/CuboidMesh.inl
> +    ()    if (m_viewPoints.getValue())
```suggestion
    if (m_viewPoints.getValue())
```

2021-05-10 14:00 UTC, pedroperrusi commented on applications/plugins/CGALPlugin/src/CGALPlugin/CuboidMesh.inl
> +    ()    if (m_viewPoints.getValue())
Thanks for the tip
It should be committed by now ;)

2021-05-10 14:41 UTC, fredroy approved these changes

2021-05-10 20:55 UTC, merged