[SofaBaseLinearSolver] Document and clean CGLineaSolver
sofa-framework/sofa pull request #2098
Opened 2021-05-18 15:43 UTC by hugtalbot

- Document the steps of the CGLinearSolver
- Remove the useless data verbose
- Use d_ for data name
- Propagate this joyeuserie

:man_dancing: 

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-05-19 07:49 UTC, alxbilger requested changes
Good intentions ;)
Build is currently failing

2021-05-19 07:49 UTC, alxbilger commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.h
> +    //Temporary function to warn the user when old attribute names are used until v20.12
v21.12?

2021-05-19 07:49 UTC, alxbilger commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.inl
> +    msg_info_when(printLog) << "b = " << b ;
I think `msg_info()` is called only if `printLog` is true. So `msg_info_when(printLog)` is redundant. Prefer `msg_info() << "b = " << b ;`

2021-05-19 07:49 UTC, alxbilger commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.inl
> +        for( nb_iter=1; nb_iter<=d_maxIter.getValue(); nb_iter++ )
Cosmetic: add spaces around `<=` and `=`:
```for( nb_iter = 1; nb_iter <= d_maxIter.getValue(); nb_iter++ )```

2021-05-19 07:49 UTC, alxbilger commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.inl
> +            /// Compute ρ = r²
Is it a good practice to have special characters, even in comments? I don't know

2021-05-19 07:49 UTC, alxbilger commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.inl
> +                    if( printLog )
Same here, condition on `printLog` is redundant

2021-05-19 07:49 UTC, alxbilger commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.inl
> +            if( printLog )
Redundant `printLog` condition

2021-05-19 07:49 UTC, alxbilger commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.inl
> +            if( printLog )
Redundant `printLog` condition

2021-05-19 07:49 UTC, alxbilger commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.inl
> +                        if( printLog )
Redundant `printLog` condition

2021-05-19 07:49 UTC, alxbilger commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.inl
> +                if( printLog )
Redundant `printLog` condition

2021-05-19 07:49 UTC, alxbilger commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.inl
> +    dmsg_info_when( printLog ) <<"solve, solution = "<< x ;
Redundant `printLog` condition

2021-05-19 07:49 UTC, alxbilger commented on SofaKernel/modules/SofaImplicitOdeSolver/SofaImplicitOdeSolver_test/EulerImplicitSolverDynamic_test.cpp
> +        cgLinearSolver->d_maxIter=3000;
Cosmetic: add spaces around `=`

2021-05-26 09:18 UTC, fredroy commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.h
> +            msg_warning() << "input data 'verbose' changed for 'printLog', please update your scene (see PR#2XXX)";
```suggestion
            msg_warning() << "input data 'verbose' changed for 'printLog', please update your scene (see PR#2098)";
```

2021-06-16 07:40 UTC, alxbilger requested changes
I approve this PR, but I request a minor change in the comment of `setSystemMBKMatrix`

2021-06-16 07:40 UTC, alxbilger commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.inl
> +/// Pass the coefficients multiplying the matrices M, B and K from the ODE to the LinearSolver (and includes a resetSystem)
This is the case only for `GraphScattered` types. With other types, the global system matrix is setup, and `addMBKToMatrix` is called.

2021-06-16 10:11 UTC, alxbilger requested changes

2021-06-16 10:11 UTC, alxbilger commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/CGLinearSolver.inl
> +/// it passes the coefficients multiplying the matrices M, B and K from the ODE to the LinearSolver (MechanicalOperations::setKFactor) adn includes a resetSystem
Typo
```suggestion
/// it passes the coefficients multiplying the matrices M, B and K from the ODE to the LinearSolver (MechanicalOperations::setKFactor) and includes a resetSystem
```

2021-06-16 15:46 UTC, merged