[SofaGraphComponent] Clean format of RequiredPlugin message
sofa-framework/sofa pull request #2111
Opened 2021-05-21 11:51 UTC by alxbilger

- Avoid trailing comma
- Consistent indentation
- Typo 'begining' -> 'beginning'
- Sort by name (bonus)

# Before
```
[WARNING] [SceneCheckMissingRequiredPlugin] This scene is using component defined in plugins but is not importing the required plugins.  
  Your scene may not work on a sofa environment with different pre-loaded plugins.  
  To fix your scene and remove this warning you just need to cut & paste the following lines at the begining of your scene (if it is a .scn):   
  <RequiredPlugin name='MultiThreading'/>   
<RequiredPlugin name='SofaConstraint'/>   
<RequiredPlugin name='SofaImplicitOdeSolver'/>   
<RequiredPlugin name='SofaLoader'/>   
<RequiredPlugin name='SofaMeshCollision'/>   
<RequiredPlugin name='SofaOpenglVisual'/>   
<RequiredPlugin name='SofaSimpleFem'/>   
```

# After
```
[WARNING] [SceneCheckMissingRequiredPlugin] This scene is using component defined in plugins but is not importing the required plugins.  
  Your scene may not work on a sofa environment with different pre-loaded plugins.  
  To fix your scene and remove this warning you just need to cut & paste the following lines at the beginning of your scene (if it is a .scn):   
  <RequiredPlugin name='MultiThreading'/>   
  <RequiredPlugin name='SofaConstraint'/>   
  <RequiredPlugin name='SofaImplicitOdeSolver'/>   
  <RequiredPlugin name='SofaLoader'/>   
  <RequiredPlugin name='SofaMeshCollision'/>   
  <RequiredPlugin name='SofaOpenglVisual'/>   
  <RequiredPlugin name='SofaSimpleFem'/>   
```

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-05-26 10:09 UTC, guparan requested changes

2021-05-26 10:09 UTC, guparan commented on modules/SofaGraphComponent/src/SofaGraphComponent/SceneCheckMissingRequiredPlugin.cpp
>              tmp <<"]-->" << msgendl;
```suggestion
            tmp <<"] -->" << msgendl;
```

2021-05-26 10:09 UTC, guparan commented on modules/SofaGraphComponent/src/SofaGraphComponent/SceneCheckMissingRequiredPlugin.cpp
> +            tmp << indent << "<RequiredPlugin name='"<<kv.first<<"'/> <!-- Needed to use components [";
```suggestion
            tmp << indent << "<RequiredPlugin name=\""<<kv.first<<"\"/> <!-- Needed to use components [";
```

2021-05-26 10:11 UTC, guparan approved these changes

2021-05-27 06:58 UTC, epernod commented
[ci-build]

2021-05-27 07:44 UTC, merged