[CGALPlugin] new features
sofa-framework/sofa pull request #2124
Opened 2021-05-26 15:43 UTC by EulalieCoevoet

Adds new features with examples:
- PoissonSurfaceReconstruction
- FrontSurfaceReconstruction
- UpsamplePointCloud
- BooleanOperations

Fixes compilation:
- Sofa.GL

Minor cleaning in DecimateMesh:
- Data member variables names with d_

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-06-07 08:15 UTC, fredroy requested changes

2021-06-07 08:15 UTC, fredroy commented on applications/plugins/CGALPlugin/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} PUBLIC SofaCore SofaSimulationCommon Sofa.GL)
> 
> Fixes compilation:
> 
>     * Sofa.GL
> 

This issue was fixed in #2065 so you dont need to add Sofa.GL

2021-06-07 15:34 UTC, fredroy approved these changes

2021-06-08 07:39 UTC, epernod requested changes
Thanks for the contribution with scenes example. 
It would be nice to put some pictures of the scene results either here in the PR description or in the plugin Doc. So we will be able to check in the future if the behavior is still the one expected from the component (unless you prefer to write some tests ;) ).

2021-06-08 07:39 UTC, epernod commented on applications/plugins/CGALPlugin/scenes/UpsamplePointCloud.scn
> +	<!-- <Node name="FrontSurfaceReconstruction">
could you remove commented code

2021-06-08 07:39 UTC, epernod commented on applications/plugins/CGALPlugin/src/CGALPlugin/DecimateMesh.h
> +    sofa::core::objectmodel::Data<VecCoord> d_inVertices; ///< List of vertices
renaming the Data is good. We just need to put the breaking flag to this PR

2021-06-08 21:13 UTC, epernod approved these changes

2021-06-09 14:39 UTC, merged