[Sofa.Core] Move eq,peq utilities functions to a standalone file
sofa-framework/sofa pull request #2137
Opened 2021-05-31 09:03 UTC by fredroy

eq/peq() functions defined in IdentityMapping should be moved elsewhere; no need to know IdentityMapping to use them.

These functions are now located in a file core/MappingHelper.h alongside Mapping.h, as these functions would likely be used only by mappings.

Some points to discuss:
 - header filename ?
 - eq/peq functions name themselves are not very informative... should it be assign() and add() for example ?

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-06-07 16:06 UTC, fredroy commented
[ci-build][with-all-tests]

2021-06-08 14:08 UTC, guparan requested changes

2021-06-08 14:08 UTC, guparan commented on SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/IdentityMapping.h
> +        "v21.06 (PR#21XX)", "v21.06", "You need to include <sofa/core/MappingHelper.h> and use sofa::core::eq(...) instead)")
```suggestion
        "v21.06 (PR#2137)", "v21.06 (PR#2137)", "You need to include <sofa/core/MappingHelper.h> and use sofa::core::eq(...) instead.")
```

2021-06-08 14:08 UTC, guparan commented on SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/IdentityMapping.h
> +        "v21.06 (PR#21XX)", "v21.06", "You need to include <sofa/core/MappingHelper.h> and use sofa::core::peq(...) instead)")
```suggestion
        "v21.06 (PR#2137)", "v21.06 (PR#2137)", "You need to include <sofa/core/MappingHelper.h> and use sofa::core::peq(...) instead.")
```

2021-06-10 08:23 UTC, guparan approved these changes

2021-06-16 07:53 UTC, alxbilger commented
I am for a discussion on the filename. I assume it could be used in other places than mappings.

2021-06-23 10:10 UTC, merged