[All] remove method applyTestCreateFunction in TopologyDataHandler
sofa-framework/sofa pull request #2171
Opened 2021-06-10 07:21 UTC by epernod

this method was never called and is not useful.
Add Disabled message.

This need to be merged before #2114

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-06-11 08:26 UTC, epernod commented
[ci-build][with-all-tests]

2021-06-16 10:28 UTC, alxbilger commented on SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataHandler.h
> +    // TODO change message before PR
Is this TODO still necessary?

2021-06-16 15:36 UTC, guparan commented on SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataHandler.h
> +    SOFA_ATTRIBUTE_DISABLED("v21.06 (PR#2171)", "v21.06 (PR#2171)", "This method has been removed as it has never been used and is not needed.")
Maybe add a fallback method (applyCreateFunction?) in the help message.

2021-06-16 15:37 UTC, guparan commented on SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataHandler.h
> +    // TODO change message before PR
Obviously no

2021-06-16 15:38 UTC, guparan requested changes

2021-06-16 15:38 UTC, guparan commented on SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataHandler.h
> +    // TODO change message before PR
```suggestion
```

2021-06-16 15:38 UTC, guparan commented on SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyDataHandler.h
> +    SOFA_ATTRIBUTE_DISABLED("v21.06 (PR#2171)", "v21.06 (PR#2171)", "This method has been removed as it has never been used and is not needed.")
Maybe add a fallback method (applyCreateFunction?) in the help message.

2021-06-17 08:41 UTC, alxbilger approved these changes

2021-06-18 09:46 UTC, merged