[scenes] Update tetrahedron and tetrahedralCorotational FEM scenes
sofa-framework/sofa pull request #2172
Opened 2021-06-10 07:34 UTC by epernod

Update scene to show the different methods apply on a same beam  (even if I can't see the diff...) 
Move the old TetrahedronFEMForceField.scn into TetrahedronFEMForceField_Chain.scn

TetrahedralCorotationalFEMForceField.scn
![Sofa - C__projects_sofa-src_examples_Components_forcefield_TetrahedralCorotationalFEMForceField scn 6_10_2021 9_28_28 AM](https://user-images.githubusercontent.com/21199245/121483745-d346a380-c9ce-11eb-8f53-ef4576139da9.png)

TetrahedronFEMForceField.scn
![Sofa - C__projects_sofa-src_examples_Components_forcefield_TetrahedralCorotationalFEMForceField scn 6_10_2021 9_26_44 AM](https://user-images.githubusercontent.com/21199245/121483753-d477d080-c9ce-11eb-968a-57009c936706.png)

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-06-11 07:15 UTC, epernod commented
[ci-build][with-all-tests]

2021-06-21 14:41 UTC, alxbilger requested changes
I am ok for these new examples.

The only thing I wonder is whether the collision detection components are necessary. In your scene, you can remove them because they are not of any use. However, having them in the scene creates consistency over all the examples. Any thought @hugtalbot @fredroy @guparan

2021-06-21 14:41 UTC, alxbilger commented on examples/Components/forcefield/TetrahedralCorotationalFEMForceField.scn
> +    <RequiredPlugin pluginName='SofaEngine'/>
- `name` instead of `pluginName`
- double quotes instead of single quotes

This should apply in all your changes

2021-06-24 09:26 UTC, epernod commented
> 
> 
> Moreover the image you show for _TetrahedronFEMForceField.scn_ displays 4 beams while only 3 are defined in the scene, maybe some mismatch?

you are right I forgot to cherry pick one commit. Here it is.

2021-06-24 09:32 UTC, epernod commented
[ci-build][with-all-tests]

2021-06-25 14:51 UTC, merged