Triangle numerical integration
sofa-framework/sofa pull request #219
Opened 2017-03-24 14:33 UTC by hdeling

This pull-request adds the following features 
- add numerical integration on tetrahedra and triangles
- add a mechanical tag on a PointSetGeometry object in order to find its associated MechanicalObject
- add the orthogonal of a 2d vector
- add support of high order elements in VTK and Gmesh mesh loaders

It also fixes some bugs 
-Quand2Triangle Topologivcal mapping

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings nor unit test failures.
- [ ] does not break existing scenes.
- [ ] does not break API compatibility.
- [ ] has been reviewed and agreed to be transitional.
- [ ] is more than 1 week old.

**Reviewers will merge only if all these checks are true.**

2017-03-24 15:04 UTC, damienmarchal commented on modules/SofaTopologyMapping/Quad2TriangleTopologicalMapping.cpp
> +            //for (int i=0; i<fromModel->getNbPoints(); i++)
Shouldn't the commented code removed ?

2017-03-24 15:06 UTC, damienmarchal commented on SofaKernel/modules/SofaBaseTopology/SofaBaseTopology_test/TriangleNumericalIntegration_test.cpp
> +        NumericalIntegrationDescriptor &nid=geo->getTriangleNumericalIntegrationDescriptor();
Identation looks weird.

2017-03-24 15:07 UTC, damienmarchal commented
Hi @hdeling,

Thank you for your PR. 
At first glance it looks nice only cosmetic/minor details.

2017-03-24 15:16 UTC, ChristianDuriez requested changes
Thanks Hervé ! 
Very useful changes.  I didn't really get if it can be used for computation of internal force in Triangle or Tetrahedron ForceFields ?

Only the same change requested
put d_  before datatypes 
(see N5 at https://github.com/sofa-framework/sofa/blob/master/GUIDELINES.md)

2017-03-24 15:16 UTC, ChristianDuriez commented on SofaKernel/framework/sofa/core/loader/MeshLoader.cpp
> +    , highOrderEdgePositions(initData(&highOrderEdgePositions,"highOrderEdgePositions","High order edge points of the mesh loaded"))
Hi Hervé !
Now we have naming conventions in SOFA:
https://github.com/sofa-framework/sofa/blob/master/GUIDELINES.md
see Rule N5 in Naming section: d_ for data

2017-03-24 15:16 UTC, ChristianDuriez commented on SofaKernel/framework/sofa/core/loader/MeshLoader.h
> +    Data< helper::vector< HighOrderEdgePosition > > highOrderEdgePositions;
Here also, naming data convention d_

2017-03-24 15:16 UTC, ChristianDuriez commented on SofaKernel/modules/SofaBaseTopology/PointSetGeometryAlgorithms.h
> +    Data<std::string> m_tagMechanics;
d_tagMechanics;

m_ is for other variable names [N7]

2017-03-24 15:16 UTC, ChristianDuriez commented on SofaKernel/modules/SofaBaseTopology/PointSetGeometryAlgorithms.h
>      Data<float> showIndicesScale;
These data could also be renamed

2017-03-24 15:16 UTC, ChristianDuriez commented on modules/SofaGeneralEngine/GenerateGrid.inl
> +    addInput(&f_minCorner);
If you can change all the data from
f_ 
to 
d_ 
it would be great ;-))

2017-03-24 15:37 UTC, hdeling commented on modules/SofaTopologyMapping/Quad2TriangleTopologicalMapping.cpp
> +            //for (int i=0; i<fromModel->getNbPoints(); i++)
Yes of course.

2017-03-27 14:17 UTC, ChristianDuriez approved these changes

2017-03-28 09:53 UTC, guparan commented
Shouldn't we revert .gitignore modification in cfa5a44 ?

2017-03-28 13:17 UTC, hdeling commented
Yes probably should remove the commit on .gitignore.

2017-04-12 09:02 UTC, BenjaminGilles approved these changes
thanks Hervé, this looks all good to me.
minor comment:  some functions might be moved from  SofaBaseTopology/CommonAlgorithms.h  to defaulttype/Vec.h

2017-04-24 09:01 UTC, damienmarchal commented
[ci-build]

2017-04-26 07:54 UTC, merged

2017-04-28 07:49 UTC, damienmarchal commented
Hi all,

It seems there a lot of new test-scene failures since the merge of this PR. 
https://ci.inria.fr/sofa-ci/job/centos_clang-3.4_options/635/console

We probably need to fix that in a new PR.