[all] Minor code cleaning
sofa-framework/sofa pull request #2225
Opened 2021-07-05 13:17 UTC by alxbilger

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-07-05 13:36 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintCorrection.cpp
> +        msg_info() << m_linearSolver->getName();
```suggestion
    for (auto & linearSolver : m_linearSolvers)
        msg_info() << linearSolver->getName();
```

2021-07-05 13:41 UTC, fredroy requested changes

2021-07-05 13:41 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintCorrection.cpp
> +        m_linearSolver->rebuildSystem(massFactor, forceFactor);
```suggestion
    for (auto & linearSolver : m_linearSolvers)
        linearSolver->rebuildSystem(massFactor, forceFactor);
```

2021-07-05 13:41 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintCorrection.cpp
> +    for (auto & m_linearSolver : m_linearSolvers)
```suggestion
    for (auto & linearSolver : m_linearSolvers)
```

2021-07-05 13:41 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintCorrection.cpp
> +        m_linearSolver->buildComplianceMatrix(cparams, W, factor);
```suggestion
        linearSolver->buildComplianceMatrix(cparams, W, factor);
```

2021-07-05 13:41 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintCorrection.cpp
> +    for (auto & m_linearSolver : m_linearSolvers)
```suggestion
    for (auto & linearSolver : m_linearSolvers)
```

2021-07-05 13:41 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintCorrection.cpp
> +        m_linearSolver->applyConstraintForce(cparams, dx, lambda);
```suggestion
        linearSolver->applyConstraintForce(cparams, dx, lambda);
```

2021-07-05 13:41 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintCorrection.cpp
> +    for (auto & m_linearSolver : m_linearSolvers)
```suggestion
    for (auto & linearSolver : m_linearSolvers)
```

2021-07-05 13:41 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintCorrection.cpp
> +        m_linearSolver->getContext()->executeVisitor(&v);
```suggestion
        MechanicalIntegrateConstraintsVisitor v(cparams, positionFactor, velocityFactor, correction, dxId, xId, vId, linearSolver->getSystemMultiMatrixAccessor());
        linearSolver->getContext()->executeVisitor(&v);
```

2021-07-05 13:41 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintCorrection.cpp
> +    for (auto & m_linearSolver : m_linearSolvers)
```suggestion
    for (auto & linearSolver : m_linearSolvers)
```

2021-07-05 13:41 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintCorrection.cpp
> +        m_linearSolver->computeResidual(params, lambda);
```suggestion
        linearSolver->computeResidual(params, lambda);
```

2021-07-05 13:41 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintSolver.cpp
> +    for(auto & constraintsResolution : constraintsResolutions)
Reference to a pointer ?

2021-07-05 13:51 UTC, alxbilger commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintSolver.cpp
> +    for(auto & constraintsResolution : constraintsResolutions)
good catch

2021-07-06 07:32 UTC, fredroy requested changes

2021-07-06 07:32 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintSolver.cpp
> +        for (auto & constraintCorrection : constraintCorrections)
Actually this file has a lot of cases where it takes now a ref to a pointer

2021-07-06 07:32 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintSolver.cpp
> +    for (auto & constraintCorrection : constraintCorrections)
here...

2021-07-06 07:32 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintSolver.cpp
> +        for (auto & constraintCorrection : constraintCorrections)
here...

2021-07-06 07:32 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintSolver.cpp
> +        for (auto cc : constraintCorrections)
and from here, I guess it should be auto* cc ? ( but I guess in this case it does not matter actually)

2021-07-06 07:32 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintSolver.cpp
> +            for (auto cc : constraintCorrections)
bis

2021-07-06 07:32 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintSolver.cpp
> +    for (auto cc : constraintCorrections)
ter

2021-07-06 07:32 UTC, fredroy commented on modules/SofaConstraint/src/SofaConstraint/GenericConstraintSolver.cpp
> +    for (auto cc : constraintCorrections)
quater

2021-07-06 08:11 UTC, alxbilger commented
[ci-build][with-all-tests]

2021-07-06 09:20 UTC, fredroy commented
seems like it introduces two new failed unit test:
 - UnitTests.Compliant_test/Batch/Python_scene_test.sofa_python_scene_tests/2
 - UnitTests.SofaCarving_test/SofaCarving_test.testdoCarving
 
 I suppose investigating the SofaCarving test will fix the Compliant one

2021-07-06 15:33 UTC, fredroy approved these changes
Great, tests are passing 👍

2021-07-09 17:15 UTC, merged