Refactor MatrixLinearSolver step1
sofa-framework/sofa pull request #2238
Opened 2021-07-09 09:33 UTC by damienmarchal

As usual the idea is to make the object more opaque so we can reduce the #include pressure. 

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-07-09 10:23 UTC, damienmarchal commented
[ci-build]

2021-07-09 12:22 UTC, alxbilger requested changes
Great! I just have a minor suggestion, otherwise it looks good to me.

2021-07-09 12:22 UTC, alxbilger commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/MatrixLinearSolver.h
> +#include <sofa/core/behavior/fwd.h>    // Because this is where is RotationMatrix
```suggestion
#include <sofa/core/behavior/fwd.h>    // Because this is where RotationMatrix is
```

2021-07-09 12:35 UTC, damienmarchal commented
Thanks @alxbilger... the CI does not agree :)

2021-07-15 08:49 UTC, fredroy commented on SofaKernel/modules/SofaBaseLinearSolver/src/SofaBaseLinearSolver/MatrixLinearSolver.inl
> +defaulttype::BaseMatrix*   MatrixLinearSolver<Matrix,Vector>::MatrixLinearSolver<Matrix,Vector>::getSystemBaseMatrix() { return linearSystem->systemMatrix; }
```suggestion
defaulttype::BaseMatrix*  MatrixLinearSolver<Matrix,Vector>::getSystemBaseMatrix() { return linearSystem->systemMatrix; }
```

2021-07-26 15:24 UTC, damienmarchal commented
[ci-build]

2021-08-27 18:02 UTC, alxbilger commented
@damienmarchal I made the merge of master into your branch. Can you allow me to push into your branch?

2022-03-02 09:46 UTC, closed without merging