[SofaMiscFEM_test] Add class to test and compare TriangleFEM and TriangularFEMForceField
sofa-framework/sofa pull request #2249
Opened 2021-07-13 15:18 UTC by epernod

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-07-15 07:59 UTC, fredroy requested changes
to fix the compilation error with gcc/clang

2021-07-15 07:59 UTC, fredroy commented on modules/SofaMiscFem/SofaMiscFem_test/TriangleFEMForceField_test.cpp
> +        MState::SPtr dofs = m_root->getTreeObject<MState>();
```suggestion
        auto dofs = m_root->getTreeObject<MState>();
```

2021-07-15 12:04 UTC, fredroy commented
[ci-build]

2021-07-19 15:13 UTC, guparan commented
Nice work @epernod :+1:
If you already know what must be done to fix the tests, I'm for doing it in this PR !

2021-07-20 12:09 UTC, epernod commented
> 
> 
> Nice work @epernod 👍
> If you already know what must be done to fix the tests, I'm for doing it in this PR !

ok I fixed some of them. The last 2 failing tests need big changes. we can comment them for the moment.

2021-07-21 09:08 UTC, guparan requested changes

2021-07-21 09:08 UTC, guparan commented on modules/SofaMiscFem/src/SofaMiscFem/TriangleFEMForceField.inl
> +    }
```suggestion
    if (method == SMALL)
    {
        initSmall();
    }
    else
    {
        initLarge();
    }
```

2021-07-21 09:08 UTC, guparan commented on modules/SofaMiscFem/src/SofaMiscFem/TriangleFEMForceField.inl
> +    }
```suggestion
    if (method == SMALL)
    {
        //    initSmall();  // useful ? The rotations are recomputed later
    }
    else
    {
        initLarge(); // compute the per-element strain-displacement matrices
    }
```

2021-07-21 09:08 UTC, guparan commented on modules/SofaMiscFem/src/SofaMiscFem/TriangleFEMForceField.inl
> +    }
```suggestion
    else
    {
        msg_warning() << "Input Method is not possible: " << val << ", should be 0 (Large) or 1 (Small). Setting default value: Large";
        method = LARGE;
    }
```

2021-07-21 09:08 UTC, guparan commented on modules/SofaMiscFem/src/SofaMiscFem/TriangularFEMForceField.inl
> +    }
```suggestion
    else
    {
        type::vector<Real> newP(1, val);
        f_poisson.setValue(newP);
    }
```

2021-07-21 09:08 UTC, guparan commented on modules/SofaMiscFem/src/SofaMiscFem/TriangularFEMForceField.inl
> +        }
```suggestion
        if (val < 0)
        {
            msg_warning() << "Input Poisson Coefficient at position: " << id << " is not possible: " << val << ", setting default value: 0.3";
            val = 1000;
        }
```

2021-07-21 09:08 UTC, guparan commented on modules/SofaMiscFem/src/SofaMiscFem/TriangularFEMForceField.inl
> +    }
```suggestion
    else
    {
        type::vector<Real> newY(1, val);
        f_young.setValue(newY);
    }
```

2021-07-21 09:08 UTC, guparan commented on modules/SofaMiscFem/src/SofaMiscFem/TriangularFEMForceField.inl
> +        }
```suggestion
        if (val < 0)
        {
            msg_warning() << "Input Young Modulus at position: " << id << " is not possible: " << val << ", setting default value: 1000";
            val = 1000;
        }
```

2021-07-21 09:10 UTC, epernod commented
https://stackoverflow.com/questions/7208070/googletest-how-to-skip-a-test

2021-07-21 23:25 UTC, epernod commented
[ci-build][with-all-tests]

2021-07-23 09:28 UTC, merged