[SofaKernel] Disable identified failing tests
sofa-framework/sofa pull request #2290
Opened 2021-08-05 07:34 UTC by hugtalbot

This PR disable tests that identify known issues in SOFA.
However, failing tests prevent from an efficient review of the PR. We disable them for now, but GitHub issues should be created for each test.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-08-18 08:54 UTC, epernod requested changes
add todo comment in code

2021-08-18 08:54 UTC, epernod commented on SofaKernel/modules/SofaCore/SofaCore_simutest/objectmodel/BaseContext_test.cpp
```suggestion
// TODO: hTalbot 2021-08-18: This test should be reactivated as soon as the identified problem has been fixed
```

2021-08-25 08:53 UTC, fredroy commented on SofaKernel/modules/SofaHelper/SofaHelper_test/Utils_test.cpp
> +TEST(UtilsTest, DISABLED_string_to_widestring_to_string)
This test should be fixable actually

2021-08-26 11:52 UTC, fredroy commented on SofaKernel/modules/SofaHelper/SofaHelper_test/Utils_test.cpp
> +TEST(UtilsTest, DISABLED_string_to_widestring_to_string)
After further digging, it appears this test fails only if the system locale is not UTF8 (not unicode).
- `LC_ALL=C ./SofaHelper_test --gtest_filter="UtilsTest.string_to_widestring_to_string` fails
- `LC_ALL=en_US.UTF-8 ./SofaHelper_test --gtest_filter="UtilsTest.string_to_widestring_to_string` succeeds
which makes sense in my mind because if it is not utf8, wstring does not really makes sense (?)

In the end, either we let it DISABLED_ like your did @hugtalbot , or we force UTF8 on the CI for the linux systems. Windows and Mac are already unicode by default I believe

2021-09-08 16:32 UTC, fredroy commented
@hugtalbot `getobjects` test should be solved here #2326 and `string_wstring` here #2320

2021-09-21 07:40 UTC, fredroy commented
[ci-build]

2021-09-21 11:01 UTC, epernod commented
[ci-build]

2021-09-21 18:34 UTC, epernod commented on SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/EdgeSetTopologyContainer.cpp
> +        msg_warning() << "return (d_edge.getValue())[i]: " << (d_edge.getValue())[i];
for debug because it fails only on the CI. The pr is not ready

2021-09-21 18:35 UTC, epernod commented
[ci-build][with-all-tests]

2021-09-22 07:08 UTC, epernod commented
[ci-build][with-all-tests]

2021-09-22 09:53 UTC, epernod commented
[ci-build][with-all-tests]

2021-09-22 20:32 UTC, fredroy commented
[ci-build][with-all-tests]

2021-09-22 21:34 UTC, merged