[SofaMiscForceField] Fix addForce function in MeshMatrixMass
sofa-framework/sofa pull request #2305
Opened 2021-08-24 13:03 UTC by hugtalbot

Fix bug introduced in #2193 and reported by @jnbunet in the Caribou CI! Thanks again @jnbrunet and @epernod for the discussions !

- Homogeneize the use of the massLumpingCoeff.
- In the test, only cosmetic change.

Fixes #2301

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-08-25 09:42 UTC, alxbilger commented on modules/SofaMiscForceField/src/SofaMiscForceField/MeshMatrixMass.inl
> +        SOFA_UNUSED(EdgeMass);
```suggestion
```

2021-08-25 09:42 UTC, guparan requested changes
:wave:

2021-08-25 09:42 UTC, guparan commented on modules/SofaMiscForceField/src/SofaMiscForceField/MeshMatrixMass.inl
> +        SOFA_UNUSED(EdgeMass);
```suggestion
    else
    {
        SOFA_UNUSED(EdgeMass);
    }
```

2021-08-25 09:42 UTC, guparan commented on modules/SofaMiscForceField/src/SofaMiscForceField/MeshMatrixMass.inl
> +                totalMass += 3.0 * mass * MMM->m_massLumpingCoeff;
```suggestion
            else
            {
                totalMass += 3.0 * mass * MMM->m_massLumpingCoeff;
            }
```

2021-08-25 09:42 UTC, guparan commented on modules/SofaMiscForceField/src/SofaMiscForceField/MeshMatrixMass.inl
> +                totalMass -= 3.0 * mass * MMM->m_massLumpingCoeff;
```suggestion
            else
            {
                totalMass -= 3.0 * mass * MMM->m_massLumpingCoeff;
            }
```

2021-08-25 09:42 UTC, guparan commented on modules/SofaMiscForceField/src/SofaMiscForceField/MeshMatrixMass.inl
> +                totalMass += 4.0 * mass * MMM->m_massLumpingCoeff;
```suggestion
            else
            {
                totalMass += 4.0 * mass * MMM->m_massLumpingCoeff;
            }
```

2021-08-25 09:42 UTC, guparan commented on modules/SofaMiscForceField/src/SofaMiscForceField/MeshMatrixMass.inl
> +                totalMass -= 4.0 * mass * MMM->m_massLumpingCoeff;
```suggestion
            else
            {
                totalMass -= 4.0 * mass * MMM->m_massLumpingCoeff;
            }
```

2021-08-25 09:42 UTC, guparan commented on modules/SofaMiscForceField/src/SofaMiscForceField/MeshMatrixMass.inl
> +                totalMass += 4.0 * mass * MMM->m_massLumpingCoeff;
```suggestion
            else
            {
                totalMass += 4.0 * mass * MMM->m_massLumpingCoeff;
            }
```

2021-08-25 09:42 UTC, guparan commented on modules/SofaMiscForceField/src/SofaMiscForceField/MeshMatrixMass.inl
> +                totalMass -= 4.0 * mass * MMM->m_massLumpingCoeff;
```suggestion
            else
            {
                totalMass -= 4.0 * mass * MMM->m_massLumpingCoeff;
            }
```

2021-08-25 09:42 UTC, guparan commented on modules/SofaMiscForceField/src/SofaMiscForceField/MeshMatrixMass.inl
> +                totalMass += 8.0 * mass * MMM->m_massLumpingCoeff;
```suggestion
            else
            {
                totalMass += 8.0 * mass * MMM->m_massLumpingCoeff;
            }
```

2021-08-25 09:42 UTC, guparan commented on modules/SofaMiscForceField/src/SofaMiscForceField/MeshMatrixMass.inl
> +                totalMass -= 8.0 * mass * MMM->m_massLumpingCoeff;
```suggestion
            else
            {
                totalMass -= 8.0 * mass * MMM->m_massLumpingCoeff;
            }
```

2021-09-01 09:16 UTC, fredroy commented
[ci-build][force-full-build][with-all-tests]

2021-09-01 15:33 UTC, guparan commented
A lot of regression tests are failing. Maybe their references should be updated?
@hugtalbot

2021-09-07 09:09 UTC, merged