[Sofa.LinearAlgebra] Dispatch EigenMatrix and EigenVector from Eigen2Solver
sofa-framework/sofa pull request #2339
Opened 2021-09-13 13:36 UTC by fredroy

Desc: todo

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-09-13 21:24 UTC, fredroy commented
[ci-build][with-all-tests]

2021-09-15 07:56 UTC, alxbilger requested changes
It seems there are more changes than I expected. A description of the changes would help me to understand.

I also have the suggestion to remove the commented code.

It also worth mentioning that you add the Eigen dependency to Sofa.LinearAlgebra, which is fine for me.

2021-09-15 07:56 UTC, alxbilger commented on SofaKernel/modules/Sofa.LinearAlgebra/src/sofa/linearalgebra/EigenBaseSparseMatrix.h
> +    ///// View this matrix as a MultiMatrix
You introduced commented code. Is is relevent?

2021-09-15 07:56 UTC, alxbilger commented on SofaKernel/modules/Sofa.LinearAlgebra/src/sofa/linearalgebra/EigenSparseMatrix.h
> +    //template<class DataVecDeriv>
Again commented code

2021-09-22 15:32 UTC, fredroy commented
[ci-build][with-all-tests]

2021-09-29 08:28 UTC, guparan commented on SofaKernel/modules/Sofa.LinearAlgebra/src/sofa/linearalgebra/EigenVector.h
> +//#define EIGEN_CHECK
```suggestion

```

2021-09-29 18:21 UTC, merged