[SofaBaseTopology] Add method to register callbacks directly using the topologyData
sofa-framework/sofa pull request #2375
Opened 2021-10-01 21:09 UTC by epernod

Add method ```addTopologyEventCallBack``` in TopologyData to be able to register callback to the TopologyHandler without having to manually create and manipulate this handler class.

```addTopologyEventCallBack``` redirect the registration to ```TopologyHandler->addCallBack```

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-10-04 09:29 UTC, epernod commented
[ci-build][with-all-tests]

2021-10-06 07:44 UTC, alxbilger requested changes
Only a minor typo

2021-10-06 07:44 UTC, alxbilger commented on SofaKernel/modules/SofaBaseTopology/src/SofaBaseTopology/TopologyData.inl
> +        msg_warning(this->getOwner()) << "No TopologyHandler has been creating to manage this TopologyData: " << this->getName()
```suggestion
        msg_warning(this->getOwner()) << "No TopologyHandler has been created to manage this TopologyData: " << this->getName() 
```

2021-10-08 13:36 UTC, fredroy commented
> 
> 
> unique ptr ?


lifetime of m_topologyHandler is planned to handled in a future PR, therefore ... ready

2021-10-08 13:38 UTC, merged