[SofaSimpleFem] Add callback on VonMises in TetrahedronFEMForceField
sofa-framework/sofa pull request #2407
Opened 2021-10-12 14:18 UTC by hugtalbot

Now callback handles the check for the draw vonMises value.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-10-14 18:45 UTC, epernod commented on SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.inl
> +            _computeVonMisesStress.setValue(0);
sure about this one? 
Your are changing _computeVonMisesStress inside the callback of _computeVonMisesStress. It might do a second turn and pass inside the first condition, no?

2021-10-20 09:50 UTC, guparan commented on SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.inl
> +            _computeVonMisesStress.setValue(0);
To be removed. Return ComponentState::Invalid instead.
See the suggestion in my review.

2021-10-20 09:54 UTC, guparan commented on SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.inl
> +    if (drawHeterogeneousTetra.getValue())
Useless computation if drawVonMisesStress is disabled.

2021-10-20 10:03 UTC, guparan requested changes

2021-10-20 10:03 UTC, guparan commented on SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.inl
> +    }, {});
```suggestion
    this->addUpdateCallback("updateComputeVonMisesStress", {&_computeVonMisesStress}, [this](const core::DataTracker& )
    {
        if( _computeVonMisesStress.getValue() != 0 && _computeVonMisesStress.getValue() != 1 && _computeVonMisesStress.getValue() != 2 )
        {
            msg_warning() << "Value of " << _computeVonMisesStress.getName() << " is invalid (must be 0, 1 or 2). "
                          << "Disabling " << _showVonMisesStressPerNode.getName() << " and " << _showVonMisesStressPerElement.getName() << ".";
            _showVonMisesStressPerNode.setValue(false);
            _showVonMisesStressPerElement.setValue(false);
            return sofa::core::objectmodel::ComponentState::Invalid;
        }        
        if ( _computeVonMisesStress.getValue() == 1 && method == SMALL )
        {
            msg_warning() << "VonMisesStress can only be computed with full Green strain when the method is SMALL.";
            return sofa::core::objectmodel::ComponentState::Invalid;
        }

        return sofa::core::objectmodel::ComponentState::Valid;
    }, {});
```

2021-10-20 10:07 UTC, guparan commented on SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.inl
> +    }, {});
Not even sure it's a good idea to do `_showVonMisesStressPerNode.setValue(false);` and `_showVonMisesStressPerElement.setValue(false);` in the callback.
In my opinion we should always avoid to call `setValue` in update callbacks.

2021-10-22 09:39 UTC, guparan commented on SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.inl
> +                msg_info() << "Correct update of " << _computeVonMisesStress.getName();
Still looks weird to me. Why printing a message in ALL cases?
An empty output should mean "nothing wrong happened".

2021-12-07 15:40 UTC, guparan commented on SofaKernel/modules/SofaSimpleFem/src/SofaSimpleFem/TetrahedronFEMForceField.inl
> +                msg_info() << "Correct update of " << _computeVonMisesStress.getName();
Indeed, I forgot the `printLog` trick.
For the record: https://www.sofa-framework.org/community/doc/programming-with-sofa/api-overview/message-api/#macros-and-typical-use

2021-12-07 15:46 UTC, merged