[SofaSparseSolver] Clean examples scenes of sparse linear solvers
sofa-framework/sofa pull request #2422
Opened 2021-10-15 10:24 UTC by alxbilger

- Remove some scenes in the module as their equivalent are in examples\Components\linearsolver
- Add example for PrecomputedLinearSolver
- Add example for SVDLinearSolver
- Minor cleaning
- Speed up an example using multithreading (from 74 fps to 131 fps in 1000 time steps on my computer)

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-10-15 12:52 UTC, alxbilger commented
[ci-build][with-all-tests]

2021-10-21 21:37 UTC, epernod approved these changes

2021-10-21 21:40 UTC, epernod requested changes
Hum sorry in fact FEMBAR-SVDLinearSolver.scn seems to time out: https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/PR-2422/CI_CONFIG=macos_clang,CI_PLUGINS=options,CI_TYPE=release/3/SceneTestCrashes/

https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/PR-2422/CI_CONFIG=macos_clang,CI_PLUGINS=options,CI_TYPE=release/3/artifact/parent_dir/build/scene-tests/archive/examples/Components/linearsolver/FEMBAR-SVDLinearSolver.scn/output.txt

could you double check before merging.

2021-10-21 21:41 UTC, epernod commented
[ci-build][with-all-tests]

2021-10-22 07:05 UTC, alxbilger commented
> Hum sorry in fact FEMBAR-SVDLinearSolver.scn seems to time out: https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/PR-2422/CI_CONFIG=macos_clang,CI_PLUGINS=options,CI_TYPE=release/3/SceneTestCrashes/
> 
> https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/PR-2422/CI_CONFIG=macos_clang,CI_PLUGINS=options,CI_TYPE=release/3/artifact/parent_dir/build/scene-tests/archive/examples/Components/linearsolver/FEMBAR-SVDLinearSolver.scn/output.txt
> 
> could you double check before merging.

@epernod yes it makes sense as this solver is super slow. I'll change the number of iterations for this scene. Thanks

2021-10-22 08:27 UTC, epernod commented
lower your expectations! :)

2021-10-22 09:18 UTC, epernod commented
hum... otherwise we could considering ignoring this scene on the CI.

2021-10-22 09:26 UTC, guparan commented
Still timeout, even with only 1 iteration :disappointed: 
To be disabled ?

2021-10-22 09:29 UTC, alxbilger commented
> Still timeout, even with only 1 iteration 😞 To be disabled ?

@epernod @guparan I check on my computer to be sure that it computes something. If it does, let's ignore it

2021-10-22 09:50 UTC, alxbilger commented
@epernod @guparan It computes the first iteration in 23 seconds on my computer. Let's ignore it

2021-10-22 12:45 UTC, epernod approved these changes

2021-10-22 12:46 UTC, merged