[SofaLoader] Rename MeshObjLoader to MeshOBJLoader
sofa-framework/sofa pull request #2428
Opened 2021-10-18 09:01 UTC by fredroy

All loaders/exporters consider the file format in upper-case EXCEPT MeshObjLoader.
When you have  stuff like MeshVTKLoader, MeshOBJ, OBJExporter, MeshSTLLoader, ImagePNG, etc
it looks not consistent.

So this PR renames all occurrences of MeshObjLoader to MeshOBJLoader and add an alias with `MeshObjLoader` to keep the compatibility with the existing scenes.

Otherwise, all the other upper-case should be converted to Xxx but will be much more bothersome that this PR....

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-10-18 12:35 UTC, alxbilger approved these changes
Of course, I read all the 348 files in details

2021-10-19 11:59 UTC, fredroy commented
[ci-build][with-all-tests]

2021-10-25 14:39 UTC, epernod commented
ObjMeshLoader ? 😆

2021-11-03 09:33 UTC, guparan requested changes

2021-11-03 09:33 UTC, guparan commented on SofaKernel/modules/SofaLoader/CMakeLists.txt
> +    ${SOFALOADER_SRC}/MeshOBJLoader.h
TODO: keep MeshObjLoader.h as a forward header + use DEPRECATED_HEADER macro in it

2021-11-03 09:33 UTC, guparan commented on SofaKernel/modules/SofaLoader/src/SofaLoader/MeshOBJLoader.h
> +class SOFA_SOFALOADER_API MeshOBJLoader : public sofa::core::loader::MeshLoader
TODO: add a class alias MeshObjLoader -> MeshOBJLoader + use ATTRIBUTE_DEPRECATED macro on it

2021-11-03 09:35 UTC, guparan commented on SofaKernel/modules/SofaLoader/CMakeLists.txt
> +    ${SOFALOADER_SRC}/MeshOBJLoader.h
Deprecation period: v21.12 -> v22.12

2021-11-03 09:36 UTC, guparan commented on SofaKernel/modules/SofaLoader/src/SofaLoader/MeshOBJLoader.h
> +class SOFA_SOFALOADER_API MeshOBJLoader : public sofa::core::loader::MeshLoader
Deprecation period: v21.12 -> v22.12

2021-11-04 10:23 UTC, fredroy commented
As expected, it is not possible to do a forward file (MeshObjLoader to MeshOBJLoader) for Windows (and Mac) because of the case insensitivity... 🥺

2021-11-30 15:21 UTC, merged