[TopologyMapping] Fix Tetra2TriangleTopologicalMapping lost ancestor info
sofa-framework/sofa pull request #2460
Opened 2021-11-07 22:03 UTC by epernod

Ancestors and coefficient parameters were lost during EdgeAdded and PointAdded methods coming from Tetrahedron to Triangle mesh.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-11-08 10:17 UTC, fredroy requested changes
TopologyChange's  stuff is now in Sofa.Core

2021-11-08 10:17 UTC, fredroy commented on modules/SofaTopologyMapping/src/SofaTopologyMapping/Tetra2TriangleTopologicalMapping.cpp
> +            const auto* edgeAdded = static_cast<const sofa::component::topology::EdgesAdded*>(*itBegin);
```suggestion
            const auto* edgeAdded = static_cast<const sofa::core::topology::EdgesAdded*>(*itBegin);
```

2021-11-08 10:17 UTC, fredroy commented on modules/SofaTopologyMapping/src/SofaTopologyMapping/Tetra2TriangleTopologicalMapping.cpp
> +            const auto* pointAdded = static_cast<const sofa::component::topology::PointsAdded*>(*itBegin);
```suggestion
            const auto* pointAdded = static_cast<const sofa::core::topology::PointsAdded*>(*itBegin);
```

2021-11-09 09:20 UTC, epernod commented on modules/SofaTopologyMapping/src/SofaTopologyMapping/Tetra2TriangleTopologicalMapping.cpp
> +            const auto* edgeAdded = static_cast<const sofa::component::topology::EdgesAdded*>(*itBegin);
Indeed!

2021-11-19 11:08 UTC, fredroy commented
[ci-build][with-all-tests]

2021-11-19 15:18 UTC, merged