[SofaExporter] Rename OBJExporter
sofa-framework/sofa pull request #2505
Opened 2021-11-25 15:09 UTC by hugtalbot

Rename OBJExporter into VisualModelOBJExporter to express more clearly that it only exports the VisualModels
Compatibility layer added + Alias.

Q: does it make sense to keep examples in the module itself?

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-11-30 18:12 UTC, guparan commented
I cleaned the VisualModelOBJExporter alias, using the SOFA_DEPRECATED_ATTRIBUTE macro.
Doing that, I also updated the status of SOFAEXPORTER_NAMESPACE deprecation (from deprecated to disabled).

2021-11-30 22:33 UTC, guparan requested changes

2021-11-30 22:33 UTC, guparan commented on SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/ExportVisualModelOBJVisitor.h
> +using ExportOBJVisitor [[deprecated("The ExportOBJVisitor is now deprecated, please use ExportVisualModelOBJVisitor instead. Compatibility stops at v22.06")]] = ExportVisualModelOBJVisitor;
TODO: use SOFA_ATTRIBUTE_DEPRECATED macro here too.

2021-12-01 10:30 UTC, guparan commented
[ci-build][with-all-tests]

2021-12-03 17:02 UTC, guparan requested changes
TODO: add backward compat headers to forward `#include <SofaExporter/OBJExporter.h>` and `#include <SofaSimulationCore/ExportOBJVisitor.h>`

2021-12-10 08:18 UTC, fredroy requested changes

2021-12-10 08:18 UTC, fredroy commented on SofaKernel/modules/Sofa.Compat/src/SofaSimulationCore/OBJExporter.h
> +
```suggestion
SOFA_DEPRECATED_HEADER("v21.12", "v22.06", "SofaSimulationCore/OBJExporter.h")
```

2021-12-10 08:36 UTC, guparan requested changes

2021-12-10 08:36 UTC, guparan commented on modules/SofaExporter/src/SofaExporter/VisualModelOBJExporter.h
>  } // namespace misc
To be moved to `Sofa.Compat/src/SofaSimulationCore/OBJExporter.h`

2021-12-10 08:36 UTC, guparan commented on modules/SofaExporter/src/SofaExporter/VisualModelOBJExporter.h
> +        = _visualmodelobjexporter_::VisualModelOBJExporter;
To be moved to `Sofa.Compat/src/SofaSimulationCore/OBJExporter.h`

2021-12-10 09:18 UTC, guparan commented
I removed the [ci-depends] as this PR must provide a compat layer (already done actually) not to break SofaPython3.

2021-12-10 09:22 UTC, guparan commented
[ci-build][with-all-tests]

2021-12-13 15:43 UTC, guparan approved these changes

2021-12-13 15:43 UTC, merged