[SofaMiscForcefield] Small optimization in addMdx in MeshMatrixMass
sofa-framework/sofa pull request #2516
Opened 2021-11-30 15:10 UTC by fredroy

getEdge() from EdgeSetTopologyContainer does bound-checking and the compiler cannot really optimize that.
EDIT: and moreover, getNbEdges() (edges, etc) used in the getEdge is extremely non-optimized...

In a nutsheel, it is much faster to do
```
const auto& edges = topo.getEdges();
for(const auto& e : edges) 
{ 
    blabla(e);
}
```
than
```
for(auto i = 0; i < topo.getNbEdges() ; i++) 
{ 
    blabla(topo.getEdge(i));
}
```

Some idea to keep the getEdge() (and others) would be either to remove the bound-check (maybe enable only in debug like std::vector), or do an unsafe version.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-11-30 15:20 UTC, alxbilger approved these changes

2021-11-30 17:31 UTC, fredroy commented
[ci-build][with-all-tests]

2021-12-01 08:57 UTC, epernod requested changes

2021-12-01 08:57 UTC, epernod commented on modules/SofaMiscForceField/src/SofaMiscForceField/MeshMatrixMass.inl
>              massTotal += 2*edgeMass[j] * Real(factor);
```suggestion
            res[e[0]] += dx[e[1]] * tempMass;
            res[e[1]] += dx[e[0]] * tempMass;

            massTotal += 2 * tempMass;
```

2021-12-01 17:08 UTC, epernod approved these changes

2021-12-01 17:09 UTC, merged