Add checks warnings response 202111
sofa-framework/sofa pull request #2523
Opened 2021-12-01 22:21 UTC by hugtalbot

Based on #2522  this PR adds a sceneCheck to guide users when using collision responses.
For some, a specific animation loop / constraint solver is needed. This is added in the SceneCheckContactResponse !

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-12-02 08:15 UTC, alxbilger commented
I recommend to review this PR with this comparison link: https://github.com/hugtalbot/sofa/compare/change_collision_response_names_202111...add_checks_warnings_response_202111
since it is polluted by https://github.com/sofa-framework/sofa/pull/2522

2021-12-02 08:46 UTC, alxbilger requested changes
I just find it weird that a `SceneChecker` is required for this. I would have imagined this check in the contact manager or directly in the contact response.
A scene checker is independent from the contact manager. If the behavior of a contact changes (e.g. a new constraint solver becomes compatible with StickContactConstraint), the scene checker must be updated. And this is a problem if the developer is not aware of this scene checker or if the new constraint solver is in a plugin.
In any case, adding those warnings are a very good initiative!

2021-12-02 08:46 UTC, alxbilger commented on modules/SofaGraphComponent/src/SofaGraphComponent/SceneCheckCollisionResponse.cpp
> +    return "Check there is not duplicated name in the scenegraph";
This is a copy/paste. Please adapt the description

2021-12-02 08:46 UTC, alxbilger commented on modules/SofaGraphComponent/src/SofaGraphComponent/SceneCheckCollisionResponse.cpp
> +            std::string response = contactManager[0]->response.getValue().getSelectedItem();
```suggestion
            const std::string response = contactManager[0]->response.getValue().getSelectedItem();
```

2021-12-02 08:46 UTC, alxbilger commented on modules/SofaGraphComponent/src/SofaGraphComponent/SceneCheckCollisionResponse.cpp
> +                }
What if there is an animation loop inheriting from `FreeMotionAnimationLoop`? Maybe you could use a `dynamic_cast` or `BaseClass::hasParent`.

2021-12-02 08:46 UTC, alxbilger commented on modules/SofaGraphComponent/src/SofaGraphComponent/SceneCheckCollisionResponse.cpp
> +                }
The comment is also valid for your other searches

2021-12-02 08:46 UTC, alxbilger commented on modules/SofaGraphComponent/src/SofaGraphComponent/SceneCheckCollisionResponse.cpp
> +                        m_message <<"A GenericConstraintSolver must be in the scene to solve StickContactConstraint" << msgendl;
Indentation

2021-12-02 08:46 UTC, alxbilger commented on modules/SofaGraphComponent/src/SofaGraphComponent/SceneCheckCollisionResponse.cpp
> +        m_checkDone=true;
```suggestion
    m_checkDone=true;
    const Size nbContactManager = contactManager.size();
    if( nbContactManager  > 0 )
    {
```
`m_checkDone` is set to `true` in any case

2021-12-03 21:00 UTC, alxbilger commented on modules/SofaGraphComponent/src/SofaGraphComponent/SceneCheckCollisionResponse.cpp
> +                }
I understand. Maybe (in a future PR) we can think about adding a SceneChecker from any module/plugin. If we were able to do that, we could put the scene checker in SofaConstraint

2021-12-14 08:03 UTC, alxbilger approved these changes

2021-12-14 08:51 UTC, guparan commented
@hugtalbot Please put a suitable title for v21.12 changelog

2021-12-14 17:23 UTC, merged