[Plugins] Move Newmat matters into the new SofaNewmat plugin
sofa-framework/sofa pull request #2532
Opened 2021-12-09 12:40 UTC by fredroy

Second and last task about https://github.com/sofa-framework/sofa/issues/2483

Contains #2531

Create a new plugin SofaNewmat with 
 - newmat lib itself
 - NewmatMatrix and NewmatVector (and their tests)
 - LULinearSolver (only compatible with NewmatMatrix)
Add a  "compatibility" layer (tricky because SofaNewmat is optional
Update ComponentChange
Remove newmat usage in image plugin.

Fix  #2483 
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-12-09 19:23 UTC, fredroy commented
[ci-build][with-all-tests]

2021-12-10 08:10 UTC, fredroy commented
[ci-build][force-full-build][with-all-tests]

2021-12-10 09:12 UTC, guparan requested changes

2021-12-10 09:12 UTC, guparan commented on modules/SofaDenseSolver/CMakeLists.txt
> +# endif()
If empty then remove

2021-12-10 09:12 UTC, guparan commented on modules/SofaMiscFem/CMakeLists.txt
> +	${SOFAMISCFEM_SRC}/QuadBendingFEMForceField.inl
```suggestion
    ${SOFAMISCFEM_SRC}/QuadBendingFEMForceField.h
    ${SOFAMISCFEM_SRC}/QuadBendingFEMForceField.inl
```

2021-12-10 09:12 UTC, guparan commented on modules/SofaMiscFem/CMakeLists.txt
> +	${SOFAMISCFEM_SRC}/QuadBendingFEMForceField.cpp
```suggestion
    ${SOFAMISCFEM_SRC}/QuadBendingFEMForceField.cpp
```

2021-12-10 09:12 UTC, guparan commented on applications/plugins/SofaNewmat/CMakeLists.txt
> +    enable_testing()
```suggestion

```

2021-12-10 09:12 UTC, guparan commented on applications/plugins/SofaNewmat/SofaNewmat_test/CMakeLists.txt
> +add_test(NAME ${PROJECT_NAME} COMMAND ${PROJECT_NAME})
```suggestion
```

2021-12-10 12:19 UTC, fredroy commented
[ci-build][force-full-build][with-all-tests]

2021-12-14 09:30 UTC, guparan commented
[ci-build]

2021-12-14 10:09 UTC, merged