[SofaKernel] More generic DefaultVisualManagerLoop
sofa-framework/sofa pull request #2549
Opened 2021-12-17 11:34 UTC by damienmarchal

Currently:
  - there must be a single VisualLoop in the scene
  - this single one must be at the root of the scene. 
  - there is no way to specify or change what is the rendered node
   
This PR allows to:
 - have multiple (possibly different) visual loop in the scene (by updating simulation::draw()). 
 - let user select which node to render (by using a SingleLink instead of a c++ attribute to store the node).
 
 This is useful as it allows to increase the separation of the different "concerns" of an object. 
 
 Exemple of scene that becomes possible:
 ```xml
    <Node name="modelling">
         <Node name="Tripod">

         </Node>
    </Node>
    
    <Node name="Simulation">
    </Node>

    <Node name="Rendering">
          <DefaultVisualManagerLoop targetNode="@/modelling/Tripod"/>
    </Node>    
 ```

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2021-12-17 12:21 UTC, alxbilger approved these changes

2022-01-05 10:17 UTC, guparan requested changes

2022-01-05 10:17 UTC, guparan commented on SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/DefaultVisualManagerLoop.h
> +    SingleLink< DefaultVisualManagerLoop, simulation::Node, BaseLink::FLAG_STOREPATH> l_node;
Please add a Doxygen comment `//< blablabla`

2022-01-05 10:17 UTC, guparan commented on SofaKernel/modules/SofaSimulationCore/src/sofa/simulation/DefaultVisualManagerLoop.cpp
> +    , l_node(initLink("targetNode","Link to the topology relevant for this object"))
Link to the topology?

2022-01-05 15:27 UTC, guparan approved these changes

2022-01-06 13:24 UTC, guparan commented
Didn't see the Windows compilation issue yesterday. Can you look at it @damienmarchal ?

2022-01-12 09:06 UTC, damienmarchal commented
It is an include problem that need to be fixed. I will look at it.

2022-01-13 16:03 UTC, damienmarchal commented
[ci-build]

2022-01-18 22:42 UTC, damienmarchal commented
[ci-build][with-scene-tests][with-regression-tests]

2022-02-16 11:33 UTC, merged