[SofaCUDA] Clean and factorize CudaTriangularFEMForceFieldOptim
sofa-framework/sofa pull request #2568
Opened 2021-12-31 17:34 UTC by epernod

- clean cuda classes and .cu code
- add cudaVec3d support using kernel template
- Add benchmark scene cpu vs gpu and performance scenes

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-01-02 09:36 UTC, fredroy commented
[ci-build][with-all-tests]

2022-01-03 15:18 UTC, alxbilger requested changes
I only request to constify what can be constify.

2022-01-03 15:18 UTC, alxbilger commented on applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTriangularFEMForceFieldOptim.cu
> +    CudaVec3 a  = x[t.ia];
I understand you did not touch this code, but if you have the time, you can constify some of the variables.

2022-01-10 13:16 UTC, alxbilger approved these changes

2022-01-14 09:24 UTC, merged