Minor improvements
sofa-framework/sofa pull request #2667
Opened 2022-02-04 16:26 UTC by hugtalbot

Simple fixes and improvements while wandering in SOFA

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-02-04 17:16 UTC, alxbilger requested changes

2022-02-04 17:16 UTC, alxbilger commented on modules/SofaConstraint/src/SofaConstraint/BilateralInteractionConstraint.cpp
> +            msg_warning("BilateralInteractionConstraintSpecialization: keepOrientationDifference is activated, rest_vector will be ignored!") ;
are you sure about this one? It's not the same thing

2022-02-07 13:16 UTC, alxbilger approved these changes

2022-02-08 08:45 UTC, fredroy approved these changes

2022-02-08 08:45 UTC, merged