FIX missing matrix update (#2704)
sofa-framework/sofa pull request #2706
Opened 2022-02-18 11:32 UTC by TheGreatLudini

In TriangularFEMForceField, the strainDisplacementMatrix was not re-computed for a new simulation step in the computeForce-method. Because of that, the strain computation used an old version of the strainDisplacementMatrix

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-02-21 13:21 UTC, alxbilger requested changes
`triangleInf[elementIndex].strainDisplacementMatrix` is computed at init in `TriangularFEMForceField::initLarge` and `TriangularFEMForceField::initSmall`. An hypothesis is that it is an optimization based on the fact it does not change from a time step to another. Are there any case where it is the case? Small method?

I see a similar code in `computeStress`, where the use of the pre-computed strain displacement is in `(method == SMALL)`, in opposite to the `computeForce` method, where it is in the corotational method. I guess those two functions must be consistent. It is my requested change.

2022-03-02 11:57 UTC, Camille-K commented
Hello,

I just had a look in the code and the associated paper ([link](https://hal.inria.fr/file/index/docid/394480/filename/NPF05.pdf)).

@alxbilger, there are two `computeStress` methods in TriangularFEMForceField, with the following signatures :
```
void computeStress(type::Vec<3,Real> &stress, Index elementIndex);
```
and
```
void computeStress(type::Vec<3,Real> &stress, const MaterialStiffness &K, const type::Vec<3,Real> &strain);
```
Only the first one seems to use the same pattern as in `computeForce` (with the call to `computeStrainDisplacement` conditioned by `_anisotropicMaterial`), in case of small deformation, which is - as you pointed out - incoherent with what is in `computeForce`.
However this `computeStress` method with this signature is apparently used only in 
```
void computeStressAlongDirection(Real &stress_along_dir, Index elementIndex, const Coord &direction);
```
which itself is used only in both `computeStressAcrossDirection` methods, and (finally) these are apparently not called anywhere.
So, _bottomline_: even though the code in `computeStress` is incoherent with the code in `computeForce`, it's actually not used and - I guess - should be cleaned rather than made coherent.

Regarding the initial issue, what I understand from the paper is that the strain-displacement matrix **should be updated at each time step** in case of large deformations. It seems to be clearly stated in the introduction, and demonstrated later in the text (section 2.3). I have a doubt if this is necessary in case of small displacement (for me the paper focuses on large deformation), but even in this case, the current implementation is not coherent (the update should be made in case of large displacement and could be saved in case of small displacement).
I think it's worth to highlight that it was actually the case initially, but it seems to have been changed in this [commit](https://github.com/sofa-framework/sofa/commit/b7d68ef394f703957e7a00037f88d7abeed82d24).

2022-03-02 15:03 UTC, alxbilger commented
I confirm `computeStressAcrossDirection` is dead code.
@epernod do you want to remove this code in your cleaning PR? Or do I make a PR?

2022-03-02 23:27 UTC, epernod commented
Sorry I think  I inverted Small and Large approach in my explanation at the SOFA meeting. 
I checked my wip PRs on TriangularFEMForcefield (#2275) and I have the same fix awaiting: https://github.com/sofa-framework/sofa/pull/2275/files#diff-33034b71c7c012b3d436dd149856f2ea3c991e6ebcb78511599d465128b6f559L1019-R1019
So let's merge this one and I will rebase my PR.

@alxbilger I will remove ```computeStressAcrossDirection ``` (if not already done), in #2287 
@hugtalbot I'm not. Tearing mechanism should be computed outside of the FEM to not add complexity in the code.

2022-03-02 23:27 UTC, epernod approved these changes

2022-03-03 09:53 UTC, merged

2022-03-07 09:04 UTC, TheGreatLudini commented
Hi everyone, sorry for taking so long to further explain my PR. I fully agree with @Camille-K and after looking over some other papers and after further analyzing if the re-computation is necessary, I come to conclusion that the strain-displacement-matrix really has to be updated at each time step.
Thanks for merging my PR.