Correct tensorProduct
sofa-framework/sofa pull request #2787
Opened 2022-03-15 09:43 UTC by olivier-goury

The current implementation of the tensor product of two vectors seems incorrect since it assumes the resulting square matrix is always symmetric.
This is not true in general, for example: 
tensorProduct([0 1],[1 2]) = [0 1]'*[1 2] 
= [[0,0]
    [1 2]]

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-03-15 09:58 UTC, fredroy commented
Would it be possible to write a unit test to show this ? thanks ! 👍
(there are already some in Sofa.Type_test/MatTypes_test.cpp so it would be easy to add tensorproduct tests here)

2022-03-15 10:03 UTC, alxbilger requested changes
Let's use this PR as an opportunity to improve this function:

I suggest to not initialize the matrix at construction:
```cpp
typedef MatNoInit<L,L,Real> Mat;
```

and take the vec parameters by const reference:

```cpp
template<sofa::Size L,class Real>
constexpr Mat<L,L,Real> tensorProduct(const Vec<L,Real>& a, const Vec<L,Real>& b ) noexcept
```
(the character '&' was missing)

2022-03-15 10:19 UTC, olivier-goury commented
Thanks for the feedback

2022-03-16 08:36 UTC, olivier-goury commented
I did the changes as requested. Let me know if that's OK!

2022-03-16 08:41 UTC, alxbilger approved these changes

2022-03-16 08:53 UTC, epernod commented
[ci-build][with-all-tests]

2022-03-16 08:53 UTC, epernod approved these changes

2022-03-17 17:00 UTC, fredroy approved these changes

2022-03-22 09:54 UTC, merged