[ArticulatedSystemPlugin] New example
sofa-framework/sofa pull request #2804
Opened 2022-03-22 21:36 UTC by EulalieCoevoet

Adds an example to the plugin ArticulatedSystemPlugin. 

![image](https://user-images.githubusercontent.com/12150715/159580224-bb724ee4-f469-4697-b373-e6e22c0b4a86.png)

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-03-25 08:41 UTC, fredroy commented
I see that this PR is adding ~10MB of data (from the stl files).
I think we should wait for this plugin to be externalized (on an other repo) to merge this example, otherwise the history of this repo will contain those files, and the SOFA repo history is already so cluttered 🤪

2022-03-25 13:08 UTC, EulalieCoevoet commented
I've just cleaned the repo, removed unused mesh files.
It's 1.7MB of stl files now. Is it still too much ? I could also simplified the mesh but, yeah... it won't be as "pretty".

2022-04-13 08:48 UTC, fredroy commented
[ci-build][with-all-tests]

2022-04-20 09:10 UTC, alxbilger requested changes

2022-04-20 09:10 UTC, alxbilger commented on applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/header.py
> +     'SofaGeneralAnimationLoop', 'SofaPython3', 'SofaSparseSolver', 'SofaPreconditioner', 'SuctionCup',
`SuctionCup` cannot be loaded

2022-04-20 09:16 UTC, EulalieCoevoet commented on applications/plugins/ArticulatedSystemPlugin/examples/ArticulatedArm/header.py
> +     'SofaGeneralAnimationLoop', 'SofaPython3', 'SofaSparseSolver', 'SofaPreconditioner', 'SuctionCup',
Oops, forgot to remove that.

2022-04-20 09:19 UTC, guparan commented
Scene test errors "extension (py) not handled" should be fixed now.

2022-04-20 09:46 UTC, EulalieCoevoet commented
Okay I don't know why things appear like that. I think I just merged master into this branch. If someone knows please tell me. 

Anyway, I've cleaned the RequiredPlugin and added some forgotten changes.

2022-04-20 11:48 UTC, alxbilger commented
Still some problem with the scene on the CI, probably because tkinter is not installed.

```
Python exception:   
  ModuleNotFoundError: No module named 'tkinter'
```

tkinter must be removed from the scene OR this scene should be ignored by the CI.

2022-04-20 13:47 UTC, EulalieCoevoet commented
The GUI (which requires tkinter) is optional but really nice I think to interact with the arm. I've just disabled it by default, so if you go for making the CI ignoring a file, it should only be the script `robotGUI.py`.

2022-04-25 07:10 UTC, alxbilger commented
@guparan @hugtalbot the scene has not been ignored despite the file .scene-tests

2022-04-25 08:12 UTC, fredroy commented
I think it is because it is missing the relative path iteself, i.e it should be "ArticulatedArm/robotGUI.py"
I will modify it directly

2022-04-26 09:36 UTC, damienmarchal commented
Ready, so merge.

2022-04-26 09:36 UTC, merged