[SofaNG] Re-organize tests
sofa-framework/sofa pull request #2873
Opened 2022-04-14 14:13 UTC by fredroy

Based on #2813 

and sofang-ize paths/plugins/etc.
and creation of some *Testing framework (solidmechanics, topology, mapping...)

and a loooots of clean as well. (not enough)

Some tests were disabled, they are back again

Will be updated when Collision/engine/etc will be merged.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-04-15 16:16 UTC, fredroy commented
[ci-build][with-all-tests]

2022-04-25 07:04 UTC, alxbilger requested changes
What a tremendous work!

I have only one comment. And you also have conflicts to solve.

2022-04-25 07:04 UTC, alxbilger commented on Component/IO/Mesh/tests/CMakeLists.txt
> +    # MeshSTLLoader_test.cpp
Why commented?
Either remove the file, or activate it.

2022-04-26 13:32 UTC, guparan requested changes
Correct me if I'm wrong but I think all the Testing packages should be using `sofa_create_package_with_targets` macro and providing a Config.cmake.in file.

2022-04-28 22:53 UTC, fredroy commented
[ci-build][force-full-build][with-all-tests]

2022-05-02 09:34 UTC, fredroy commented
[ci-build][force-full-build][with-all-tests]

2022-05-04 13:13 UTC, merged