[S.C.LinearSolver] Restore specialized functions in SSORPreconditioner
sofa-framework/sofa pull request #2885
Opened 2022-04-19 16:05 UTC by fredroy

#2883 was merged a little bit fast, and some specializations were unfairly commented (well it was ugly in a way)
this PR brings them back in the cpp (where it should have been) and the weird define/undef thingys removed

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-04-19 17:00 UTC, alxbilger requested changes

2022-04-19 17:00 UTC, alxbilger commented on Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/SSORPreconditioner.cpp
> +void SSORPreconditioner<linearalgebra::SparseMatrix<SReal>, linearalgebra::FullVector<SReal> >::solve (Matrix& M, Vector& z, Vector& r)
This specialization is not "used" by any explicit template instantiation.
Either add the template instantiation, or remove the the specialization.
IMO, `SparseMatrix` is not interesting so I would remove it.

2022-04-20 05:14 UTC, fredroy commented on Component/LinearSolver/Preconditioner/src/sofa/component/linearsolver/preconditioner/SSORPreconditioner.cpp
> +void SSORPreconditioner<linearalgebra::SparseMatrix<SReal>, linearalgebra::FullVector<SReal> >::solve (Matrix& M, Vector& z, Vector& r)
Right! I will remove this unused specialized function

2022-04-20 05:59 UTC, fredroy commented
[ci-build][with-all-tests]

2022-04-25 06:48 UTC, alxbilger approved these changes

2022-04-25 06:48 UTC, merged