Fix bb hexafem
sofa-framework/sofa pull request #289
Opened 2017-06-06 11:18 UTC by untereiner

add bounding box to hexaFemForceField

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2017-06-06 13:05 UTC, damienmarchal commented
I like new tests so thanks for your PR.

2017-06-07 11:38 UTC, guparan commented
Rebased and cleaned. `onlyVisible` restored.

2017-06-09 18:49 UTC, damienmarchal commented
[ci-build]

2017-06-12 08:29 UTC, guparan commented
This PR is not ready, it seems to mess with the CI. See all latest failing builds on [windows7_VS-2015_amd64_pr_1_options](https://ci.inria.fr/sofa-ci/job/windows7_VS-2015_amd64_pr_1_options/).

2017-06-14 08:58 UTC, matthieu-nesme requested changes
minor change required

2017-06-14 08:58 UTC, matthieu-nesme commented on SofaKernel/modules/SofaSimpleFem/HexahedronFEMForceField.inl
> +    static const Real min_real = std::numeric_limits<Real>::min();
warning `std::numeric_limits::min()` is not what you want, you want either `-std::numeric_limits::max()` or in c++11 `std::numeric_limits::lowest()`

2017-06-26 11:36 UTC, damienmarchal commented
Hi all,

Is this PR ready ?

2017-06-29 07:52 UTC, untereiner commented
Do you agree @matthieu-nesme ?

2017-06-29 09:44 UTC, matthieu-nesme approved these changes

2017-06-30 12:02 UTC, damienmarchal commented
This PR fullfill our merging rules...so I pass it to ready.

2017-06-30 17:05 UTC, merged