[SofaNG] Setup GUI
sofa-framework/sofa pull request #2895
Opened 2022-04-25 22:02 UTC by fredroy

#1527 

based on:
- #2843  

Desc: todo

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-04-26 07:00 UTC, fredroy commented
[ci-build][force-full-build][with-all-tests]

2022-04-28 07:55 UTC, fredroy commented
[ci-build][force-full-build][with-all-tests]

2022-04-28 22:43 UTC, fredroy commented
[ci-build][force-full-build][with-all-tests]

2022-05-02 09:49 UTC, fredroy commented
[ci-build][force-full-build][with-all-tests]

2022-05-03 15:59 UTC, guparan commented
[ci-build][force-full-build][with-all-tests]

2022-05-09 15:48 UTC, guparan requested changes

2022-05-09 15:48 UTC, guparan commented on GUI/Qt/Sofa.GUI.QtConfig.cmake.in
> +
```suggestion
find_package(Sofa.GUI.Common QUIET REQUIRED)
```

2022-05-09 15:48 UTC, guparan commented on GUI/Batch/Sofa.GUI.BatchConfig.cmake.in
> +endif()
```suggestion
find_package(Sofa.GUI.Common QUIET REQUIRED)
```

2022-05-16 15:23 UTC, merged