[Sofa.Component] Fix compilation when FLOATING_POINT is set to float
sofa-framework/sofa pull request #2907
Opened 2022-04-29 13:03 UTC by fredroy

(without the tests....)

Main problem is the linear solvers using CSPARSE, which only handles double.
Actually, SparseCholesky was using buffers of float with pointers of double (which obviously causes a crash).
SparseLU is more convenient, it tried to use SReal, and make the compilation failing directly.

There were at least two way to solve this problem:
 - disable in the CMakeLists directly (if floating_point is float)
 - do not compile the instance templated on float (effectivement does not compile the two solvers)

I chose the latter to keep them visible in the base code, but I totally agree with the former solution (but requires to access to the Cmake variable SOFA_FLOATING_POINT from Sofa.Config in the CMakefile of S.C.LS.Direct)

An other thing is that preconditionner wants to use SparseCholesky  as well so there is a conditional compilation happening here unfortunately. I dont know if it is possible to just use an other direct solver (probably)

This was needed to test the performance tests for 
 - #2856

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-04-29 13:14 UTC, alxbilger requested changes
Thanks for this unfunny work. Only minor changes requested

2022-04-29 13:14 UTC, alxbilger commented on Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseCholeskySolver.cpp
> +SOFA_PRAGMA_WARNING("SparseCholeskySolver does support float as scalar.")
```suggestion
SOFA_PRAGMA_WARNING("SparseCholeskySolver does not support float as scalar.")
```

2022-04-29 13:14 UTC, alxbilger commented on Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseCholeskySolver.cpp
> +// dont try to compile if floating point is float
```suggestion
```

2022-04-29 13:14 UTC, alxbilger commented on Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLUSolver.cpp
> +SOFA_PRAGMA_WARNING("SparseLUSolver does support float as scalar.")
```suggestion
SOFA_PRAGMA_WARNING("SparseLUSolver does not support float as scalar.")
```

2022-05-02 21:07 UTC, fredroy commented
[ci-build][force-full-build][with-all-tests]

2022-05-03 07:00 UTC, alxbilger approved these changes
- At some point, we will need to ask the question if the [Eigen solvers](https://github.com/alxbilger/EigenLinearSolvers) can replace the ones based on Csparse. If yes, the Eigen solvers are able to deal with `float`.
- PrecomputedLinearSolver uses the Cholesky factorization because it's the most generic solver. Using another is possible but it restricts the use of this solver. (In practice, we all use SparseLDLSolver, so it would not be a problem).

2022-05-05 14:31 UTC, merged