[Sofa.GUI] Clean cmake options/variables/names
sofa-framework/sofa pull request #2974
Opened 2022-05-21 02:30 UTC by fredroy

Clean all cmake var/options/names to follow the new guidelines and the new SOFA-NG module names
(fulfill some TODO written long ago as well)

+ Fix #2972

Remark/question: should we keep compatibility with all the cmake variables/options and preproc defines?

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-05-22 03:58 UTC, fredroy commented
[ci-build][with-all-tests]

2022-05-23 15:04 UTC, alxbilger reviewed
Does the CIs need to be updated with the new variable names?

2022-05-24 02:05 UTC, fredroy commented
> Does the CIs need to be updated with the new variable names?

I think the CI does not really set any GUI/Qt cmake variables.
In any case, as there is no forwarding from the new var to the old deprecated var, it should be yes.

2022-05-31 13:55 UTC, guparan requested changes

2022-05-31 13:55 UTC, guparan commented on Sofa/GUI/CMakeLists.txt
> +if(SOFA_GUI_ENABLE_HEADLESS_RECORDER)
```suggestion
option(SOFA_GUI_ENABLE_HEADLESSRECORDER "Compile the headless recorder (Linux only)" OFF)
if(SOFA_GUI_ENABLE_HEADLESSRECORDER)
```
Looks more consistent to me. May need to be propagated somewhere else...

2022-06-01 03:42 UTC, fredroy commented on Sofa/GUI/CMakeLists.txt
> +if(SOFA_GUI_ENABLE_HEADLESS_RECORDER)
seems not (after grep'ping, it is the only two occurences)

2022-06-01 07:11 UTC, guparan approved these changes

2022-06-01 07:21 UTC, guparan commented
This is breaking, right @fredroy ?

2022-06-01 07:30 UTC, fredroy commented
> This is breaking, right @fredroy ?

Breaking in term of user configuration, yes ; as the cmake option names changed 🫤

2022-06-01 09:11 UTC, guparan commented
And in term of SDK usage

2022-06-01 09:12 UTC, merged