Change the current GUI by default choice
sofa-framework/sofa pull request #2979
Opened 2022-05-24 14:34 UTC by olivier-goury

Currently, when running runSofa without using the -g option for specifying if we want the GUI or batch, SOFA picks the last used one. I would rather like it to be the GUI all the time, and if you want to run in batch, then you would have to specify it explicitly. The current behaviour is annoying when running SOFA in parallel for example with SOFA launcher, because it then saves the batch mode by default.
I am aware my fix is maybe not perfect, I want to start the debate!
Thank you!

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-05-24 15:25 UTC, alxbilger requested changes
You need to make sure `qglviewer` is available in the list of `GUICreator`. Otherwise, another GUI should be picked.

2022-05-24 15:31 UTC, alxbilger commented
Maybe the best approach is to take the GUI with the highest [priority](https://github.com/sofa-framework/sofa/blob/master/Sofa/GUI/Common/src/sofa/gui/common/GUIManager.h#L49).

2022-05-25 01:08 UTC, fredroy commented
> Maybe the best approach is to take the GUI with the highest [priority](https://github.com/sofa-framework/sofa/blob/master/Sofa/GUI/Common/src/sofa/gui/common/GUIManager.h#L49).

I agree with this suggestion.

2022-05-25 07:48 UTC, olivier-goury commented
Thanks for the comments!

2022-05-25 07:57 UTC, alxbilger approved these changes

2022-05-25 13:11 UTC, alxbilger commented
I tried with the imgui GUI in a clean build.
I confirm that `runSofa -l SofaImGui -g imgui` creates a file _lastUsedGUI.ini_, with `imgui` inside.
Then, if I run `runSofa -l SofaImGui`, as expected, it loads the last used gui (found in the file).
However, it does not work with `runSofa` (without the `-l SofaImGui`). Normal, since the plugin is not loaded. It would be the same situation with a double-click on the executable.

2022-05-31 14:01 UTC, guparan commented
> I tried with the imgui GUI in a clean build. I confirm that `runSofa -l SofaImGui -g imgui` creates a file _lastUsedGUI.ini_, with `imgui` inside. Then, if I run `runSofa -l SofaImGui`, as expected, it loads the last used gui (found in the file). However, it does not work with `runSofa` (without the `-l SofaImGui`). Normal, since the plugin is not loaded. It would be the same situation with a double-click on the executable.

But do you think this is a bad or good behavior?
In my opinion it's good. The only issue is with batch GUI, hence @hugtalbot's idea to never put "batch" in lastUsedGUI.ini but keep the mechanism for all other GUIs.

2022-06-14 21:20 UTC, alxbilger commented
I made the changes so that GUIs can decide if they are saved as the last used GUI or not. What do you think?

2022-06-15 09:21 UTC, guparan requested changes

2022-06-15 09:21 UTC, guparan commented on Sofa/GUI/Batch/src/sofa/gui/batch/BatchGUI.h
> +    bool saveAsDefaultGUI() const override { return false; }
```suggestion
    bool canBeDefaultGUI() const override { return false; }
```

2022-06-15 09:21 UTC, guparan commented on Sofa/GUI/Common/src/sofa/gui/common/BaseGUI.h
> +    virtual bool saveAsDefaultGUI() const { return true; }
```suggestion
    virtual bool canBeDefaultGUI() const { return true; }
```

2022-06-15 09:21 UTC, guparan commented on Sofa/GUI/Common/src/sofa/gui/common/GUIManager.cpp
> +        if (currentGUI->saveAsDefaultGUI())
```suggestion
        if (currentGUI->canBeDefaultGUI())
```

2022-06-15 11:58 UTC, damienmarchal commented
@guparan can you remove your request for change if it is not needed anymore plz.

2022-06-17 09:36 UTC, merged