[Components] remove shadow variable
sofa-framework/sofa pull request #2987
Opened 2022-05-27 08:28 UTC by maddin200

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-05-30 07:19 UTC, alxbilger commented
[ci-build][with-all-tests]

2022-06-01 08:52 UTC, epernod approved these changes

2022-06-01 08:54 UTC, epernod requested changes

2022-06-01 08:54 UTC, epernod commented on Sofa/Component/Engine/Transform/src/sofa/component/engine/transform/ROIValueMapper.h
> +                    for (size_t kk=oldSize ; kk <ind+1 ; kk++) outputValues[kk] = defaultValue;
```suggestion
                    for (size_t kk=oldSize ; kk <ind+1 ; kk++) 
                    {
                        outputValues[kk] = defaultValue;
                    }
```

2022-06-08 15:08 UTC, damienmarchal commented
@epernod  is the requested change done in this one ?

2022-06-10 08:18 UTC, alxbilger commented
I made the code more concise, more efficient and clearer to me. It also remove the need of the variable which was initially shadowed. Let me know if you agree/disagree.
I also merged master.
I suggest also to move the methods definitions in the cpp file, but I did not want to be out of the scope of this PR.

2022-06-10 10:08 UTC, maddin200 commented
Hi thanks for help - any update is fine go ahead :-)

2022-06-12 22:07 UTC, epernod approved these changes

2022-06-13 07:08 UTC, merged