[Core.Topology] Remove array quadsInHexahedronArray, QuadsOrientationInHexahedronArray should be used
sofa-framework/sofa pull request #2995
Opened 2022-05-31 16:13 UTC by epernod

quadsInHexahedronArray was not really used. 
QuadsOrientationInHexahedronArray  is the good one.

Quick way to fix #2003

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-05-31 16:14 UTC, epernod commented
[ci-build][with-all-tests]

2022-06-01 05:37 UTC, fredroy requested changes

2022-06-01 05:37 UTC, fredroy commented on Sofa/framework/Core/src/sofa/core/topology/Topology.h
> -SOFA_CORE_API extern const unsigned int quadsInHexahedronArray[6][4];
Instead of directly removing this constant, it should be first declared as a `DeprecatedAndRemoved` to warn the potential user(s).

2022-06-06 02:21 UTC, fredroy requested changes

2022-06-06 02:21 UTC, fredroy commented on Sofa/framework/Core/src/sofa/core/topology/Topology.h
> +SOFA_CORE_API extern const DeprecatedAndRemoved quadsInHexahedronArray;
You may remove the extern keyword, as there is no definition anywhere

2022-06-06 02:21 UTC, fredroy commented on Sofa/framework/Core/src/sofa/core/topology/Topology.h
> +SOFA_CORE_API extern const DeprecatedAndRemoved quadsInHexahedronArray;
```suggestion
const DeprecatedAndRemoved quadsInHexahedronArray;
```

2022-06-07 01:18 UTC, fredroy approved these changes

2022-06-08 20:22 UTC, merged