[SofaCUDA] Add ConstraintCorrection instantiation in CudaVec3f/CudaVec3f1
sofa-framework/sofa pull request #3004
Opened 2022-06-02 09:49 UTC by epernod

Add instantiation in CudaVec3f/CudaVec3f1 for
- LinearSolverConstraintCorrection
- PrecomputedConstraintCorrection
- UncoupledConstraintCorrection

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-06-02 12:54 UTC, alxbilger requested changes
Only minor changes requested.

Does it add any interesting features for Cuda scenes?

2022-06-02 12:54 UTC, alxbilger commented on applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaLinearSolverConstraintCorrection.cpp
> +} // namespace sofa::component::constraintset
```suggestion
} // namespace sofa::component::constraint::lagrangian::correction
```

2022-06-02 12:54 UTC, alxbilger commented on applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaLinearSolverConstraintCorrection.cpp
> +const int CudaLinearSolverConstraintCorrectionClass = core::RegisterObject("Supports GPU-side computations using CUDA.")
In the other files, `RegisterObject` is performed in the `sofa::gpu::cuda` namespace

2022-07-20 01:54 UTC, Changjing-Liu commented
Wow, this SofaCUDA for ConstraintCorrection is exactly what I want! Is there any update here?

2022-07-28 09:06 UTC, epernod commented
> Only minor changes requested.
> 
> Does it add any interesting features for Cuda scenes?

One of the numerous iteration to be able to use FreeMotionAnimationLoop in CUDA to use at least some components with  CUDA implementation

2022-08-11 00:33 UTC, merged