[SofaNG] Dispatch SofaHaptics and SofaValidation
sofa-framework/sofa pull request #3041
Opened 2022-06-14 02:51 UTC by fredroy

https://github.com/sofa-framework/sofa/issues/1527

Deprecates **SofaHaptics** and **SofaValidation** (and a bit of **SofaGeneralObjectInteraction**)

**SofaHaptics** was more or less renamed to Sofa.Component.Haptic
**SofaValidation** only has 2 useful components (CompareState and CompareTopology) which have been moved to S.C.Playback (along the Read and Write ones)
**SofaGeneralObjectInteraction** had an interactiveEllipsoidFF which has been moved to S.C.MechanicalLoad.

The remaining components in the modules/ are now either deprecated (gravity), bogus (monitor&co, collisiongroupmanager) or could be replaced with two components (boxstiffFF)

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-06-14 07:53 UTC, fredroy commented
[ci-build][with-all-tests]

2022-06-22 09:53 UTC, guparan requested changes

2022-06-22 09:53 UTC, guparan commented on Sofa/Component/Playback/CMakeLists.txt
> +sofa_find_package(Sofa.Simulation.Common REQUIRED)
PlaybackConfig.cmake.in must be changed accordingly.

2022-06-22 09:53 UTC, guparan commented on modules/SofaGeneralObjectInteraction/CMakeLists.txt
> +sofa_find_package(Sofa.Component.Engine.Select REQUIRED)
```suggestion
sofa_find_package(Sofa.Component.Engine.Select REQUIRED)
sofa_find_package(Sofa.Component.MechanicalLoad REQUIRED)
```

2022-06-22 09:53 UTC, guparan commented on modules/SofaGeneralObjectInteraction/SofaGeneralObjectInteractionConfig.cmake.in
>  find_package(Sofa.Component.Engine.Select QUIET REQUIRED)
```suggestion
find_package(Sofa.Component.Engine.Select QUIET REQUIRED)
find_package(Sofa.Component.MechanicalLoad QUIET REQUIRED)
```

2022-06-22 09:53 UTC, guparan commented on modules/SofaHaptics/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} PUBLIC Sofa.Component.Haptic)
SofaHapticsConfig.cmake.in to be changed accordingly.

2022-06-22 09:53 UTC, guparan commented on modules/SofaValidation/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} PUBLIC Sofa.Component.Playback)
SofaValidationConfig.cmake.in to be changed accordingly.

2022-06-23 09:11 UTC, guparan commented
[ci-build][with-all-tests][force-full-build]

2022-06-23 09:27 UTC, guparan commented
[ci-build][with-all-tests][force-full-build]

2022-06-23 15:34 UTC, merged