Add spelling suggestion for object and data field using difflib.
sofa-framework/sofa pull request #3042
Opened 2022-06-14 23:32 UTC by damienmarchal

WIP.
Implement spelling replacement in case of un-creatable component or data field's one using difflib.
Example of output:
```console
[ERROR]   [SofaPython3::SceneLoader] Unable to completely load the scene from file 'toto.py'.  
Python exception:  ValueError: Object type MechanicaObject<> was not created  
The object is not in the factory.  
But the following exits:  
                      : MechanicalObject  
                      : MappedObject  
                      : MechanicalStateController  
```

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-11-08 07:40 UTC, damienmarchal commented
[ci-build][with-all-tests]

2022-11-08 12:31 UTC, alxbilger requested changes
Almost good to go.

It worth mentioning that the difflib comes from https://github.com/duckie/difflib.

2022-11-08 12:31 UTC, alxbilger commented on extlibs/CMakeLists.txt
> +# STB (header-only)
```suggestion
```

2022-11-08 12:31 UTC, alxbilger commented on Sofa/framework/Core/src/sofa/core/objectmodel/Base.cpp
> +        std::vector<std::string> possibleNames;
```suggestion
        std::vector<std::string> possibleNames;
        possibleNames.reserve(m_vecData.size() + m_vecLink.size());
```

2022-11-08 12:31 UTC, alxbilger commented on Sofa/framework/Core/src/sofa/core/ObjectFactory.cpp
> +            arg->logError("The object '"+classname+"' is not in the factory.");
```suggestion
            arg->logError("The object '" + classname + "' is not in the factory.");
```

2022-11-08 12:31 UTC, alxbilger commented on Sofa/framework/Core/src/sofa/core/ObjectFactory.cpp
> +                std::vector<std::string> possibleNames;
```suggestion
                std::vector<std::string> possibleNames;
                possibleNames.reserve(registry.size());
```

2022-11-08 22:22 UTC, damienmarchal commented on extlibs/difflib/difflib.h
> +
```suggestion
/// Original source: https://github.com/duckie/difflib.
```

2022-11-09 08:40 UTC, alxbilger approved these changes

2022-11-09 08:43 UTC, alxbilger commented
@damienmarchal Is the work finished on this PR?

2022-11-09 09:01 UTC, damienmarchal commented
@alxbilger  yes, I have not more time to improve it. 

There is still work to do in order to generalize the usage of that everywhere we are doing "name" search, but this is future work.

2022-11-09 09:55 UTC, damienmarchal commented
Ready... so merge.

2022-11-09 09:56 UTC, merged