Searching for Direct Linear Solver in LinearSolverConstraintCorrection
sofa-framework/sofa pull request #3055
Opened 2022-06-17 15:36 UTC by ScheiklP

@hugtalbot 
Copied search for correct Direct Linear Solver from GenericConstraintCorrection.

As mentioned in https://github.com/sofa-framework/sofa/discussions/3046 the object did not check the correct type of the solver during init.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-06-22 12:29 UTC, alxbilger requested changes

2022-06-22 12:29 UTC, alxbilger commented on Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.inl
> +            if (s->getTemplateName() == "GraphScattered")
```suggestion
            if (s->getTemplateName() == sofa::component::linearsolver::GraphScatteredMatrix::Name())
```

2022-06-22 12:29 UTC, alxbilger commented on Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.inl
> +                if (s->getTemplateName() == "GraphScattered")
```suggestion
                if (s->getTemplateName() == sofa::component::linearsolver::GraphScatteredMatrix::Name())
```

2022-06-22 12:29 UTC, alxbilger commented on Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.inl
> +                msg_warning() << "Can not use the solver " << s->getName() << " because it is templated on GraphScatteredType";
I would like to know more about the reason GraphScattered types are not compatible with LinearSolverConstraintCorrection please.

2022-06-28 13:09 UTC, ScheiklP commented on Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.inl
> +                msg_warning() << "Can not use the solver " << s->getName() << " because it is templated on GraphScatteredType";
I am actually not sure. I just got that from the documentation, @hugtalbot, and `GenericConstraintCorrection`

2022-06-29 12:25 UTC, ScheiklP commented
Did the changes build for you @alxbilger ?
Getting the name does not seem to work for the CI:
```
3055/fedora_clang_options_release/src/Sofa/Component/Constraint/Lagrangian/Correction/src/sofa/component/constraint/lagrangian/correction/LinearSolverConstraintCorrection.inl:97:76: error: no member named 'GraphScatteredMatrix' in 'sofa::core::behavior::LinearSolver'
                if (s->getTemplateName() == sofa::component::linearsolver::GraphScatteredMatrix::Name())
```

2022-06-29 12:38 UTC, alxbilger commented
@ScheiklP yes it is because of a missing include. I made the change

2022-07-15 01:04 UTC, fredroy commented
[ci-build][with-all-tests]

2022-07-18 05:03 UTC, merged