[scenes] Remove all uses of DefaultCollisionGroupManager
sofa-framework/sofa pull request #3104
Opened 2022-07-06 07:59 UTC by hugtalbot

Simply remove all lines in scenes (scn) including a DefaultCollisionGroupManager

`$ find . -type f -name "*.scn" -exec sed -i '/DefaultCollisionGroupManager/d' {} +`

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-07-06 08:13 UTC, alxbilger requested changes
Some places where it must not be removed

2022-07-06 08:13 UTC, alxbilger commented on modules/SofaMiscCollision/SofaMiscCollision_test/scenes/DefaultCollisionGroupManager_singleObject_test.scn
> -    <DefaultCollisionGroupManager name="GroupManager"/>
Probably not here

2022-07-06 08:13 UTC, alxbilger commented on examples/Benchmark/Performance/CollisionGroupManager/1system_without_CollisionGroupManager.scn
> -the DefaultCollisionGroupManager component.
Not in this file

2022-07-06 08:13 UTC, alxbilger commented on examples/Benchmark/Performance/CollisionGroupManager/2systems_with_CollisionGroupManager.scn
> -the DefaultCollisionGroupManager component.
Not here

2022-07-06 08:13 UTC, alxbilger commented on examples/Benchmark/Performance/CollisionGroupManager/2systems_with_CollisionGroupManager.scn
> -There is a DefaultCollisionGroupManager component in this scene.
Not here

2022-07-06 08:13 UTC, alxbilger commented on examples/Benchmark/Performance/CollisionGroupManager/2systems_without_CollisionGroupManager.scn
> -the DefaultCollisionGroupManager component.
Not here

2022-07-06 08:13 UTC, alxbilger commented on examples/Benchmark/Performance/CollisionGroupManager/2systems_without_CollisionGroupManager.scn
> -There is a DefaultCollisionGroupManager component in this scene.
Not here

2022-07-07 01:13 UTC, fredroy commented
[ci-build][with-all-tests]

2022-07-07 02:08 UTC, fredroy commented
@hugtalbot you will need to update the regression file for collisionMultiple.scn, as the DefaultCollisionGroupManager seemed to have an impact in this one

2022-07-20 01:10 UTC, fredroy commented
[ci-build][force-full-build][with-all-tests]

2022-07-20 03:27 UTC, fredroy approved these changes

2022-07-20 03:28 UTC, merged