[GL.Rendering3D] Clean up GL components
sofa-framework/sofa pull request #3115
Opened 2022-07-07 10:21 UTC by alxbilger

- Fix link issues because of missing *_API
- Follow naming guidelines + depreciation of old variables
- OglGrid uses a cached list of vertices
- Use of `saveLastState` and `restoreLastState`

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-07-08 00:34 UTC, fredroy requested changes

2022-07-08 00:34 UTC, fredroy commented on SofaKernel/modules/Sofa.GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglSceneFrame.cpp
>      glPushAttrib( GL_ALL_ATTRIB_BITS);
You can replace it with the saveLastState()

2022-07-08 00:35 UTC, fredroy commented
Other than my little contribution, well done 👌

2022-07-08 07:59 UTC, alxbilger commented on SofaKernel/modules/Sofa.GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglSceneFrame.cpp
>      glPushAttrib( GL_ALL_ATTRIB_BITS);
Sure. I took the opportunity to use draw tools as much as possible, replacing the corresponding OpenGL calls

2022-07-11 08:16 UTC, epernod commented
I see @fredroy you requested changes. I think it is clear now?

2022-07-11 08:27 UTC, epernod commented on SofaKernel/modules/Sofa.GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglGrid.cpp
> +    , d_color(initData(&d_color, sofa::type::RGBAColor(0.34117647058f,0.34117647058f,0.34117647058f,1.0f),  "color", "Color of the lines in the grid. default=(0.34,0.34,0.34,1.0)"))
0.34117647058f I think we are more sharp on line color than on CG convergence!

2022-07-11 08:27 UTC, epernod commented on SofaKernel/modules/Sofa.GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglGrid.cpp
> +            min = sofa::type::Vec3f(-s*0.1f, -s*0.5f, -s*0.5f);
maybe create 2 variables for s*0.1f and s*0.5f , if you think we will change that values some days...

2022-07-11 08:27 UTC, epernod commented on SofaKernel/modules/Sofa.GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglGrid.h
> +    sofa::type::vector<Vector3> m_drawnPoints;
small doxygen doc, even if the name is crystal clear

2022-07-11 08:27 UTC, epernod commented on SofaKernel/modules/Sofa.GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglSceneFrame.cpp
> +        drawCubeCones(vparams);
what is a cube cone? pyramid?

2022-07-11 08:28 UTC, epernod commented on SofaKernel/modules/Sofa.GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglSceneFrame.cpp
> +        drawCubeCones(vparams);
If I understood well, you are updating/changing some rendering, maybe a small screenshot just for the record.

2022-07-11 08:28 UTC, epernod commented
[ci-build][with-all-tests]

2022-07-11 10:45 UTC, alxbilger commented on SofaKernel/modules/Sofa.GL/Component/Rendering3D/src/sofa/gl/component/rendering3d/OglSceneFrame.cpp
> +        drawCubeCones(vparams);
Note that CubeCones already existed before (but I was the author).
I attached a video capture to visualize what CubeCones is.

https://user-images.githubusercontent.com/10572752/178247590-c43c3c32-b626-46a2-bdcf-f8aa817090c3.mp4

The rendering should be the same. Only the way to call it changes.

2022-07-12 01:11 UTC, fredroy approved these changes

2022-07-12 09:27 UTC, damienmarchal commented
Hi all, 

Thanks for the PR. 

In the past it was consider that draw tools was a rendering abstraction layer to be used for debugging/inspection or GUI helpers. The recommendation was to use drawTools in the Base::visual() overrides. The main ideas was to allow component developpers to have rendering tools without having a dependency to opengl. On its side, OglXXX component in Sofa.GL exists to hold compoennts that, for whatever reason (performance, lack of time), are still implemented using the opengl api.

Up to now, the evolution guidelines was something like:
- replace in the complete code base ogl call by drawTools calls into xxx::draw() 
- move every component for which ogl call remains (mostly in xxxx:drawVisual) into the Sofa.GL.XXX

This PR does something else, as it replace opengl calls from Sofa.GL.OglXXX by drawTools's ones. Implementing component rendering using drawTools instead of ogl calls is probably desirable (if there is no performance cost)... but it cannot be in Sofa.GL. 

I recommand to create a new component in Sofa.Component.Visual, for the component using drawTools and if needed in Sofa.GL.Component have the ogl version subclassing it (if needed).

2022-07-12 09:30 UTC, damienmarchal requested changes
Is there performance cost/benefit for this PR ? 
Please consider moving component not using opengl calls into Sofa.Component.Visual.

2022-07-12 12:16 UTC, alxbilger commented
@damienmarchal Thanks for your suggestion. Indeed, some components can now be moved to a generic module not depending on OpenGL 👍 🎊 . But I am confused by your comment. Did you want to suggest other things than just moving the components?

2022-07-14 07:59 UTC, damienmarchal commented
@alxbilger 

In addition to have very component not relying anymore on a dependency to opengl should be moved to a generic module. 
I would suggest having a layer of compatibility/deprecation (possibly build on top of the generic module) to to tell users that scenes like:
```console
   RequiredPlugin("Sofa.GL.Component") 
   OglModel()
   OglGrid() 
```
Are still working but displays nice guidance on how to update to more or less something of that kind:
```console
   RequiredPlugin("Sofa.Components.Visual")                 
   VisualModel()                                                          
   VisualGrid() 
```

2022-07-19 14:53 UTC, alxbilger commented
@damienmarchal Does https://github.com/sofa-framework/sofa/pull/3115/commits/e8bb1deb711c2f512739a1afa373cbaef96bcb59 match your expectations?

2022-07-21 01:47 UTC, merged