[constraint.lagrangian.solver] fixes verbose GenericConstraintSolver
sofa-framework/sofa pull request #3232
Opened 2022-08-22 12:27 UTC by EulalieCoevoet

Fixes the verbosity introduced in #3053. 
These messages should be associated with the solver object, so that they are only printed if `printLog` is set to true.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-08-22 13:44 UTC, alxbilger requested changes
Could you also change the one in line 1145? Thanks

2022-08-24 07:57 UTC, alxbilger approved these changes

2022-08-24 07:57 UTC, merged

2022-08-27 17:24 UTC, alxbilger commented
@sofa-framework/consortium-staff hotfix for 22.06?

2022-08-29 08:31 UTC, damienmarchal commented
Small warning before back porting... 
I got 1à minuets ago a preliminary feedback from @samFabrice that this change is not working as expected. 
He is investigating and will confirm/cancel the warning.

2022-08-30 08:26 UTC, samFabrice commented
I just hadn't updated my workspace. but now that it's done I no longer have these warnings so it's fine