[core] remove shadow variables (modern version)
sofa-framework/sofa pull request #3267
Opened 2022-09-02 09:57 UTC by maddin200

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-09-03 09:51 UTC, maddin200 commented
changed

2022-09-05 07:01 UTC, alxbilger requested changes
Thanks for the pull request. It is indeed important to make the code more readable while taking advantages of modern C++. Here are my suggestions

2022-09-05 07:01 UTC, alxbilger commented on Sofa/framework/Core/src/sofa/core/collision/Intersection.cpp
> +        for (auto classInfoIt = classes.begin(); classInfoIt != classes.end(); ++classInfoIt)
To avoid such long for loop declarations and dealing with useless iterators, there are range-based for loops: https://en.cppreference.com/w/cpp/language/range-for

So I would have written this loop: `for (const auto& classInfo : classes)`

I think it is more readable.

But ultimately, this for loop is just a search for an element in a `std::set`. There is `std::find_if` for that:

```cpp
const auto findIt = std::find_if(classes.begin(), classes.end(),
    [model](const auto* classInfo){ return classInfo->isInstance(model); });
if (findIt != classes.end())
    t2 = (*findIt)->type();
```

2022-09-05 07:01 UTC, alxbilger commented on Sofa/framework/Core/src/sofa/core/collision/Intersection.cpp
> +    for(auto intersectorsMapIt = intersectorsMap.begin(), itEnd = intersectorsMap.end(); intersectorsMapIt != itEnd; ++intersectorsMapIt)
Here, since the container is a `std::map`, you can use structured binding (https://en.cppreference.com/w/cpp/language/structured_binding):

```cpp
for (const auto& [typeInfoPair, intersector] : intersectorsMap)
{
    tmp << "  "
            << gettypename(typeInfoPair.first) << "-"
            << gettypename(typeInfoPair.second);
    tmp << "  " << (intersector ? intersector->name() : "nullptr") << msgendl;
}
```

2022-09-05 11:53 UTC, maddin200 commented
probably I have no time to test it.

2022-11-15 16:38 UTC, closed without merging