[Constraint.Lagrangian] Remove merge option from BilateralInteractionConstraint
sofa-framework/sofa pull request #3328
Opened 2022-09-22 07:47 UTC by epernod

based on PR #3327 

- Remove option `merge` which was added as a test in 2011 and never finished. According to a quick test on example. The behavior is less stable when activating the option with the same speed.

Result of BilateralConstraint between 2 deformable models. 
Current behavior: single constraint working fine
![RemovingBilateralInteractionConstraint_00000001](https://user-images.githubusercontent.com/21199245/191688055-b0f0af8a-a657-4d9f-b477-6d712542a48a.png)

Result when activating merge option: Some vibration and constraint is duplicated
![RemovingBilateralInteractionConstraint_00000002](https://user-images.githubusercontent.com/21199245/191688314-22cd8674-ce2c-40d9-a6c1-f77267cbb471.png)

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-09-23 08:20 UTC, fredroy commented
[ci-build][with-all-tests]

2022-09-30 07:55 UTC, alxbilger requested changes
I recommend to deprecate Data fields properly. See https://www.sofa-framework.org/community/doc/contributing-to-sofa/lifecycle-mechanisms/#removing-a-datafield

2022-09-30 07:55 UTC, alxbilger commented on Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/BilateralInteractionConstraint.inl
> +    , d_activate( initData(&d_activate, true, "activate", "controle constraint activation (true by default)"))
```suggestion
    , d_activate( initData(&d_activate, true, "activate", "control constraint activation (true by default)"))
```

2022-10-07 21:31 UTC, epernod commented
> I recommend to deprecate Data fields properly. See https://www.sofa-framework.org/community/doc/contributing-to-sofa/lifecycle-mechanisms/#removing-a-datafield

I did something to correctly depreciate the Data. The instruction are not 100% clear to me (regarding dates inside the macro and parse method). Let me know if it seems correct.

2022-10-07 21:31 UTC, epernod commented
[ci-build][with-all-tests]

2022-10-12 09:30 UTC, alxbilger requested changes

2022-10-12 09:30 UTC, alxbilger commented on Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/BilateralInteractionConstraint.h
> +        else if (arg->getAttribute("merge"))
```suggestion
        if (arg->getAttribute("merge"))
```

2022-10-12 09:30 UTC, alxbilger commented on Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/BilateralInteractionConstraint.h
> +        else if (arg->getAttribute("derivative"))
```suggestion
        if (arg->getAttribute("derivative"))
```

2022-10-13 00:14 UTC, merged