[SofaPhysicsAPI] Some small cleaning and add access to VisualModel*
sofa-framework/sofa pull request #3519
Opened 2022-12-01 23:40 UTC by epernod

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2022-12-02 09:16 UTC, alxbilger requested changes
The methods you added can be const.

And by curiosity, why are the methods of the SofaPhysicsAPI class not defined in SofaPhysicAPI.cpp?

2022-12-02 09:54 UTC, epernod commented
> And by curiosity, why are the methods of the SofaPhysicsAPI class not defined in SofaPhysicAPI.cpp?

Very good question... I'm not sure, I think it was done so SofaPhysicsAPI can be shipped/share easily? or to look like an interface ?
@fredroy any idea?

2022-12-05 05:23 UTC, fredroy commented
> > And by curiosity, why are the methods of the SofaPhysicsAPI class not defined in SofaPhysicAPI.cpp?
> 
> Very good question... I'm not sure, I think it was done so SofaPhysicsAPI can be shipped/share easily? or to look like an interface ? @fredroy any idea?

At that time, it was to give a public API to any external program using SOFA as a lib (no exposition whatsoever to any SOFA code).
You just needed this .h and the compiled libs.
 
Note that because of the config.h stuff, this is not the case anymore 🙊

2022-12-07 09:16 UTC, fredroy approved these changes

2022-12-07 14:23 UTC, merged