[MechanicalLoad] Fix when no force given
sofa-framework/sofa pull request #3670
Opened 2023-02-21 10:15 UTC by alxbilger

Resize the force vector even when no force Data has been set. This avoids a crash later.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2023-02-21 10:15 UTC, alxbilger commented
[ci-build][with-all-tests]

2023-02-21 17:18 UTC, epernod requested changes

2023-02-21 17:18 UTC, epernod commented on Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/ConstantForceField.inl
> +        computeForceFromSingleForce();
I don't understand, looking quickly at the code you end up in this ```else case```  if, upon other cases, d_force is not set.
But `computeForceFromSingleForce `is using d_force to apply it's value to each force per index. 
You should set d_force value to 0 before calling `computeForceFromSingleForce `no?

2023-02-22 09:51 UTC, alxbilger commented on Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/ConstantForceField.inl
>      , d_force(initData(&d_force, "force", "applied force to all points if forces attribute is not specified"))
To do: add a default value

2023-02-22 12:17 UTC, alxbilger commented
[ci-build][with-all-tests]

2023-02-23 03:31 UTC, merged