[SofaPhysicsAPI] Remove unreachable code
sofa-framework/sofa pull request #3771
Opened 2023-04-06 14:09 UTC by alxbilger

I removed code that was unreachable. I am not sure that it is the intended behavior. I need advices (from @epernod ?).

Fixes https://github.com/sofa-framework/sofa/issues/3739

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2023-04-06 14:15 UTC, alxbilger commented
[ci-build][with-all-tests]

2023-04-06 14:15 UTC, damienmarchal commented
Thanks @alxbilger  for this nice PR :)

2023-04-12 07:50 UTC, epernod requested changes

2023-04-12 07:50 UTC, epernod commented on applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsSimulation.cpp
>          return updateOutputMeshes();
In fact could you keep returning the result of outputMeshes to not break my version:

int result = API_SUCCESS;
if (m_RootNode.get())
{
...
   result = updateOutputMeshes();
} 
else
{
  m_RootNode = m_Simulation->createNewGraph("");
  return API_SCENE_FAILED;
}
...
return result;

2023-04-12 09:06 UTC, alxbilger commented on applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsSimulation.cpp
>          return updateOutputMeshes();
done

2023-04-12 09:06 UTC, alxbilger commented
[ci-build][with-all-tests]

2023-04-14 08:57 UTC, epernod approved these changes

2023-04-14 12:47 UTC, merged