[all] Add DepercatedData and RemovedData
sofa-framework/sofa pull request #3934
Opened 2023-06-09 09:23 UTC by damienmarchal

To make it more simple to manage deprecation and more specifically  to not override the parse() method for that purpose.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2023-06-13 04:51 UTC, fredroy requested changes

2023-06-13 04:51 UTC, fredroy commented on Sofa/framework/Core/src/sofa/core/objectmodel/DeprecatedData.cpp
> +class DeprecatedData
the cpp has the same contents as the .h

2023-06-13 04:51 UTC, fredroy commented on Sofa/framework/Core/src/sofa/core/objectmodel/Base.cpp
> +DeprecatedData::DeprecatedData(Base* b, const std::string& name, const std::string& helptext)
I think those should go into DeprecatedData.cpp

2023-06-16 15:04 UTC, damienmarchal commented
[ci-build][with-tests]

2023-06-19 00:19 UTC, fredroy commented
[ci-build][with-all-tests]

2023-06-19 00:23 UTC, fredroy requested changes
Looks good to me, except some added indentations for the license citation in some files, and for  some comments as well 🤐

2023-06-19 00:23 UTC, fredroy commented on applications/plugins/MultiThreading/src/MultiThreading/component/animationloop/AnimationLoopParallelScheduler.h
> + *                 SOFA, Simulation Open-Framework Architecture                *
Indentation ?

2023-06-19 00:23 UTC, fredroy commented on applications/plugins/MultiThreading/src/MultiThreading/component/animationloop/AnimationLoopParallelScheduler.h
> +            /// Initialization method called at graph creation and modification, during bottom-up traversal.
same, here and there....

2023-06-21 08:38 UTC, alxbilger requested changes

2023-06-21 08:38 UTC, alxbilger commented on Sofa/framework/Core/src/sofa/core/objectmodel/RemovedData.h
> +///    RemovedData d_sofaIsGreatM(this "sofaIsGread", "")
```suggestion
///    RemovedData d_sofaIsGreatM(this, "sofaIsGreat", "")
```

2023-06-21 08:38 UTC, alxbilger commented on Sofa/framework/Core/src/sofa/core/objectmodel/DeprecatedData.h
> +/// add DeprecatedData d_sofaIsGreatM(this "sofaIsGread", "")
```suggestion
/// add DeprecatedData d_sofaIsGreatM(this, "sofaIsGreat", "")
```

2023-06-21 08:38 UTC, fredroy commented
2 tests are considered as failing since the message of RemovedData is thrown as an `Error`

2023-06-27 01:41 UTC, fredroy approved these changes

2023-06-27 01:42 UTC, fredroy commented
[ci-build][with-all-tests]

2023-06-28 00:02 UTC, merged