[Helper] add the experimental filesystem library for gcc-8 compilation
sofa-framework/sofa pull request #3944
Opened 2023-06-12 12:31 UTC by mikelitu

Fixes https://github.com/sofa-framework/sofa/issues/3943

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2023-06-12 15:18 UTC, alxbilger requested changes
Thanks for this pull request.

Note that some of the files will have conflicts with https://github.com/sofa-framework/sofa/pull/3942

2023-06-12 15:18 UTC, alxbilger commented on CMakePresets.json
Is this file part of the pull request?

2023-06-12 15:18 UTC, alxbilger commented on Sofa/framework/Helper/CMakeLists.txt
> +	if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 9.1)
Indentation rule is 4 spaces

2023-06-12 15:18 UTC, alxbilger commented on CHANGELOG.md
I am not sure it is up to the PR developer to edit this file. I think your PR will be automatically added to the changelog in the future release. Right @hugtalbot ?

2023-06-12 15:18 UTC, alxbilger commented on Sofa/Component/IO/Mesh/tests/MeshExporter_test.cpp
> +std::string tempdir = fs::temp_directory_path().string() ;
```suggestion
const std::string tempdir = sofa::helper::system::FileRepository::getTempPath() ;
```

I suggest to use directly this utility function. That would avoid the boilerplate code for the includes. The same apply in the other test files.

2023-06-12 16:11 UTC, mikelitu commented on CMakePresets.json
No, sorry I forgot to remove it from my repository. I was just doing some testing with the CMakePresets.json.

2023-06-12 16:23 UTC, mikelitu reviewed
Thank you very much for your suggestions. I have adddressed them and made the necessary updates on the code.

2023-06-13 07:11 UTC, alxbilger requested changes

2023-06-13 07:11 UTC, alxbilger commented on CMakePresets.json
You should not delete it, just checkout it again, and commit it.

2023-06-13 07:11 UTC, alxbilger commented on Sofa/Component/IO/Mesh/tests/MeshExporter_test.cpp
> +#endif
```suggestion
```

Since you now use `FileRepository::getTempPath()`, you need need the includes

2023-06-13 07:36 UTC, mikelitu commented on CMakePresets.json
Done.

2023-06-16 13:02 UTC, alxbilger commented
[ci-build][with-all-tests]

2023-06-20 10:38 UTC, mikelitu commented
I have corrected the test scripts as they were retrieving and error with the class definition from the previous definition. Now it compiles succesfully and passes all the tests. Sorry for using multiple accounts for commiting, but I had to change PC in the last days and I did not realize that the one I was using already had a linked account.

2023-06-21 10:41 UTC, alxbilger approved these changes

2023-06-21 10:45 UTC, alxbilger commented
The CI is happy with your changes. Let's wait more reviews. It should be merged next week.
(the MacOS build still has issues independent from your changes, but it should be fixed soon)

2023-06-28 08:35 UTC, bakpaul approved these changes

2023-06-29 10:40 UTC, merged