[plugins] Remove references to old plugins
sofa-framework/sofa pull request #3960
Opened 2023-06-19 08:38 UTC by hugtalbot

References removed:
- THMPGSpatialHashing, 
- Flexible, 
- Compliant, 
- OptiTrackNatNet, 
- OpenCTMPlugin

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2023-06-19 09:12 UTC, alxbilger approved these changes

2023-06-19 23:56 UTC, fredroy requested changes
You might add `PreassembledMass` and `RigidScale` to the bin because they need Compliant and/or Flexible

2023-06-21 08:43 UTC, epernod approved these changes

2023-06-21 10:37 UTC, alxbilger approved these changes

2023-06-22 00:39 UTC, fredroy approved these changes

2023-06-22 00:40 UTC, merged