[MechanicalLoad] Implement buildStiffnessMatrix in EllipsoidForceField
sofa-framework/sofa pull request #4005
Opened 2023-07-04 09:04 UTC by alxbilger

A task from #3967 + minor cleaning.

I suspect there is also a damping term, which was not taken into account in the derivative before. It needs a deeper investigation.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2023-07-09 23:48 UTC, fredroy commented
[ci-build][with-all-tests]

2023-07-11 01:25 UTC, fredroy requested changes

2023-07-11 01:25 UTC, fredroy commented on Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/EllipsoidForceField.h
> +    SOFA_ELLIPSOIDFORCEFIELD_RENAMEDDATA_DEPRECATED() Data<sofa::type::vector<Contact> > contacts; ///< Contacts
I guess `SOFA_ELLIPSOIDFORCEFIELD_CONTACTS_DEPRECATED` was the first version of the macro and you change it for `SOFA_ELLIPSOIDFORCEFIELD_RENAMEDDATA_DEPRECATED`. But you forgot to update the config.h.in 🤐

2023-07-11 01:25 UTC, fredroy commented on Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/EllipsoidForceField.h
> +    SOFA_ELLIPSOIDFORCEFIELD_RENAMEDDATA_DEPRECATED() Data<sofa::type::RGBAColor> color; ///< ellipsoid color. (default=0,0.5,1.0,1.0)
I think this will be breaking, in the `behavior` way of meaning no ?
If one is using this class (inhering or composing) and was using those data (setValue or whatever), it will not do anything . I know there will be warnings at compilation time but still 🙊
Maybe at least inform the user at runtime with the `DeprecatedData`... or directly break the compilation with the DeprecatedAndRemoved thingy.

EDIT: I guess `DeprecatedData` wont do, as you rename the ""C++"" data, not the ""user space""(?) data itself 🤔

2023-07-17 15:53 UTC, alxbilger commented on Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/EllipsoidForceField.h
> +    SOFA_ELLIPSOIDFORCEFIELD_RENAMEDDATA_DEPRECATED() Data<sofa::type::vector<Contact> > contacts; ///< Contacts
you're right. It's fixed

2023-07-17 15:53 UTC, alxbilger commented on Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/EllipsoidForceField.h
> +    SOFA_ELLIPSOIDFORCEFIELD_RENAMEDDATA_DEPRECATED() Data<sofa::type::RGBAColor> color; ///< ellipsoid color. (default=0,0.5,1.0,1.0)
The new version is not breaking

2023-07-18 07:51 UTC, alxbilger commented
The union comes with a problem: the ForceField constructor does not know which constructor from the union to call. The same for the destructor. For the constructor, the constructors of the Data are explicitly called so it is not a problem. However, it's a problem for the destructor. That is why an explicit call to Data destructors is needed.

See an example here: https://godbolt.org/z/svoo9za6G

2023-07-18 08:08 UTC, alxbilger commented on Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/EllipsoidForceField.h
> +    union
yes, no redirection needed

2023-07-19 08:08 UTC, fredroy approved these changes

2023-07-19 08:25 UTC, alxbilger commented
@hugtalbot that's something to decide. It's not a magic method, it adds a new complexity in the deprecation mechanism. I am not sure

2023-07-19 08:51 UTC, alxbilger commented
@hugtalbot Note that you have to implement a destructor but you are allowed not to call the Data destructor. If you forget it, it's a memory leak.

2023-07-26 10:09 UTC, merged