[SofaMisc] Add a data repository at start-up time
sofa-framework/sofa pull request #402
Opened 2017-09-14 13:20 UTC by fredroy

A small utility object to add a repo at runtime.
Check the example for getting an idea on how to use.

I guess it would be mainly useful for people still using XML scene...

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2017-09-18 09:24 UTC, guparan requested changes

2017-09-18 09:24 UTC, guparan commented on modules/SofaMisc/AddResourceRepository.cpp
> +#define SOFA_COMPONENT_MISC_ADDRESOURCEREPOSITORY_CPP
Don't forget the license header here...

2017-09-18 09:24 UTC, guparan commented on modules/SofaMisc/SofaMisc_test/AddResourceRepository_test.cpp
> +#include <SofaTest/Sofa_test.h>
... and here :)

2017-09-18 12:09 UTC, guparan approved these changes

2017-09-21 13:57 UTC, damienmarchal commented
[ci-build]

2017-09-22 08:26 UTC, damienmarchal commented
Thank for adding new features to Sofa and having provided tests with it.
Seem to compile and does not turn the CI in full red.
So let's merge it.

2017-09-22 08:27 UTC, merged