[GuiQt] Remove some unactivated code
sofa-framework/sofa pull request #4025
Opened 2023-07-11 15:02 UTC by epernod

Just some cleaning while debugging the gui.

All code are under ifdef never define.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2023-07-12 00:20 UTC, fredroy requested changes
I think you can also remove all the code related to `SOFA_GUI_QT_NO_RECORDER` as it is always defined (and we have a nice double negation 🤐 `#ifndef SOFA_GUI_QT_NO_RECORDER`)

2023-07-12 00:20 UTC, fredroy commented on Sofa/GUI/Qt/src/sofa/gui/qt/RealGUI.cpp
> +            fileOpenSimu(s.toStdString());
TIL I learn about the `.simu` extension 🙃

2023-07-12 07:35 UTC, epernod commented on Sofa/GUI/Qt/src/sofa/gui/qt/RealGUI.cpp
> +            fileOpenSimu(s.toStdString());
will remove SOFA_GUI_QT_NO_RECORDER next time I dig into the gui ^^

2023-07-12 08:06 UTC, alxbilger reviewed
What was `SOFA_GUI_INTERACTION` supposed to do?

2023-07-14 02:46 UTC, fredroy approved these changes

2023-07-18 08:01 UTC, fredroy commented
> What was `SOFA_GUI_INTERACTION` supposed to do?

I guess nobody knows 🔮

2023-07-18 08:16 UTC, epernod commented
> What was `SOFA_GUI_INTERACTION` supposed to do?

I dig into the git history before removing the macro but I was not able to find what it was doing and why the macro is not anymore here (introduce/remove before moving on CMake).

2023-07-18 23:53 UTC, merged