[GitHub] Action to check labels
sofa-framework/sofa pull request #4079
Opened 2023-08-05 20:23 UTC by hugtalbot

Now, this action checks and make sure that sufficiently descriptive labels are set.
Among the 8 possible labels:
- enhancement
- deprecated
- refactoring
- pr: breaking
- pr: clean
- pr: fix
- pr: new feature
- pr: test

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2023-08-06 23:38 UTC, fredroy requested changes

2023-08-06 23:38 UTC, fredroy commented on .github/workflows/label-checker.yml
> +            if (!labels.includes('enhancement') && !labels.includes('deprecated') && !labels.includes('refactoring') && !labels.includes('pr: breaking') && !labels.includes('pr: clean') && !labels.in
I would create an array of stuff to compare with, it will be easier to add/remove tags in the future

2023-08-08 01:30 UTC, fredroy approved these changes

2023-08-08 09:11 UTC, epernod commented on .github/workflows/label-checker.yml
> +            const validLabels = ['enhancement', 'deprecated', 'refactoring', 'pr: breaking', 'pr: clean', 'pr: fix', 'pr: new feature', 'pr: test'];
This is a good idea but are you sure about the list of labels required?

I would have expected a first list with the status:
to review || wip 
And a second list on the type:
pr: xxx

btw I would turn `refactoring` into `pr: refactoring`   and same for `pr: enhancement`
And I would remove deprecated from this list

2023-08-29 08:01 UTC, epernod approved these changes
ok for me.
Just for the logs, could you just put in a comment what should be the output of those messages if the PR fails to pass the tests.
just copy past the message or a screenshot of the result.

2023-08-30 08:28 UTC, epernod commented
![EJ1cXMfVAAAfvpW](https://github.com/sofa-framework/sofa/assets/21199245/e432d7b9-de26-4b02-94c7-d00810259123)

2023-09-01 07:33 UTC, epernod reviewed
trust your YAML skills 🤓

2023-09-01 07:33 UTC, epernod commented on .github/workflows/label-checker.yml
> +      - name: Delay for 3 Seconds
good idea, maybe a little more than 3 seconds? 
like 10 or 15 sec

2023-09-01 07:55 UTC, epernod commented on .github/workflows/label-checker.yml
> +          sleep 3
```suggestion
          sleep 10
```

2023-09-01 07:56 UTC, epernod commented on .github/workflows/label-checker.yml
> +      - name: Delay for 3 Seconds
```suggestion
      - name: Delay for 10 Seconds
```

2023-09-01 07:56 UTC, epernod commented on .github/workflows/label-checker.yml
> +          sleep 3
```suggestion
          echo "Waiting for 10 seconds in case other labels get changed"
          sleep 10
```

2023-09-01 15:49 UTC, epernod approved these changes

2023-09-03 20:08 UTC, merged