[LinearSystem] Assemble non-mapped and mapped matrices in parallel
sofa-framework/sofa pull request #4172
Opened 2023-09-14 10:21 UTC by alxbilger

Based on #4158 

Non-mapped and mapped matrices can be assembled in parallel because the contributions are not accumulated in the same matrix data structure.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2023-09-20 11:26 UTC, alxbilger commented
[ci-build][with-all-tests]

2023-09-22 09:58 UTC, alxbilger commented
From the scene `examples/Component/LinearSystem/MatrixLinearSystem.scn`

The timeline of the sequential assembly:
![assembleSequential](https://github.com/sofa-framework/sofa/assets/10572752/669405f7-62ce-409c-bf19-30a33aa32cbf)


The timeline of the parallel assembly:
![assembleParallel](https://github.com/sofa-framework/sofa/assets/10572752/43e06470-38b8-4305-bb11-93443297caaa)

Both pictures are not at the same scale

2023-09-22 10:02 UTC, alxbilger commented
Since this PR is based on an another, it can be difficult to review it. Here is the diff with the other PR: https://github.com/alxbilger/sofa/compare/constantsparsitypattern...alxbilger:sofa:independantmatrices

2023-09-24 23:58 UTC, fredroy requested changes

2023-09-24 23:58 UTC, fredroy commented on Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.h
> +    Data< bool > d_parallelAssemblyIndependantMatrices; ///< If true, independant matrices (global matrix vs mapped matrices) are assembled in parallel
```suggestion
    Data< bool > d_parallelAssemblyIndependentMatrices; ///< If true, independent matrices (global matrix vs mapped matrices) are assembled in parallel
```

https://en.wiktionary.org/wiki/independant 🙊

2023-09-24 23:58 UTC, fredroy commented on Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.inl
> +        (initData(&d_parallelAssemblyIndependantMatrices, true, "parallelAssemblyIndependantMatrices", "If true, independant matrices (global matrix vs mapped matrices) are assembled in parallel"))
```suggestion
    , d_parallelAssemblyIndependentMatrices
        (initData(&d_parallelAssemblyIndependentMatrices, true, "parallelAssemblyIndependentMatrices", "If true, independent matrices (global matrix vs mapped matrices) are assembled in parallel"))
```

2023-09-24 23:58 UTC, fredroy commented on Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.inl
> +        if (d_parallelAssemblyIndependantMatrices.getValue() && taskScheduler && taskScheduler->getThreadCount() < 1)
```suggestion
        if (d_parallelAssemblyIndependentMatrices.getValue() && taskScheduler && taskScheduler->getThreadCount() < 1)
```

2023-09-24 23:58 UTC, fredroy commented on Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.inl
> +        const simulation::ForEachExecutionPolicy execution = d_parallelAssemblyIndependantMatrices.getValue() ?
```suggestion
        const simulation::ForEachExecutionPolicy execution = d_parallelAssemblyIndependentMatrices.getValue() ?
```

2023-09-24 23:58 UTC, fredroy commented on Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.inl
> +        (initData(&d_parallelAssemblyIndependantMatrices, true, "parallelAssemblyIndependantMatrices", "If true, independant matrices (global matrix vs mapped matrices) are assembled in parallel"))
And should it be true by default ?

2023-09-27 07:57 UTC, alxbilger commented
[ci-build][with-all-tests]

2023-09-27 07:59 UTC, alxbilger commented on Sofa/Component/LinearSystem/src/sofa/component/linearsystem/MatrixLinearSystem.inl
> +        (initData(&d_parallelAssemblyIndependantMatrices, true, "parallelAssemblyIndependantMatrices", "If true, independant matrices (global matrix vs mapped matrices) are assembled in parallel"))
to be set to false

2023-10-04 08:33 UTC, fredroy approved these changes

2023-10-04 15:49 UTC, merged