[all] Generalize the usage of ScopedAdvancedTimer
sofa-framework/sofa pull request #4177
Opened 2023-09-18 12:56 UTC by alxbilger

By using RAII, `ScopedAdvancedTimer` is less error-prone than `AdvancedTimer::stepBegin/stepEnd`. Let's use it more, in the goal of having only 1 way to define a timer.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2023-09-18 23:59 UTC, fredroy commented
[ci-build][with-all-tests]

2023-09-19 20:56 UTC, epernod commented
I think you have a true positive test failing: [SceneTests.applications/plugins/SofaPython3/examples.advanced_timer.py](https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/PR-4177/CI_CONFIG=windows_vs2019,CI_PLUGINS=options,CI_TYPE=release/4/testReport/SceneTests/applications_plugins_SofaPython3_examples/advanced_timer_py/)

2023-09-19 20:57 UTC, epernod requested changes
I think you have a true positive test failing to fix: [SceneTests.applications/plugins/SofaPython3/examples.advanced_timer.py](https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/PR-4177/CI_CONFIG=windows_vs2019,CI_PLUGINS=options,CI_TYPE=release/4/testReport/SceneTests/applications_plugins_SofaPython3_examples/advanced_timer_py/)

2023-09-22 13:29 UTC, bakpaul approved these changes

2023-09-27 09:12 UTC, merged