Fix segfault when accessing and empty CSR matrix (through iterators)
sofa-framework/sofa pull request #4179
Opened 2023-09-18 15:24 UTC by courtecuisse

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2023-09-18 15:41 UTC, alxbilger requested changes
The change makes sense, but I would like to know if your code worked in the past, before some SOFA changes, as it appears that the method `getRowRange` never checked the bounds.

2023-09-18 15:41 UTC, alxbilger commented on Sofa/framework/LinearAlgebra/src/sofa/linearalgebra/CompressedRowSparseMatrixGeneric.h
> +        if ((unsigned) id+1 >= rowBegin.size()) return Range();
```suggestion
        if ((unsigned) id >= rowBegin.size()) return Range();
```
`id == rowBegin.size()` would also lead to an out-of-bounds.

2023-09-18 23:46 UTC, fredroy commented
[ci-build][with-all-tests]

2023-09-18 23:58 UTC, fredroy commented
Well spotted @courtecuisse 

- This fix reminds me that some bound checks (e.g type::vector) does only check in DEBUG mode/assertion https://github.com/sofa-framework/sofa/blob/649a41bf386b78c95264d9a6fb3125f4662c5a58/Sofa/framework/Type/src/sofa/type/vector_T.h#L108
obviously for performance reason. Should we do that here ? Thing is, many people do not run in debug so.... 🤐

- I guess this is a far cry but @fjourdes  you would want to get the fix ? (if you dont have it already...)

2023-10-24 02:00 UTC, fredroy commented
Superseded by https://github.com/sofa-framework/sofa/pull/4236
(@courtecuisse)

2023-10-24 02:00 UTC, closed without merging