[CollisionModel] New: added collision layer property
sofa-framework/sofa pull request #4219
Opened 2023-10-04 14:32 UTC by polyakovkrylo

This PR introduces  collision layers, a collision filtering algorithm similar to the one used in [Unity's collsion pipeline](https://docs.unity3d.com/Manual/LayerBasedCollision.html). The overall idea is to omit collision detection for models that are in different layers.  This way, each layer can be used for different functionality, e.g. cutting simulation.
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2023-10-04 15:01 UTC, alxbilger commented
Hey! Can you explain how it is different from the `group` property? Thanks

2023-10-04 15:42 UTC, polyakovkrylo commented
Hi, @alxbilger! It works the opposite way the collision groups work. With collision groups, collision can only occur between the models' group sets do not overlap (no common groups). With the collision layers it' s the opposite -- collision can only occur if the models are in the same layer.

2023-10-11 08:07 UTC, alxbilger requested changes

2023-10-11 08:07 UTC, alxbilger commented on Sofa/framework/Core/src/sofa/core/CollisionModel.h
> +    Data<int> layer;
```suggestion
    Data<int> d_layer;
```

2023-10-11 08:08 UTC, alxbilger commented on Sofa/framework/Core/src/sofa/core/CollisionModel.h
> +    Data<int> layer;
It also needs to be initialized in the constructor

2023-10-11 08:15 UTC, alxbilger commented on Sofa/framework/Core/src/sofa/core/CollisionModel.h
> +    Data<int> layer;
Does it make sense to define more than one layer for a collision model?

2023-10-11 08:48 UTC, bakpaul commented
Hi vlad, this PR has also been discussed during the dev meeting. 
The conclusions are the same as for the #4226 : we need more context/example of use (for instance to see how you use it in your scenes or plugin). 

We are also curious to know how you handle differences between this and the group mechanism : what happens if you are in the same time in the same group and in the same layer ? Are the two mechanism really necessary ? 
It could be also possible to remplace the group mechanism by yours to have a more positive mechanism (same layer = collision instead of diffrent group = collision). But for this it would need to handle multiple layer by object. 

And finally, again, some unit testing would be great if we manage to find a mechanism that suites every one.

2026-05-08 09:20 UTC, closed without merging