[all] Fix warnings
sofa-framework/sofa pull request #4291
Opened 2023-11-12 14:40 UTC by hugtalbot

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2023-11-13 08:15 UTC, alxbilger requested changes
Almost approved ;)

2023-11-13 08:15 UTC, alxbilger commented on Sofa/Component/LinearSolver/Direct/src/sofa/component/linearsolver/direct/SparseLDLSolver.h
> +
```suggestion
```

I don't get why you added this. This Data is already in its base class in `MatrixLinearSolver`

2023-11-14 08:43 UTC, fredroy commented
[ci-build][with-all-tests]

2023-11-16 10:56 UTC, alxbilger approved these changes

2023-11-28 07:44 UTC, fredroy commented
[ci-build][with-all-tests]

2023-12-01 13:08 UTC, alxbilger approved these changes

2023-12-01 16:27 UTC, bakpaul approved these changes

2023-12-01 16:27 UTC, merged