[Constraint] Make name of constraints more explicit
sofa-framework/sofa pull request #4302
Opened 2023-11-17 10:44 UTC by bakpaul

This PR is a first step for the issue #3952. 

I modified the names of the constraints following the rule that we agreed upon. Still need to change spring force-fields that can behave as penalties. 

The changes where straight, not more though than adding the type into the name was done. If any name doesn't fit your standard, feel free to suggest any changes. 

This PR also add a componentRenamed mechanism that creates an alias automatically for renamed objects.

TODO:

- [x]  Edit Sofa/framework/Helper/src/sofa/helper/ComponentChange.cpp
  - [x]  Add a API in ComponentChange.cpp for Renamed component (avoiding to add an alias manually in the class)
- [x] Move the C++ alias in the old header
- [x] Change name of projective constraints strating by `ProjectOn`

2023-11-21 16:20 UTC, bakpaul commented
[ci-build][with-all-tests]

2023-11-21 16:22 UTC, bakpaul commented
I am just not sure about the alias compatibility. It is for scene launching, but nothing guaranty that those aliases will one day be removed. Maybe the factory lacks a method `addDeprecationAlias` (or I am not aware of this) ?

2023-11-22 09:34 UTC, alxbilger reviewed
You need to edit Sofa/framework/Helper/src/sofa/helper/ComponentChange.cpp

2023-11-29 16:09 UTC, bakpaul commented
[ci-build][with-all-tests]

2023-12-11 08:09 UTC, alxbilger requested changes
Almost good to go. Keep in mind that the documentation website will need to be updated accordingly.

2023-12-11 08:09 UTC, alxbilger commented on Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/SlidingLagrangianConstraint.cpp
> +int SlidingLagrangianConstraintClass = core::RegisterObject("TODO-SlidingLagrangianConstraint")
I am not really happy with this description...

2023-12-11 08:09 UTC, alxbilger commented on applications/plugins/SofaCarving/examples/CarvingTool.scn
> +        <RequiredPlugin name="Sofa.Component.Constraint.Projective"/> <!-- Needed to use components [FixedConstraint, LinearMovementProjectiveConstraint] -->
```suggestion
        <RequiredPlugin name="Sofa.Component.Constraint.Projective"/> <!-- Needed to use components [LinearMovementProjectiveConstraint] -->
```

There is also an occurence of `FixedConstraint` in this file. Could you check again in the examples of all the code base that you renamed the components?

2023-12-12 16:09 UTC, bakpaul commented on Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/SlidingLagrangianConstraint.cpp
> +int SlidingLagrangianConstraintClass = core::RegisterObject("TODO-SlidingLagrangianConstraint")
Yes me neither, but in fact this is not the only component and it is not really in the scope of this pr...

2023-12-18 10:39 UTC, bakpaul commented
[ci-build][with-all-tests]

2023-12-18 16:36 UTC, bakpaul commented
Finally I needed the changed introduced in the (now closed) [PR #4324](https://github.com/sofa-framework/sofa/pull/4324) to finalize the automatic alias creation mechanism. Now CI should not be crying anymore.

2023-12-18 16:40 UTC, bakpaul commented
[ci-build][with-all-tests]

2023-12-20 11:10 UTC, merged