[Simulation.Core] Remove usage of ill-used nodeData in MechanicalGetNonDiagonalMassesCountVisitor and MechanicalVDotVisitor
sofa-framework/sofa pull request #4328
Opened 2023-12-01 02:42 UTC by fredroy

First task of removing(deprecating) the usage of nodeData (noticed in #4327)

Those two visitors are using the pointer nodeData for local computations so It was changed to local (weak) stored pointers. 
Not fan of pointers but it does not break API. (a SReal to count is weird btw)

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2023-12-01 03:50 UTC, fredroy commented
[ci-build][with-all-tests]

2023-12-01 08:22 UTC, alxbilger requested changes
I think the counter is SReal only because of the use of `nodeData`. If you don't use it, I don't see any reason to switch to an integer.

2023-12-01 16:13 UTC, bakpaul approved these changes

2023-12-04 04:33 UTC, fredroy commented
> I think the counter is SReal only because of the use of `nodeData`. If you don't use it, I don't see any reason to switch to an integer.

To keep the API "non-breaking"  🙊 but I can make it an integer if we dont care ✌️

2023-12-06 10:07 UTC, alxbilger commented
Since this visitor is rather recent, and used at only one place. We can consider convert the SReal to an integer even if it's breaking

2023-12-13 09:00 UTC, alxbilger commented on Sofa/framework/Simulation/Core/src/sofa/simulation/mechanicalvisitor/MechanicalGetNonDiagonalMassesCountVisitor.h
> +    // given result is not a Real anymore since https://github.com/sofa-framework/sofa/pull/4328
```suggestion
```

2023-12-13 14:05 UTC, merged