[Topology] Fix method isQuadDeulaunayOriented and its use in splitAlongPath
sofa-framework/sofa pull request #4494
Opened 2024-02-11 11:26 UTC by epernod

Method isQuadDeulaunayOriented  was only handling some specific case. Use directly the computation of angles to check flipping Delaunay condition to triangulate a quad see [wikipedia page](https://en.wikipedia.org/wiki/Delaunay_triangulation#Visual_Delaunay_definition:_Flipping) 

And in fact the method was not working well but the method splitAlongPath used for triangular incision was calling it with wrong quad structure. 
Luckily in this case we had error*error = good behavior... 

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-02-11 12:50 UTC, epernod commented
[ci-build][with-all-tests]

2024-02-14 09:52 UTC, alxbilger requested changes

2024-02-14 09:52 UTC, alxbilger commented on Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.inl
> +    bool isDelau = (alpha + beta > M_PI) ? false : true;
```suggestion
    const bool isDelau = (alpha + beta <= M_PI);
```

2024-02-14 09:52 UTC, alxbilger commented on Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.inl
> +    //std::cout << "alpha: " << alpha*180/ M_PI << " | beta: " << beta * 180 / M_PI << " delaunay: " << isDelau << std::endl;
```suggestion
```

2024-02-14 09:52 UTC, alxbilger commented on Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/TriangleSetGeometryAlgorithms.inl
> +                    new_triangles.push_back(Triangle(vertexOrder[1], vertexOrder[2], vertexOrder[4]));
```suggestion
                    new_triangles.emplace_back(vertexOrder[1], vertexOrder[2], vertexOrder[4]);
```

2024-02-14 09:54 UTC, bakpaul commented
One unit test failling : 
https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/PR-4494/CI_CONFIG=ubuntu_gcc,CI_PLUGINS=options,CI_TYPE=release/2/testReport/UnitTests.Sofa_Component/Topology_InciseProcessor_test/InciseTriangles/

2024-02-19 08:41 UTC, epernod commented
> One unit test failling : https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/PR-4494/CI_CONFIG=ubuntu_gcc,CI_PLUGINS=options,CI_TYPE=release/2/testReport/UnitTests.Sofa_Component/Topology_InciseProcessor_test/InciseTriangles/

Unit test references have been changed. The new version is more accurate.

2024-02-22 00:55 UTC, merged