[GUI] Remove the New menu option
sofa-framework/sofa pull request #4523
Opened 2024-02-23 09:11 UTC by hugtalbot

Since SOFA is no modeler, remove the New option as pointed out in #4520

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-02-23 09:36 UTC, alxbilger requested changes
Maybe remove `RealGUI::fileNew()` as well.

There is also 3 other sections in `GUI.ui`:

```
  <action name="fileNewAction">
   <property name="icon">
    <iconset>
     <normaloff>image2</normaloff>image2</iconset>
   </property>
   <property name="text">
    <string>&amp;New</string>
   </property>
   <property name="iconText">
    <string>New</string>
   </property>
   <property name="shortcut">
    <string>Ctrl+N</string>
   </property>
   <property name="name" stdset="0">
    <cstring>fileNewAction</cstring>
   </property>
  </action>
```

and

```
<connection>
   <sender>fileNewAction</sender>
   <signal>triggered()</signal>
   <receiver>GUI</receiver>
   <slot>fileNew()</slot>
   <hints>
    <hint type="sourcelabel">
     <x>-1</x>
     <y>-1</y>
    </hint>
    <hint type="destinationlabel">
     <x>20</x>
     <y>20</y>
    </hint>
   </hints>
  </connection>
```

and 

```
<slot>fileNew()</slot>
```

2024-03-12 10:59 UTC, alxbilger approved these changes

2024-03-13 14:55 UTC, fredroy commented
Tested & approved, -> ready

2024-03-13 14:55 UTC, fredroy approved these changes

2024-03-13 14:55 UTC, merged