[all] Fix some warnings
sofa-framework/sofa pull request #4529
Opened 2024-02-24 13:13 UTC by hugtalbot

While starting the lifecycle for v24.06, found some minor fixes of warnings

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-03-01 11:54 UTC, epernod commented on applications/plugins/SofaCarving/src/SofaCarving/CarvingManager.cpp
> +            }
small PR hijacking

2024-03-01 11:55 UTC, epernod commented on applications/plugins/SofaCarving/src/SofaCarving/CarvingManager.cpp
> +            }
note: it is not possible to compare nbElems and elemsToRemove.size() because the vector can have redundant indices

2024-03-07 09:30 UTC, bakpaul approved these changes

2024-03-14 08:53 UTC, alxbilger requested changes

2024-03-14 08:53 UTC, alxbilger commented on applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.cpp
> +    SOFA_UNUSED(onlyVisible);
From what I can see, all the implementations of `computeBBox` have the following code:

```suggestion
    if (!onlyVisible) return;
```

2024-03-14 15:05 UTC, alxbilger approved these changes

2024-03-15 08:31 UTC, merged