[plugins] Add SimpleApi as a dependency in SofaCarving_test
sofa-framework/sofa pull request #4572
Opened 2024-03-07 16:23 UTC by hugtalbot

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-03-13 08:16 UTC, fredroy approved these changes

2024-03-14 15:55 UTC, alxbilger requested changes
Since `SofaCarving_test` depends already on `Sofa.Testing`, which has a dependency on `Sofa.SimpleApi`, I think it's not necessary to modify the `CMakeLists.txt` file.

2024-03-19 15:10 UTC, alxbilger commented
I took the liberty to remove your changes in CMakeLists.txt @hugtalbot

2024-03-19 22:59 UTC, epernod approved these changes

2024-03-20 04:23 UTC, fredroy commented
[ci-build][force-full-build]

2024-03-20 04:43 UTC, merged