[LinearAlgebra] Trigger error on the Eigen version
sofa-framework/sofa pull request #4630
Opened 2024-04-05 08:43 UTC by alxbilger

The fix from Eigen https://gitlab.com/libeigen/eigen/-/commit/80142362ac35ca77bfc5ccf7ba49c9f034b57abc, making `SparseMatrixProduct` compile, is available starting 3.3.5.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-04-05 09:21 UTC, alxbilger commented
[ci-build][with-all-tests]

2024-04-08 22:18 UTC, epernod approved these changes

2024-04-11 03:38 UTC, fredroy commented
![Screenshot 2024-04-11 123723](https://github.com/sofa-framework/sofa/assets/11028016/b442c8c0-1336-4d7a-b34b-345325edafc1)

🤷‍♂️👮

2024-04-11 03:44 UTC, fredroy requested changes
It is a bit weird to allow the user to use a version < 3.3.5 after configuring, etc, and then throw an error at the compilation 😅.
IMO, An enforcement of the version would be preferable at the cmake stage, while find_package()'ing

Here https://github.com/sofa-framework/sofa/blob/8454dfeaf854a4bd4353a21d5d72ff184716e210/Sofa/framework/LinearAlgebra/CMakeLists.txt#L65

2024-04-12 14:33 UTC, fredroy approved these changes

2024-04-15 01:38 UTC, merged