[Spring] Remove duplicated spring indices
sofa-framework/sofa pull request #4635
Opened 2024-04-08 15:26 UTC by bakpaul

This component was using a set of data to define indices on which to apply springs. But those data already exist in the parent class. This was resulting in strange behaviors when using `AttachBodyPerformer` (which uses this component to attach an object to the mouse) out of the GUI API. 

In fact the performer was acting on the parent data which is not directly used by the StiffSpringForcefield. A nebulous chain of update triggered by a GUI update made it work with the mouse interactor anyway, but not when the performer was own by a graph component. 

Anyway this mechanism doesn't seem to have any added value and now the performer works great even outside the GUI interaction API.  

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-04-08 22:36 UTC, epernod requested changes

2024-04-08 22:36 UTC, epernod commented on Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/StiffSpringForceField.inl
> +    this->addUpdateCallback("updateSprings", { &this->d_springsIndices[0],&this->d_springsIndices[1], &d_lengths, &this->ks, &this->kd}, [this](const core::DataTracker& t)
I'm not really sure it is the same thing...
In any case you should add alias with deprecated warning message

2024-04-09 09:07 UTC, damienmarchal commented on Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/StiffSpringForceField.h
> +    core::objectmodel::lifecycle::DeprecatedData d_indices1{this, "v24.06", "v24.12", "indices1", "This data has been replaced by the data springsIndices1 "};
We are the master of lifecycle management :)

2024-04-09 15:36 UTC, bakpaul commented
[ci-build][with-all-tests]

2024-04-18 06:52 UTC, closed without merging