[Fem] Small update on container access to avoid unecessary check
sofa-framework/sofa pull request #4639
Opened 2024-04-09 15:57 UTC by epernod

continue porting changes from old branches: https://github.com/epernod/sofa/pull/12/files

getTetrahedron(i) perform a test if i is not out of bounds.
When a function is called often and loop on the list of tetrahedra, it is best to get a ref to the array and loop on it.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-04-10 08:06 UTC, alxbilger approved these changes

2024-04-11 00:44 UTC, fredroy requested changes

2024-04-11 00:44 UTC, fredroy commented on Sofa/Component/SolidMechanics/FEM/HyperElastic/src/sofa/component/solidmechanics/fem/hyperelastic/TetrahedronHyperelasticityFEMDrawing.h
> +        const auto t = tetraArray[i];
(cannot suggest)
No point to get the index and t is making an unnecessary copy.
Suggestion:
```
for(const auto& t : topology->getTetrahedra())
{
...
```

2024-04-11 00:44 UTC, fredroy commented on Sofa/Component/SolidMechanics/TensorMass/src/sofa/component/solidmechanics/tensormass/TetrahedralTensorMassForceField.inl
> +    for (Index tetraId : tetrahedronAdded)
```suggestion
    for (const Index tetraId : tetrahedronAdded)
```

2024-04-11 00:44 UTC, fredroy commented on Sofa/Component/SolidMechanics/TensorMass/src/sofa/component/solidmechanics/tensormass/TetrahedralTensorMassForceField.inl
>      const typename DataTypes::VecCoord restPosition=this->mstate->read(core::ConstVecCoordId::restPosition())->getValue();
it is doing a (costly) copy.

```suggestion
    const auto& restPosition=this->mstate->read(core::ConstVecCoordId::restPosition())->getValue();
```
or a ReadAccessor

2024-04-11 21:54 UTC, epernod commented
[ci-build][with-all-tests]

2024-04-12 00:09 UTC, fredroy approved these changes

2024-04-12 07:28 UTC, bakpaul approved these changes

2024-04-18 03:35 UTC, merged