[Collision.Detection.Algorithm] Rename Data
sofa-framework/sofa pull request #4674
Opened 2024-04-22 15:45 UTC by lamriaimen

According to the guidelines

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-04-22 16:09 UTC, bakpaul commented on README.md
> +SOFA provideqtcreators a plugin system allowing the coupling of additional codes to add functionalities. A lot of plugins are already referenced in the [source code](https://github.com/sofa-framework
This change might have been added by mistake

2024-04-24 00:56 UTC, fredroy commented
[ci-build][with-all-tests]

2024-04-29 02:06 UTC, fredroy commented
[ci-build][with-all-tests]

2024-04-29 12:34 UTC, alxbilger requested changes

2024-04-29 12:34 UTC, alxbilger commented on Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/IncrSAP.h
> +    Data<bool> d_bDraw; ///< enable/disable display of results
Actually, `bDraw` is never used. So I would be in favor to deprecate it without renaming. You must use `DeprecatedData` (see https://www.sofa-framework.org/community/doc/contributing-to-sofa/lifecycle-mechanisms/). The method `setDraw` is also to be deprecated.

2024-04-29 12:39 UTC, alxbilger commented on Sofa/Component/Collision/Detection/Algorithm/src/sofa/component/collision/detection/algorithm/BruteForceBroadPhase.h
> +class SOFA_COMPONENT_COLLISION_DETECTION_ALGORITHM_API BruteForceBroadPhase : public core::collision::BroadPhaseDetection {
[The guidelines](https://github.com/sofa-framework/sofa/blob/master/GUIDELINES.md) wants you to use Allman style
```suggestion
class SOFA_COMPONENT_COLLISION_DETECTION_ALGORITHM_API BruteForceBroadPhase : public core::collision::BroadPhaseDetection
{
```

2024-04-29 13:00 UTC, bakpaul approved these changes

2024-05-03 08:03 UTC, alxbilger approved these changes

2024-05-07 06:09 UTC, merged