[Collision.Detection.Intersection] Rename Data
sofa-framework/sofa pull request #4675
Opened 2024-04-23 12:05 UTC by lamriaimen

According to the guidelines

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-04-24 00:56 UTC, fredroy commented
[ci-build][with-all-tests]

2024-04-24 13:51 UTC, bakpaul commented
[ci-depends-on https://github.com/SofaDefrost/ModelOrderReduction/pull/116]

2024-04-29 12:51 UTC, alxbilger commented
[ci-build][with-all-tests][force-full-build]

2024-04-29 12:55 UTC, alxbilger requested changes
Overall, check the indentation is consistant

2024-04-29 12:55 UTC, alxbilger commented on Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/BaseProximityIntersection.cpp
> +    contactDistance.setParent(&d_contactDistance);
Can you check that the indentation is consistant here? Normally, it's 4 spaces for 1 tab.

2024-04-29 12:55 UTC, alxbilger commented on Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/LocalMinDistance.h
> +    Data<bool> angleCone;
```suggestion
    Data<double> angleCone;
```

2024-04-29 12:55 UTC, alxbilger commented on Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/LocalMinDistance.h
> +    Data<bool> coneFactor;
```suggestion
    Data<double> coneFactor;
```

2024-04-29 13:04 UTC, bakpaul requested changes

2024-04-29 13:04 UTC, bakpaul commented on Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MinProximityIntersection.h
>   * - Line/Line (if useLineLine is true)
```suggestion
 * - Line/Line (if d_useLineLine is true)
```

2024-04-29 13:04 UTC, bakpaul commented on Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MinProximityIntersection.h
> + * Datas can be set to ignore some pairs of collision models (d_useSphereTriangle, usePointPoint, etc).
```suggestion
 * Datas can be set to ignore some pairs of collision models (d_useSphereTriangle, d_usePointPoint, etc).
```

2024-04-29 13:04 UTC, bakpaul commented on Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MinProximityIntersection.h
>   * - Point/Point (if usePointPoint is true)
```suggestion
 * - Point/Point (if d_usePointPoint is true)
```

2024-05-03 08:06 UTC, alxbilger requested changes

2024-05-03 08:06 UTC, alxbilger commented on Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MinProximityIntersection.cpp
> +    , d_useSphereTriangle(initData(&d_useSphereTriangle, true, "d_useSphereTriangle", "activate Sphere-Triangle intersection tests"))
```suggestion
    , d_useSphereTriangle(initData(&d_useSphereTriangle, true, "useSphereTriangle", "activate Sphere-Triangle intersection tests"))
```

2024-05-03 08:06 UTC, alxbilger commented on Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/MinProximityIntersection.cpp
> +    , d_useLinePoint(initData(&d_useLinePoint, true, "d_useLinePoint", "activate Line-Point intersection tests"))
```suggestion
    , d_useLinePoint(initData(&d_useLinePoint, true, "useLinePoint", "activate Line-Point intersection tests"))
```

Can you look over all your PRs that there are no such mistakes?

2024-05-07 06:49 UTC, merged