[IO] Rename Data
sofa-framework/sofa pull request #4679
Opened 2024-04-25 10:11 UTC by lamriaimen

According to the guidelines

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-04-25 10:13 UTC, alxbilger commented
[ci-build][with-all-tests]

2024-04-29 13:16 UTC, alxbilger requested changes

2024-04-29 13:16 UTC, alxbilger commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshSTLLoader.h
> +    Data <bool> forceBinary;
```suggestion
    Data <bool> _forceBinary;
```
It previously started with an underscore

2024-04-29 13:16 UTC, alxbilger commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshSTLLoader.h
> +    Data <unsigned int> headerSize;
```suggestion
    Data <unsigned int> _headerSize;
```

2024-04-29 13:16 UTC, alxbilger commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshSTLLoader.cpp
> +    , d_headerSize(initData(&d_headerSize, 80u, "d_headerSize", "Size of the header binary file (just before the number of facet)."))
```suggestion
    , d_headerSize(initData(&d_headerSize, 80u, "headerSize", "Size of the header binary file (just before the number of facet)."))
```
Be careful in all of your PRs that you don't change the name of the Data.

2024-04-29 13:16 UTC, alxbilger commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshTrianLoader.cpp
> +    , d_trianglesOnBorderList(initData(&d_trianglesOnBorderList, "d_trianglesOnBorderList", "List of triangle indices which are on the border of the mesh loaded."))
```suggestion
    , d_neighborTable(initData(&d_neighborTable, "neighborTable", "Table of neighborhood triangle indices for each triangle."))
    , d_edgesOnBorder(initData(&d_edgesOnBorder, "edgesOnBorder", "List of edges which are on the border of the mesh loaded."))
    , d_trianglesOnBorderList(initData(&d_trianglesOnBorderList, "trianglesOnBorderList", "List of triangle indices which are on the border of the mesh loaded."))
```

2024-04-29 13:16 UTC, alxbilger commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/OffSequenceLoader.cpp
> +    , d_stepDuration(initData(&d_stepDuration, 0.04, "d_stepDuration", "how long each file is loaded") )
```suggestion
    , d_stepDuration(initData(&d_stepDuration, 0.04, "stepDuration", "how long each file is loaded") )
```

2024-04-29 13:16 UTC, alxbilger commented on Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridTopology.cpp
> +    , dataResolution(initData(&dataResolution, type::Vec3i(0,0,0), "d_dataResolution", "Dimension of the voxel File"))
```suggestion
    , dataResolution(initData(&dataResolution, type::Vec3i(0,0,0), "dataResolution", "Dimension of the voxel File"))
```

2024-04-29 13:22 UTC, bakpaul requested changes
Please be careful when you use 'search and replace' you don't want to rename the data name in the factory

2024-04-29 13:22 UTC, bakpaul commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshSTLLoader.cpp
> +    , d_headerSize(initData(&d_headerSize, 80u, "d_headerSize", "Size of the header binary file (just before the number of facet)."))
```suggestion
    , d_headerSize(initData(&d_headerSize, 80u, "headerSize", "Size of the header binary file (just before the number of facet)."))
```

2024-04-29 13:22 UTC, bakpaul commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshTrianLoader.cpp
> +    , d_neighborTable(initData(&d_neighborTable, "d_neighborTable", "Table of neighborhood triangle indices for each triangle."))
```suggestion
    , d_neighborTable(initData(&d_neighborTable, "neighborTable", "Table of neighborhood triangle indices for each triangle."))
```

2024-04-29 13:22 UTC, bakpaul commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshTrianLoader.cpp
> +    , d_edgesOnBorder(initData(&d_edgesOnBorder, "d_edgesOnBorder", "List of edges which are on the border of the mesh loaded."))
```suggestion
    , d_edgesOnBorder(initData(&d_edgesOnBorder, "edgesOnBorder", "List of edges which are on the border of the mesh loaded."))
```

2024-04-29 13:22 UTC, bakpaul commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshTrianLoader.cpp
> +    , d_trianglesOnBorderList(initData(&d_trianglesOnBorderList, "d_trianglesOnBorderList", "List of triangle indices which are on the border of the mesh loaded."))
```suggestion
    , d_trianglesOnBorderList(initData(&d_trianglesOnBorderList, "trianglesOnBorderList", "List of triangle indices which are on the border of the mesh loaded."))
```

2024-04-29 13:22 UTC, bakpaul commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshTrianLoader.h
> +    Data <bool> trian2;
```suggestion
    Data <bool> p_trian2;
```

2024-04-29 13:22 UTC, bakpaul commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/MeshTrianLoader.cpp
> +    trian2.setParent(&d_trian2);
```suggestion
    p_trian2.setParent(&d_trian2);
```

2024-04-29 13:22 UTC, bakpaul commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/OffSequenceLoader.cpp
> +    , d_stepDuration(initData(&d_stepDuration, 0.04, "d_stepDuration", "how long each file is loaded") )
```suggestion
    , d_stepDuration(initData(&d_stepDuration, 0.04, "stepDuration", "how long each file is loaded") )
```

2024-04-29 13:22 UTC, bakpaul commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/VTKExporter.h
> +    Data< std::string > vtkFilename;
```suggestion
    [Data< std::string >](sofa::core::objectmodel::DataFileName) vtkFilename;
```

2024-04-29 13:22 UTC, bakpaul commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/VoxelGridLoader.cpp
> +      d_idxInRegularGrid(initData(&d_idxInRegularGrid, "d_idxInRegularGrid", "indices of the hexa in the grid.")),
```suggestion
      d_idxInRegularGrid(initData(&d_idxInRegularGrid, "idxInRegularGrid", "indices of the hexa in the grid.")),
```

2024-04-29 13:22 UTC, bakpaul commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/VoxelGridLoader.cpp
> +      d_generateHexa(initData (&d_generateHexa, true, "d_generateHexa", "Interpret voxel as either hexa or points")),
```suggestion
      d_generateHexa(initData (&d_generateHexa, true, "generateHexa", "Interpret voxel as either hexa or points")),
```

2024-04-29 13:22 UTC, bakpaul commented on Sofa/Component/Mapping/Linear/src/sofa/component/mapping/linear/LineSetSkinningMapping.inl
> +                    position = xfrom[line[0]].getOrientation().inverseRotate(xto[verticeIndex] - xfrom[line[0]].getCenter());
Add the break after the '=' instead...

2024-04-29 13:22 UTC, bakpaul commented on Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridTopology.cpp
> +    , dataResolution(initData(&dataResolution, type::Vec3i(0,0,0), "d_dataResolution", "Dimension of the voxel File"))
```suggestion
    , dataResolution(initData(&dataResolution, type::Vec3i(0,0,0), "dataResolution", "Dimension of the voxel File"))
```

2024-04-29 13:22 UTC, bakpaul commented on Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/MultilevelHexahedronSetTopologyContainer.cpp
> +      hexaIndexInRegularGrid(initData(&hexaIndexInRegularGrid,"d_idxInRegularGrid","indices of the hexa in the grid.")),
```suggestion
      hexaIndexInRegularGrid(initData(&hexaIndexInRegularGrid,"idxInRegularGrid","indices of the hexa in the grid.")),
```

2024-04-29 13:22 UTC, bakpaul commented on Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridTopologyContainer.cpp
> +    , idxInRegularGrid( initData ( &idxInRegularGrid, sofa::type::vector<BaseMeshTopology::HexaID>(), "d_idxInRegularGrid", "indices in the Regular Grid" ) )
```suggestion
    , idxInRegularGrid( initData ( &idxInRegularGrid, sofa::type::vector<BaseMeshTopology::HexaID>(), "idxInRegularGrid", "indices in the Regular Grid" ) )
```

2024-04-29 15:34 UTC, bakpaul commented
I've put this PR in wip to avoid overloading the CI while you integrate all the comments. Once you've finished all the review, you can change the tag back to to review and then trigger the CI with the usual comment.

2024-04-30 16:00 UTC, lamriaimen commented
[ci-build][with-all-tests]

2024-05-02 08:48 UTC, lamriaimen commented
[ci-build][with-all-tests]

2024-05-03 08:25 UTC, alxbilger requested changes

2024-05-03 08:25 UTC, alxbilger commented on Sofa/framework/Helper/src/sofa/helper/MarchingCubeUtility.cpp
> +        //    Vec3i gridSize = Vec3i ( d_dataResolution[0]/cubeStep, d_dataResolution[1]/cubeStep, d_dataResolution[2]/cubeStep );
Not sure this file is intended to be modified

2024-05-03 08:25 UTC, alxbilger commented on Sofa/framework/Helper/src/sofa/helper/MarchingCubeUtility.h
> +    BoundingBox roi; // Set value to 0 on this limit to always obtain manifold mesh. (Set to d_dataResolution by default but can be changed for ROI)
Not sure this file is intended to be modified

2024-05-07 09:37 UTC, alxbilger approved these changes

2024-05-13 00:31 UTC, fredroy approved these changes

2024-05-13 06:30 UTC, merged