[Playback] Rename Data
sofa-framework/sofa pull request #4681
Opened 2024-04-25 13:58 UTC by lamriaimen

According to the guidelines

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-04-29 01:55 UTC, fredroy commented
[ci-build][with-all-tests]

2024-04-29 13:25 UTC, alxbilger approved these changes

2024-04-29 13:29 UTC, bakpaul requested changes

2024-04-29 13:29 UTC, bakpaul commented on Sofa/Component/Playback/src/sofa/component/playback/InputEventReader.cpp
> +    , d_inverseSense(initData(&d_inverseSense, false, "d_inverseSense", "inverse the sense of the mouvement"))
```suggestion
    , d_inverseSense(initData(&d_inverseSense, false, "inverseSense", "inverse the sense of the mouvement"))
```

2024-04-29 13:29 UTC, bakpaul commented on Sofa/Component/Playback/src/sofa/component/playback/InputEventReader.cpp
> +    d_writeEvents.setParent(&d_writeEvents);
```suggestion
    p_writeEvents.setParent(&d_writeEvents);
```

2024-04-29 13:29 UTC, bakpaul commented on Sofa/Component/Playback/src/sofa/component/playback/InputEventReader.cpp
> +    d_outputFilename.setParent(&d_outputFilename);
```suggestion
    p_outputFilename.setParent(&d_outputFilename);
```

2024-04-29 13:29 UTC, bakpaul commented on Sofa/Component/Playback/src/sofa/component/playback/InputEventReader.h
> +    Data<std::string> p_outputFilename;
```suggestion
    sofa::core::objectmodel::DataFileName p_outputFilename;
```

2024-04-29 13:29 UTC, bakpaul commented on Sofa/Component/Playback/src/sofa/component/playback/InputEventReader.h
> +    Data<std::string> filename;
```suggestion
    sofa::core::objectmodel::DataFileName filename;
```

2024-05-03 09:04 UTC, alxbilger approved these changes
LGTM

2024-05-07 09:39 UTC, fredroy approved these changes

2024-05-08 05:28 UTC, merged