[Setting] Rename Data
sofa-framework/sofa pull request #4682
Opened 2024-04-25 14:52 UTC by lamriaimen

According to the guidelines

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-04-29 05:06 UTC, fredroy commented
[ci-build][with-all-tests]

2024-04-29 13:28 UTC, alxbilger requested changes

2024-04-29 13:28 UTC, alxbilger commented on Sofa/GUI/Qt/src/sofa/gui/qt/GUI.ui
> +               <string comment="This is used to plut curves fter a simulation">Record the state at each time step in file &quot;d_dumpState.data&quot;</string>
This change is not appropriate. You must revert the change

2024-04-29 13:28 UTC, alxbilger commented on Sofa/framework/Simulation/Core/src/sofa/simulation/Simulation.cpp
> +    SCOPED_TIMER_VARNAME(dumpStateTimer, "d_dumpState");
```suggestion
    SCOPED_TIMER_VARNAME(dumpStateTimer, "dumpState");
```

2024-04-29 13:28 UTC, alxbilger commented on Sofa/framework/Simulation/Core/src/sofa/simulation/config.h.in
> +"v23.12", "v24.06", "Use sofa::simulation::node::d_dumpState")
```suggestion
"v23.12", "v24.06", "Use sofa::simulation::node::dumpState")
```

2024-04-29 13:28 UTC, alxbilger commented on Sofa/GUI/Qt/src/sofa/gui/qt/RealGUI.cpp
> +        m_dumpStateStream = new std::ofstream ( "d_dumpState.data" );
```suggestion
        m_dumpStateStream = new std::ofstream ( "dumpState.data" );
```

2024-04-29 13:28 UTC, alxbilger commented on Sofa/Component/Setting/src/sofa/component/setting/StatsSetting.cpp
> +        d_dumpState(initData(&d_dumpState, false, "d_dumpState", "Dump state vectors at each time step of the simulation"))
```suggestion
        d_dumpState(initData(&d_dumpState, false, "dumpState", "Dump state vectors at each time step of the simulation"))
```

2024-04-29 13:28 UTC, alxbilger commented on Sofa/Component/Setting/src/sofa/component/setting/StatsSetting.cpp
> +    , d_exportState(initData(&d_exportState, false, "d_exportState", "Create GNUPLOT files with the positions, velocities and forces of all the simulated objects of the scene"))
```suggestion
    , d_exportState(initData(&d_exportState, false, "exportState", "Create GNUPLOT files with the positions, velocities and forces of all the simulated objects of the scene"))
```

2024-05-07 09:40 UTC, alxbilger approved these changes

2024-05-07 09:40 UTC, fredroy approved these changes

2024-05-07 09:42 UTC, bakpaul commented on Sofa/Component/Setting/src/sofa/component/setting/SofaDefaultPathSetting.cpp
> +        d_gnuplotPath(initData(&d_gnuplotPath, "d_gnuplotPath", "Path where will be saved the gnuplot files"))
```suggestion
        d_gnuplotPath(initData(&d_gnuplotPath, "gnuplotPath", "Path where will be saved the gnuplot files"))
```

2024-05-07 10:53 UTC, lamriaimen commented
[ci-build][with-all-tests]

2024-05-13 07:01 UTC, fredroy approved these changes

2024-05-13 08:12 UTC, merged