[Topology] Rename Data
sofa-framework/sofa pull request #4683
Opened 2024-04-26 13:27 UTC by lamriaimen

According to the guidelines

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-04-29 05:07 UTC, fredroy commented
[ci-build][with-all-tests]

2024-04-29 09:38 UTC, alxbilger commented
[ci-build][with-all-tests]

2024-04-29 10:47 UTC, lamriaimen commented
[ci-build][with-all-tests]

2024-04-29 13:32 UTC, alxbilger requested changes

2024-04-29 13:32 UTC, alxbilger commented on Sofa/Component/IO/Mesh/src/sofa/component/io/mesh/VoxelGridLoader.cpp
> +      idxInRegularGrid(initData(&idxInRegularGrid,"d_idxInRegularGrid","indices of the hexa in the grid.")),
```suggestion
      idxInRegularGrid(initData(&idxInRegularGrid,"idxInRegularGrid","indices of the hexa in the grid.")),
```
and you did not renamed the Data...

2024-04-29 13:54 UTC, bakpaul requested changes

2024-04-29 13:54 UTC, bakpaul commented on Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/DynamicSparseGridTopologyContainer.cpp
>  {
Please, review all data factory name. e.g. : `    , d_valuesIndexedInRegularGrid(initData (&d_valuesIndexedInRegularGrid, sofa::type::vector<unsigned char>(), "d_valuesIndexedInRegularGrid", "values indexed in the Regular Grid" ) )` --> the third parameter **should not be modified**

2024-04-29 13:54 UTC, bakpaul commented on Sofa/Component/Topology/Container/Dynamic/src/sofa/component/topology/container/dynamic/MultilevelHexahedronSetTopologyContainer.cpp
> +      hexaIndexInRegularGrid(initData(&hexaIndexInRegularGrid,"d_idxInRegularGrid","indices of the hexa in the grid.")),
```suggestion
      hexaIndexInRegularGrid(initData(&hexaIndexInRegularGrid,"idxInRegularGrid","indices of the hexa in the grid.")),
```

2024-04-29 13:54 UTC, bakpaul commented on Sofa/Component/Topology/Mapping/src/sofa/component/topology/mapping/SubsetTopologicalMapping.cpp
>  {
Please here also, remove all modification of factory data name.

2024-05-17 03:40 UTC, fredroy commented
[ci-build][with-all-tests]

2024-05-22 10:00 UTC, alxbilger commented
[ci-build][with-all-tests]

2024-05-22 10:00 UTC, alxbilger commented
Note that there are still Data variables that are not been renamed in `Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridTopology.h`

2024-05-22 12:25 UTC, bakpaul approved these changes

2024-05-22 23:47 UTC, fredroy approved these changes

2024-05-22 23:48 UTC, fredroy commented
> Note that there are still Data variables that are not been renamed in `Sofa/Component/Topology/Container/Grid/src/sofa/component/topology/container/grid/SparseGridTopology.h`

You intend to rename them in this PR, or should we merge as it is ?

2024-05-24 07:51 UTC, merged