[Visual] Rename Data
sofa-framework/sofa pull request #4684
Opened 2024-04-26 14:59 UTC by lamriaimen

According to the guidelines

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-04-29 09:42 UTC, alxbilger commented
[ci-build][with-all-tests]

2024-04-29 13:36 UTC, alxbilger requested changes

2024-04-29 13:36 UTC, alxbilger commented on Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.cpp
> +    , m_vtexcoords(initData(&d_vtexcoords, "texcoords", "coordinates of the texture"))
```suggestion
```

2024-04-29 13:36 UTC, alxbilger commented on Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.cpp
> +    , m_vtangents (initData   (&d_vtangents, "tangents", "tangents for normal mapping"))
```suggestion
```

2024-04-29 13:36 UTC, alxbilger commented on Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.cpp
> +    , m_vbitangents(initData   (&d_vbitangents, "bitangents", "tangents for normal mapping"))
```suggestion
```

2024-04-29 13:36 UTC, alxbilger commented on Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.cpp
> +    , m_edges(initData   (&d_edges, "edges", "edges of the model"))
```suggestion
```

2024-04-29 13:36 UTC, alxbilger commented on Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.cpp
> +    , m_triangles(initData   (&d_triangles, "triangles", "triangles of the model"))
```suggestion
```

2024-04-29 13:36 UTC, alxbilger commented on Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.cpp
> +    , m_quads  (initData   (&d_quads, "quads", "quads of the model"))
```suggestion
```

2024-04-29 13:36 UTC, alxbilger commented on Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.cpp
>      m_vnormals      .setGroup("Vector");
Not d_vnormals?

2024-04-29 13:56 UTC, bakpaul requested changes

2024-04-29 13:56 UTC, bakpaul commented on Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.cpp
> +    , d_srgbTexturing		(initData	(&d_srgbTexturing, (bool) false, "d_srgbTexturing", "When sRGB rendering is enabled, is the texture in sRGB colorspace?"))
```suggestion
    , d_srgbTexturing		(initData	(&d_srgbTexturing, (bool) false, "srgbTexturing", "When sRGB rendering is enabled, is the texture in sRGB colorspace?"))
```

2024-04-30 13:07 UTC, lamriaimen commented on Sofa/Component/Visual/src/sofa/component/visual/VisualModelImpl.cpp
>      m_vnormals      .setGroup("Vector");
well m_vnormals is a variable that belongs to Sofa/framework/Core/src/sofa/core/visual/VisualState.h

2024-05-16 00:52 UTC, fredroy commented
[ci-build][with-all-tests]

2024-05-22 23:52 UTC, fredroy approved these changes

2024-05-22 23:52 UTC, fredroy commented on Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/TriangleModel.h
> +     * @brief d_triangles
```suggestion
     * @brief m_triangles
```

2024-05-22 23:52 UTC, fredroy commented on Sofa/Component/Visual/src/sofa/component/visual/BaseCamera.h
> +	Data<bool> d_fixedLookAtPoint; ///< keep the lookAt point always fixed
```suggestion
    Data<bool> d_fixedLookAtPoint; ///< keep the lookAt point always fixed
```

2024-05-24 09:15 UTC, alxbilger approved these changes

2024-05-24 10:57 UTC, fredroy approved these changes

2024-05-24 13:38 UTC, merged