Sofa.constraint
sofa-framework/sofa pull request #4696
Opened 2024-04-29 15:18 UTC by lamriaimen

According to the guidelines

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-04-29 15:30 UTC, lamriaimen commented
[ci-build][with-all-tests]

2024-05-23 00:02 UTC, fredroy requested changes

2024-05-23 00:02 UTC, fredroy commented on Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedRotationProjectiveConstraint.h
> +    Data< bool > d_FixedZRotation; ///< Prevent Rotation around Z axis
```suggestion
    Data< bool > d_fixedXRotation; ///< Prevent Rotation around X axis
    Data< bool > d_fixedYRotation; ///< Prevent Rotation around Y axis
    Data< bool > d_fixedZRotation; ///< Prevent Rotation around Z axis
```
The guidelines say that it should be lowerCamelCase ([N4])

2024-05-23 00:02 UTC, fredroy commented on Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedRotationProjectiveConstraint.inl
> +          FixedZRotation.setParent(&d_FixedZRotation);
```suggestion
      d_fixedXRotation(initData(&d_fixedXRotation, false, "FixedXRotation", "Prevent Rotation around X axis")),
      d_fixedYRotation(initData(&d_fixedYRotation, false, "FixedYRotation", "Prevent Rotation around Y axis")),
      d_fixedZRotation(initData(&d_fixedZRotation, false, "FixedZRotation", "Prevent Rotation around Z axis"))
{
          FixedXRotation.setParent(&d_fixedXRotation);
          FixedYRotation.setParent(&d_fixedYRotation);
          FixedZRotation.setParent(&d_fixedZRotation);
```

2024-05-23 00:02 UTC, fredroy commented on Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedRotationProjectiveConstraint.inl
> +        if (d_FixedXRotation.getValue() == true){
```suggestion
        if (d_fixedXRotation.getValue() == true){
```

2024-05-23 00:02 UTC, fredroy commented on Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedRotationProjectiveConstraint.inl
> +        if (d_FixedYRotation.getValue() == true){
```suggestion
        if (d_fixedYRotation.getValue() == true){
```

2024-05-23 00:02 UTC, fredroy commented on Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/FixedRotationProjectiveConstraint.inl
> +        if (d_FixedZRotation.getValue() == true){
```suggestion
        if (d_fixedZRotation.getValue() == true){
```

2024-05-24 10:59 UTC, fredroy approved these changes

2024-05-27 00:01 UTC, merged