[all] Update data comments
sofa-framework/sofa pull request #4751
Opened 2024-05-21 18:54 UTC by hugtalbot

In the context of the documentation improvement, and towards the automation of its generation, here is a first wide clean PR.

Replace #2751 

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-05-22 08:53 UTC, alxbilger requested changes

2024-05-22 08:53 UTC, alxbilger commented on Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/BaseProximityIntersection.cpp
> +    : d_alarmDistance(initData(&d_alarmDistance, 1.0_sreal, "alarmDistance", "Distance above which the intersection computations ignores the promixity pair. This distance can also be used in some bro
```suggestion
    : d_alarmDistance(initData(&d_alarmDistance, 1.0_sreal, "alarmDistance", "Distance above which the intersection computations ignores the promixity pair. This distance can also be used in some broad phase algorithms to reduce the search area"))
```

2024-05-22 08:53 UTC, alxbilger commented on Sofa/Component/Collision/Detection/Intersection/src/sofa/component/collision/detection/intersection/BaseProximityIntersection.cpp
> +    : d_alarmDistance(initData(&d_alarmDistance, 1.0_sreal, "alarmDistance", "Distance above which the intersection computations ignores the promixity pair. This distance can also be used in some bro
to report also in the header

2024-05-22 08:53 UTC, alxbilger commented on Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/SphereModel.h
> +    Data< SReal > d_defaultRadius; ///< Default radius (default=1.0)
```suggestion
    Data< SReal > d_defaultRadius; ///< Default radius
```

2024-05-22 08:53 UTC, alxbilger commented on Sofa/Component/Collision/Geometry/src/sofa/component/collision/geometry/SphereModel.inl
> +    , d_defaultRadius(initData(&d_defaultRadius, (SReal)(1.0), "radius", "Default radius (default=1.0)"))
```suggestion
    , d_defaultRadius(initData(&d_defaultRadius, (SReal)(1.0), "radius", "Default radius"))
```

2024-05-27 07:07 UTC, alxbilger requested changes

2024-05-27 07:07 UTC, alxbilger commented on Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/BilateralLagrangianConstraint.inl
> +    , m2(initData(&m2, "second_point","index of the constraint on the second model (object2)"))
I don't understand why you added `object1` and `object2` here. What information does it add?

2024-05-27 07:07 UTC, alxbilger commented on Sofa/Component/Controller/src/sofa/component/controller/Controller.h
> +    Data< bool > d_handleEventTriggersUpdate; ///< Event handling frequency controls the controller update frequency
I am not comfortable with this sentence

2024-05-27 07:07 UTC, alxbilger commented on applications/plugins/Geomagic/src/Geomagic/GeomagicDriver.cpp
> +    , d_forceScale(initData(&d_forceScale, 1.0, "forceScale", "Default forceScale applied to the force feedback"))
```suggestion
    , d_forceScale(initData(&d_forceScale, 1.0, "forceScale", "Default force scale applied to the force feedback"))
```

2024-05-27 07:07 UTC, alxbilger commented on applications/plugins/Sensable/NewOmniDriver.cpp
> +    : forceScale(initData(&forceScale, 1.0, "forceScale","Default forceScale applied to the force feedback"))
```suggestion
    : forceScale(initData(&forceScale, 1.0, "forceScale","Default force scale applied to the force feedback"))
```

2024-05-27 07:07 UTC, alxbilger commented on applications/plugins/Sensable/OmniDriver.cpp
> +    , forceScale(initData(&forceScale, 1.0, "forceScale","Default forceScale applied to the force feedback"))
```suggestion
    , forceScale(initData(&forceScale, 1.0, "forceScale","Default force scale applied to the force feedback"))
```

2024-05-27 07:07 UTC, alxbilger commented on applications/plugins/SensableEmulation/NewOmniDriverEmu.cpp
> +    : forceScale(initData(&forceScale, 1.0, "forceScale","Default forceScale applied to the force feedback"))
```suggestion
    : forceScale(initData(&forceScale, 1.0, "forceScale","Default force scale applied to the force feedback"))
```

2024-05-27 07:07 UTC, alxbilger commented on applications/plugins/SensableEmulation/OmniDriverEmu.cpp
> +    : forceScale(initData(&forceScale, 1.0, "forceScale","Default forceScale applied to the force feedback"))
```suggestion
    : forceScale(initData(&forceScale, 1.0, "forceScale","Default force scale applied to the force feedback"))
```

2024-05-27 07:07 UTC, alxbilger commented on applications/plugins/SofaHAPI/SofaHAPIHapticsDevice.cpp
> +			, forceScale(initData(&forceScale, 1.0, "forceScale","Default forceScale applied to the force feedback"))
```suggestion
			, forceScale(initData(&forceScale, 1.0, "forceScale","Default force scale applied to the force feedback"))
```

2024-06-05 08:59 UTC, bakpaul approved these changes

2024-06-05 08:59 UTC, alxbilger approved these changes

2024-06-05 09:00 UTC, merged