Sofa.component
sofa-framework/sofa pull request #4771
Opened 2024-06-07 11:32 UTC by lamriaimen

According to the guidelines
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-06-07 11:35 UTC, lamriaimen commented
[ci-build][with-all-tests]

2024-06-19 08:17 UTC, alxbilger commented
To do: update the deprecation dates

2024-06-20 09:15 UTC, alxbilger commented on Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/TrianglePressureForceField.h
> +    core::objectmodel::lifecycle::DeprecatedData d_dmax{ this, "v24.06", "v24.12", "dmax", "Plan selection using normal, dmin, dmax has been removed. Triangles should be selected using an Engine.Sele
I am not sure you should rename the `DeprecatedData` type

2024-06-20 09:39 UTC, alxbilger requested changes

2024-06-20 09:39 UTC, alxbilger commented on Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/TrianglePressureForceField.inl
> +        my_subset[i].force= d_pressure.getValue() * my_subset[i].area;
This should not be here!

2024-06-20 09:40 UTC, alxbilger commented on Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/TrianglePressureForceField.inl
> +    template<class DataTypes>
Be careful with the indentations

2024-06-21 06:57 UTC, alxbilger commented
Thanks for vigilance @hugtalbot.

@lamriaimen as you can see in the following report, most of the deprecation warnings are in targets that you probably did not enable. I suggest that you activate in CMake "internal" plugins (the ones provided with the sources in `applications/plugins`), and I take care of the external plugins (such as ModelOrderReduction).

https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/PR-4771/CI_CONFIG=fedora_clang,CI_PLUGINS=options,CI_TYPE=release/13/FullBuildWarnings-Clang/category.2119183113/

2024-06-26 16:05 UTC, bakpaul requested changes

2024-06-26 16:05 UTC, bakpaul commented on Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedronFEMForceField.inl
> +    , d_drawHeterogeneousTetra(initData(&d_drawHeterogeneousTetra, false, "d_drawHeterogeneousTetra", "Draw Heterogeneous Tetra in different color"))
```suggestion
    , d_drawHeterogeneousTetra(initData(&d_drawHeterogeneousTetra, false, "drawHeterogeneousTetra", "Draw Heterogeneous Tetra in different color"))
```

2024-06-26 16:05 UTC, bakpaul commented on Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/QuadBendingSprings.inl
> +    , d_localRange(initData(&d_localRange, type::Vec<2,int>(-1, -1), "d_localRange", "optional range of local DOF indices. Any computation involving only indices outside of this range are discarded (
```suggestion
    , d_localRange(initData(&d_localRange, type::Vec<2,int>(-1, -1), "localRange", "optional range of local DOF indices. Any computation involving only indices outside of this range are discarded (useful for parallelization using mesh partitionning)" ) )
```

2024-06-26 16:05 UTC, bakpaul commented on Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/TriangularBendingSprings.inl
> +    , d_edgeInfo(initData(&d_edgeInfo, "d_edgeInfo", "Internal edge data"))
```suggestion
    , d_edgeInfo(initData(&d_edgeInfo, "edgeInfo", "Internal edge data"))
```

2024-06-26 16:05 UTC, bakpaul commented on Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/TriangularBiquadraticSpringsForceField.inl
> +    : d_triangleInfo(initData(&d_triangleInfo, "d_triangleInfo", "Internal triangle data"))
```suggestion
    : d_triangleInfo(initData(&d_triangleInfo, "triangleInfo", "Internal triangle data"))
```

2024-06-26 16:05 UTC, bakpaul commented on Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/TriangularBiquadraticSpringsForceField.inl
> +    , d_edgeInfo(initData(&d_edgeInfo, "d_edgeInfo", "Internal edge data"))
```suggestion
    , d_edgeInfo(initData(&d_edgeInfo, "edgeInfo", "Internal edge data"))
```

2024-06-26 16:05 UTC, bakpaul commented on Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/TriangularQuadraticSpringsForceField.inl
> +    , d_triangleInfo(initData(&d_triangleInfo, "d_triangleInfo", "Internal triangle data"))
```suggestion
    , d_triangleInfo(initData(&d_triangleInfo, "triangleInfo", "Internal triangle data"))
```

2024-06-26 16:05 UTC, bakpaul commented on Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/TriangularQuadraticSpringsForceField.inl
> +    , d_edgeInfo(initData(&d_edgeInfo, "d_edgeInfo", "Internal edge data"))
```suggestion
    , d_edgeInfo(initData(&d_edgeInfo, "edgeInfo", "Internal edge data"))
```

2024-06-26 16:05 UTC, bakpaul commented on Sofa/Component/SolidMechanics/TensorMass/src/sofa/component/solidmechanics/tensormass/TetrahedralTensorMassForceField.inl
> +    , edgeInfo(initData(&edgeInfo, "d_edgeInfo", "Internal edge data"))
```suggestion
    , edgeInfo(initData(&edgeInfo, "edgeInfo", "Internal edge data"))
```

2024-06-26 16:05 UTC, bakpaul commented on Sofa/Component/SolidMechanics/TensorMass/src/sofa/component/solidmechanics/tensormass/TriangularTensorMassForceField.inl
> +    : edgeInfo(initData(&edgeInfo, "d_edgeInfo", "Internal edge data"))
```suggestion
    : edgeInfo(initData(&edgeInfo, "edgeInfo", "Internal edge data"))
```

2024-06-26 16:07 UTC, bakpaul commented
I tried to look everywhere and spotted the same mistake as in the other PRs : you sometimes changed the factory name. It might still remain errors. Better check it twice @lamriaimen 

By the way you seem to have messed up a bit with the edge info data in the Tensor forcefiles, you have modified the comments but not the actual data, please take a look there. 

Except for those chages, the PR seems ok to me.

2024-06-28 08:38 UTC, bakpaul reviewed
Still some wrong data names...

2024-06-28 08:38 UTC, bakpaul commented on Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/FastTetrahedralCorotationalForceField.inl
> +    , d_edgeInfo(initData(&d_edgeInfo, "d_edgeInfo", "Internal edge data"))
```suggestion
    , d_edgeInfo(initData(&d_edgeInfo, "edgeInfo", "Internal edge data"))
```

2024-06-28 08:38 UTC, bakpaul commented on Sofa/Component/SolidMechanics/TensorMass/src/sofa/component/solidmechanics/tensormass/TriangularTensorMassForceField.inl
> +    : d_edgeInfo(initData(&d_edgeInfo, "d_edgeInfo", "Internal edge data"))
```suggestion
    : d_edgeInfo(initData(&d_edgeInfo, "edgeInfo", "Internal edge data"))
```

2024-06-28 09:15 UTC, lamriaimen commented
Hey @bakpaul In the renaming data process I use the Refactor option in Clion (IDE), sometimes it does this that it even renames the data in the double quotes even though I specify that the renaming should only be for the code.sorry for that I rechecked all the code base even for the PRS that got merged I think now the code is clean

2024-06-28 10:27 UTC, bakpaul commented
Ok I get that. Without such tool it would be difficult to make that kind of huge refacto anyway...
If you've added the two last modifications I asked then it is ready for me ! Good job !

2024-06-28 10:28 UTC, bakpaul approved these changes

2024-07-01 05:00 UTC, merged

2024-07-03 08:30 UTC, alxbilger commented
@lamriaimen Can you take a look at `FastTetrahedralCorotationalForceField::tetrahedronInfo`. I think you used the wrong type compared to `d_tetrahedronInfo`