[all] Clean some warnings
sofa-framework/sofa pull request #4805
Opened 2024-07-02 15:29 UTC by hugtalbot

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-07-02 23:44 UTC, fredroy commented
[ci-build][with-all-tests]

2024-07-03 07:30 UTC, alxbilger requested changes
Almost ready for me

2024-07-03 07:30 UTC, alxbilger commented on applications/projects/SofaPhysicsAPI/src/SofaPhysicsAPI/SofaPhysicsSimulation.cpp
> +    [[maybe_unused]] double xForeground, yForeground, zForeground, xBackground, yBackground, zBackground;
Instead of adding `[[maybe_unused]]`, you could declare those variables below (after the return), close to where the variables are used.

2024-07-16 08:11 UTC, bakpaul approved these changes

2024-07-17 13:47 UTC, merged