[GUI] Clean warning from GUI at start
sofa-framework/sofa pull request #4811
Opened 2024-07-04 14:45 UTC by hugtalbot

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-07-04 18:44 UTC, alxbilger requested changes
Thanks for the PR!

2024-07-04 18:44 UTC, alxbilger commented on CHANGELOG.md
>  # SOFA Changelog
File to remove from the pr

2024-07-04 20:25 UTC, alxbilger approved these changes

2024-07-05 06:16 UTC, fredroy approved these changes

2024-07-05 06:16 UTC, merged