[Core] Add RenamedData component for data symbol renaming
sofa-framework/sofa pull request #4814
Opened 2024-07-05 14:18 UTC by bakpaul

The current lifecycle mechanism when renaming the symbol of a Data object is depreciating the old data and setting the new data as a parent of the old one : 
`_oldData.setParent(d_newData)`

This is not 100% working, because a setValue on the old data will not be applied on the new one, because a child is only link to the parent by a callback (and not a _feedForward_).

This means that a lot of the recent refactoring pr renaming data symbols are breaking. This pr aims at solving this, and is meant to be applied to all the recent pr to solve this issue. 
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-07-16 08:04 UTC, bakpaul commented
[ci-build][with-all-tests]

2024-07-17 14:42 UTC, bakpaul commented
Comments from SOFA-dev meeting have been applied. Wait for merge to make a full refacto of the compat layer of previous PR.

2024-07-17 14:42 UTC, bakpaul commented
[ci-build][with-all-tests]

2024-07-17 14:50 UTC, alxbilger requested changes

2024-07-17 14:50 UTC, alxbilger commented on Sofa/framework/Core/src/sofa/core/objectmodel/RenamedData.h
> +    Data<T>* m_originalData;
```suggestion
    Data<T>* m_originalData { nullptr };
```

2024-07-25 00:38 UTC, merged