[Helper] Retrieve the current user local configuration directory
sofa-framework/sofa pull request #4875
Opened 2024-08-01 05:11 UTC by fredroy

First steps for a consistent, uniformed and centralized configuration storage.

This PR adds the ability to retrieve the current local config folder for the user. 

These return respectively (local account is `fred`):
 - Linux:
```
getUserLocalDirectory(): /home/fred/.config
getSofaUserLocalDirectory(): /home/fred/.config/SOFA
```

 - macOS:
 ```
getUserLocalDirectory(): /Users/fred/Library/Application Support
getSofaUserLocalDirectory(): /Users/fred/Library/Application Support/SOFA
```
 - Windows:
 ```
getUserLocalDirectory(): C:/Users/Fred/AppData/Local
getSofaUserLocalDirectory(): C:/Users/Fred/AppData/Local/SOFA
```

`getSofaUserLocalDirectory()` creates also the directory if it is not created yet

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-08-01 08:46 UTC, alxbilger requested changes
Great!

I think you should not use `std::filesystem` directly. Some users still rely on old versions of GCC (even if we don't support them officially) when `filesystem` was in the `experimental` namespace. I suggest you use the `sofa::FileSystem` functions.

2024-08-01 08:46 UTC, alxbilger commented on Sofa/framework/Helper/src/sofa/helper/Utils.cpp
> +        });
Check if you can use `sofa::helper::narrowString` here

2024-08-01 08:46 UTC, alxbilger commented on Sofa/framework/Helper/src/sofa/helper/Utils.cpp
> +        const std::filesystem::path localDirPath = getUserLocalDirectory() + "/SOFA";
You can use `FileSystem::append` here, or `std::filesystem::append`, or `std::filesystem::path{getUserLocalDirectory()} / "SOFA"`

2024-08-01 08:47 UTC, alxbilger commented
Could you think about a pertinent unit test?

2024-08-06 05:01 UTC, fredroy commented
> Could you think about a pertinent unit test?

I made some but it is possible that it fails, as (normally) CI jobs run with a unprivileged user which can have no home-directory defined, AFAIK (on Linux at least)

2024-08-07 09:05 UTC, alxbilger approved these changes

2024-08-07 12:22 UTC, fredroy commented
[ci-build]

2024-08-07 14:14 UTC, fredroy commented
[ci-build]

2024-08-14 10:21 UTC, merged