Sofa.mouse op
sofa-framework/sofa pull request #4880
Opened 2024-08-01 13:57 UTC by lamriaimen

This pull request enhances the Operation::createPerformer function to provide more detailed error messages when it fails to create an InteractionPerformer. The function now includes precise diagnostic messages that indicate where the failure occurred, improving the ease of debugging and maintaining the code.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-08-01 14:21 UTC, alxbilger approved these changes

2024-08-02 13:00 UTC, epernod commented on Sofa/GUI/Common/src/sofa/gui/common/MouseOperations.cpp
> +        msg_error("MouseOperation") << "Failed to create InteractionPerformer: Interaction object is null.";
```suggestion
        msg_error("MouseOperation") << "Failed to create InteractionPerformer: ComponentMouseInteraction object from input PickHandler is null.";
```

2024-08-02 13:00 UTC, epernod commented on Sofa/GUI/Common/src/sofa/gui/common/MouseOperations.cpp
> +        msg_error("MouseOperation") << "Failed to create InteractionPerformer: MouseInteractor is null.";
```suggestion
        msg_error("MouseOperation") << "Failed to create InteractionPerformer: MouseInteractor inside input PickHandler  is null.";
```

2024-08-02 13:04 UTC, epernod approved these changes

2024-08-02 14:33 UTC, lamriaimen commented
[ci-build][with-all-tests]

2024-08-02 16:40 UTC, epernod commented
you have some compilation error... not sure if it is relevant...
could you double check before merging

2024-08-02 16:42 UTC, epernod requested changes
fix should be the problem

2024-08-02 16:42 UTC, epernod commented on Sofa/GUI/Common/src/sofa/gui/common/MouseOperations.cpp
> +    const InteractionPerformer *performer = InteractionPerformer::InteractionPerformerFactory::getInstance()->createObject(type, mouseInteractor);
```suggestion
    InteractionPerformer *performer = InteractionPerformer::InteractionPerformerFactory::getInstance()->createObject(type, mouseInteractor);
```

2024-08-02 22:18 UTC, merged