[Mass,MechanicalLoad] Use enumeration to clarify the code
sofa-framework/sofa pull request #4918
Opened 2024-08-13 10:02 UTC by hugtalbot

Based on #3927 this PR aims at :
- Use enumeration to clarify the code for initialization methods in ConstantForceField and UniformMass
- some code cleanings : starting init as Valid, avoid calling isComponentValid while init(), check isComponentValid prior to run-time functions 

Meaningful commit : https://github.com/sofa-framework/sofa/commit/3b1cc06330ff4c3ea30bfd0fcff7ed69031976cf

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-08-13 12:10 UTC, fredroy requested changes

2024-08-13 12:10 UTC, fredroy commented on Sofa/Component/Mass/src/sofa/component/mass/UniformMass.h
> +
I am surprised that there are no guidelines for enum types in the doc. But generally:

- the values should be UpperCamelCase or UPPERCASE
- `enum class` is recommended: https://stackoverflow.com/questions/18335861/why-is-enum-class-considered-safer-to-use-than-plain-enum

2024-08-13 13:28 UTC, fredroy commented on Sofa/Component/Mass/src/sofa/component/mass/UniformMass.h
> +
Seems the UPPERCASE is the most used case in the codebase, indeed.
But I dont see why you put a `= 0`. (and add a new line for the open curling brace 🫢)

2024-08-13 13:42 UTC, fredroy commented
[ci-build][with-all-tests]

2024-08-13 13:50 UTC, fredroy requested changes

2024-08-13 13:50 UTC, fredroy commented on Sofa/Component/MechanicalLoad/src/sofa/component/mechanicalload/ConstantForceField.h
> +        TOTALFORCE ,
```suggestion
        TOTALFORCE,
```
🫢

2024-08-19 23:13 UTC, fredroy commented
> This change makes all tests using the ConstantForceField fail due to a bug in SingleStateAccessor solved in #4917 . To solve the tests, merge #4917 first and rebase. Then, the PR should be fine

#4917 has been integrated (not rebased due to anterior conflicts) and there are still errors because of 
`No input force has been set. Please define one of both Data: forces or totalForce` 🥲

I guess there is an error of logics (if, else, etc) somewhere

2024-08-20 12:15 UTC, bakpaul commented on Sofa/Component/Mass/src/sofa/component/mass/UniformMass.h
> +    InitMethod m_initMethod = InitMethod::TOTALMASS;
Default value in the class declaration is not really wanted.

2025-04-01 11:02 UTC, closed without merging