[Engine] Add draw method in NearestPointROI
sofa-framework/sofa pull request #4944
Opened 2024-08-28 22:32 UTC by epernod

just for quick debugging visualization

![NearestPointROI_00000001](https://github.com/user-attachments/assets/cce22e5c-263b-4ba5-8d39-050963967f30)

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-08-29 05:08 UTC, fredroy requested changes

2024-08-29 05:08 UTC, fredroy commented on Sofa/Component/Engine/Select/src/sofa/component/engine/select/NearestPointROI.inl
> +
```suggestion
    const auto stateLifeCycle = vparams->drawTool()->makeStateLifeCycle();
```

2024-08-29 05:08 UTC, fredroy commented on Sofa/Component/Engine/Select/src/sofa/component/engine/select/NearestPointROI.inl
> +        colors.emplace_back(sofa::type::RGBAColor(SReal(rand()) / RAND_MAX, SReal(rand()) / RAND_MAX, SReal(rand()) / RAND_MAX, 1._sreal));
```suggestion
        vertices.emplace_back(xId1[0], xId1[1], xId1[2]);
        vertices.emplace_back(xId2[0], xId2[1], xId2[2]);
        colors.emplace_back(SReal(rand()) / RAND_MAX, SReal(rand()) / RAND_MAX, SReal(rand()) / RAND_MAX, 1._sreal);
```

2024-08-29 05:08 UTC, fredroy commented on Sofa/Component/Engine/Select/src/sofa/component/engine/select/NearestPointROI.inl
> +        colors.emplace_back(sofa::type::RGBAColor(SReal(rand()) / RAND_MAX, SReal(rand()) / RAND_MAX, SReal(rand()) / RAND_MAX, 1._sreal));
And I dont understand why rand() ? 😶‍🌫️
It will be called 3 times for every spring at every **draw** steps.

If rand is needed, FYI they are also already some generators in sofa::helper (sofa::helper::random.h and sofa::helper::RandomGenerator.h)

2024-08-30 14:16 UTC, epernod commented on Sofa/Component/Engine/Select/src/sofa/component/engine/select/NearestPointROI.inl
> +        colors.emplace_back(sofa::type::RGBAColor(SReal(rand()) / RAND_MAX, SReal(rand()) / RAND_MAX, SReal(rand()) / RAND_MAX, 1._sreal));
This is just to have different color per pair to differentiate them. 
I push a more simple version without random.

2024-08-30 14:16 UTC, epernod commented on Sofa/Component/Engine/Select/src/sofa/component/engine/select/NearestPointROI.inl
> +        colors.emplace_back(sofa::type::RGBAColor(SReal(rand()) / RAND_MAX, SReal(rand()) / RAND_MAX, SReal(rand()) / RAND_MAX, 1._sreal));
![image](https://github.com/user-attachments/assets/a3d4f3c0-604e-48a7-a2b9-3f29b4970ba1)

2024-08-30 14:31 UTC, alxbilger reviewed
For distinct colors, you can also use `ColorMap`

2024-08-30 14:31 UTC, alxbilger commented on Sofa/Component/Engine/Select/src/sofa/component/engine/select/NearestPointROI.inl
> +        colors.emplace_back(sofa::type::RGBAColor(col, 1._sreal, 0.5_sreal, 1._sreal));
```suggestion
        colors.emplace_back(col, 1.f, 0.5f, 1f);
```
`RGBAColor` is composed of  `float`

2024-08-30 14:31 UTC, alxbilger commented on Sofa/Component/Engine/Select/src/sofa/component/engine/select/NearestPointROI.inl
> +        vertices.emplace_back(sofa::type::Vec3(xId2[0], xId2[1], xId2[2]));
```suggestion
        vertices.emplace_back(xId1[0], xId1[1], xId1[2]);
        vertices.emplace_back(xId2[0], xId2[1], xId2[2]);
```

2024-08-30 14:31 UTC, alxbilger commented on Sofa/Component/Engine/Select/src/sofa/component/engine/select/NearestPointROI.inl
> +        const SReal col = SReal(i) / nbrIds;
```suggestion
        const float col = static_cast<float>(i) / nbrIds;
```

2024-08-30 14:31 UTC, alxbilger commented on Sofa/Component/Engine/Select/src/sofa/component/engine/select/NearestPointROI.inl
> +    const SReal nbrIds = SReal(indices1.size());
```suggestion
    const float nbrIds = static_cast<float>(indices1.size());
```

2024-09-03 08:09 UTC, bakpaul approved these changes

2024-09-04 12:02 UTC, alxbilger requested changes

2024-09-04 12:02 UTC, alxbilger commented on Sofa/Component/Engine/Select/src/sofa/component/engine/select/NearestPointROI.inl
> +        colors.emplace_back(col, 1.f, 0.5f, 1f);
```suggestion
        colors.emplace_back(col, 1.f, 0.5f, 1.f);
```

2024-09-05 13:50 UTC, alxbilger approved these changes

2024-09-06 02:29 UTC, fredroy approved these changes

2024-09-06 02:30 UTC, merged