Inf 2024 14 draw coro von mises
sofa-framework/sofa pull request #4945
Opened 2024-08-28 22:33 UTC by epernod

Similar to TetrahedronFEMForceField, compute von mises per element and add option to draw it.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-09-02 23:29 UTC, fredroy requested changes

2024-09-02 23:29 UTC, fredroy commented on Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.h
> +    sofa::helper::ColorMap* m_VonMisesColorMap;
```suggestion
    Data<type::vector<Real> > d_vonMisesPerNode; ///< von Mises Stress per node
    
    sofa::helper::ColorMap* m_vonMisesColorMap;
```
I guess this is a copy-paste from the other file 🫢but it is nice to have consistency

2024-09-02 23:29 UTC, fredroy commented on Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.inl
> +    const bool canInvert = type::invertMatrix(tetrahedronInf[i].elemShapeFun, matVert);
```suggestion
    [[maybe_unused]] const bool canInvert = type::invertMatrix(tetrahedronInf[i].elemShapeFun, matVert);
```

2024-09-02 23:29 UTC, fredroy commented on Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.inl
> +        //tetraInfo.rotation.transpose(R_0_2);
```suggestion
```

2024-09-02 23:29 UTC, fredroy commented on Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.inl
> +        std::vector< type::Vec3 > points[4];
You could reserve the memory beforehand as the size seems computable

2024-09-03 08:39 UTC, damienmarchal commented
To me adding more and more hard coded drawing function by copy-pasting other's drawing function in every components is not desirable. 

I see two better solutions: 
1) the drawing code & related datafield should at least be moved in a separated c++ object to factor rendering & UX. 
2)  the drawing code & related datafields should be in a separated sofa component so they can be compose in the scene.

2024-09-03 08:41 UTC, bakpaul approved these changes

2024-10-27 09:16 UTC, epernod commented on Sofa/Component/SolidMechanics/FEM/Elastic/src/sofa/component/solidmechanics/fem/elastic/TetrahedralCorotationalFEMForceField.inl
> +        std::vector< type::Vec3 > points[4];
I did it but in a new PR I will change that drawing to use directly the drawScaledTetrahedra from drawTools

2024-10-27 10:22 UTC, epernod commented
[ci-build][with-all-tests]

2024-10-29 06:23 UTC, fredroy approved these changes

2024-10-29 06:23 UTC, merged