[Constraint.Projective] Make LinearVelocityProjectiveConstraint work with FreeMotionAL
sofa-framework/sofa pull request #5025
Opened 2024-09-26 08:28 UTC by bakpaul

Implement missing methods to work in FreeMotionAnimationLoop. --> simply took what was implemented in FixedProjectiveConstraint.

Also add a new feature to keep the constraint applied after all the key event have passed

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-10-02 05:35 UTC, fredroy requested changes
I guess a scene test (even better with a regression 🥸) would be welcomed 🫢

2024-10-02 08:40 UTC, alxbilger commented on Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/LinearVelocityProjectiveConstraint.inl
> +        const unsigned int N = Deriv::size();
can be constexpr

2024-11-21 17:21 UTC, bakpaul commented
[ci-builds][with-all-tests]

2024-12-02 12:20 UTC, alxbilger reviewed
I would appreciate a video showing the introduced scenes 😃

2024-12-02 12:20 UTC, alxbilger commented on Sofa/Component/Constraint/Projective/src/sofa/component/constraint/projective/LinearVelocityProjectiveConstraint.inl
> +    SOFA_UNUSED(mparams);
Shouldn't you use `d_continueAfterEnd` and/or `finished` here? If `d_continueAfterEnd` is false and `finished` is true, should the matrix projection be applied?

2024-12-11 12:56 UTC, merged