[SolidMechanics] Apply new factory registration mechanism
sofa-framework/sofa pull request #5027
Opened 2024-09-27 07:12 UTC by fredroy

See
- #4429

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-09-27 07:13 UTC, fredroy commented
[ci-build][with-all-tests]

2024-10-01 16:50 UTC, bakpaul commented on Sofa/Component/SolidMechanics/FEM/src/sofa/component/solidmechanics/fem/init.cpp
> +    factory->registerObjectsFromPlugin("Sofa.Component.SolidMechanics.FEM.HyperElastic");
Missing non uniform ?

2024-10-10 00:18 UTC, fredroy commented on Sofa/Component/SolidMechanics/FEM/src/sofa/component/solidmechanics/fem/init.cpp
> +    factory->registerObjectsFromPlugin("Sofa.Component.SolidMechanics.FEM.HyperElastic");
indeed

2024-10-10 08:55 UTC, epernod requested changes
problem on fedora:
@fredroy 
fedora_clang_options — Build OK. FIXME: 8 units, 0 scene, 88 regressions

2024-10-11 00:33 UTC, fredroy commented
> problem on fedora: @fredroy fedora_clang_options — Build OK. FIXME: 8 units, 0 scene, 88 regressions

done

2024-10-11 08:18 UTC, epernod approved these changes

2024-10-11 08:18 UTC, merged