[Constraint] Apply new factory registration mechanism
sofa-framework/sofa pull request #5052
Opened 2024-10-10 00:24 UTC by fredroy

See
- #4429

[ci-depends-on https://github.com/sofa-framework/SofaPython3/pull/462]

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-10-10 00:25 UTC, fredroy commented
[ci-build][with-all-tests]

2024-10-10 06:09 UTC, fredroy commented
[ci-build][with-all-tests][force-full-build]

2024-10-18 14:10 UTC, alxbilger requested changes

2024-10-18 14:10 UTC, alxbilger commented on Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/StopperLagrangianConstraint.cpp
> +    factory->registerObjects(core::ObjectRegistrationData("TODO-StopperLagrangianConstraint")
```suggestion
    factory->registerObjects(core::ObjectRegistrationData("Lagrangian-based constraint forcing a 1D DoF to be  inside a given range.")
```

2024-10-18 14:10 UTC, alxbilger commented on Sofa/Component/Constraint/Lagrangian/Model/src/sofa/component/constraint/lagrangian/model/UnilateralLagrangianConstraint.cpp
> +    factory->registerObjects(core::ObjectRegistrationData("TODO-UnilateralLagrangianConstraint")
```suggestion
    factory->registerObjects(core::ObjectRegistrationData("Lagrangian-based inequality constraint")
```

2024-10-26 15:59 UTC, epernod approved these changes

2024-10-26 15:59 UTC, merged