[Core] Test for nullptr in force field creation
sofa-framework/sofa pull request #5075
Opened 2024-10-21 12:31 UTC by alxbilger

It crashed if `context` was `nullptr`.

Not sure what to return if `context` is `nullptr`.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-10-22 07:19 UTC, alxbilger commented
[ci-build][with-all-tests]

2024-10-27 11:01 UTC, epernod approved these changes

2024-10-27 11:04 UTC, epernod requested changes
I just checked, and by default:
BaseObject::canCreate(obj, context, arg); returns true:

/// Pre-construction check method called by ObjectFactory.
```
template<class T>
static bool canCreate(T* /*obj*/, BaseContext* /*context*/, BaseObjectDescription* /*arg*/)
{
    return true;
}
```

in your case, even if I guess it is not yet catched. I would return false if context == nullptr

2024-10-27 13:19 UTC, alxbilger commented
Yes, that is why I asked you your opinion about the returned value. I am not convinced of both values

2024-10-28 09:39 UTC, epernod commented
I prefer `false`. 
So probably the component won't be created and the scene might crash at creation or init with your error message. 
Otherwise the crash might happened later. Or worse, it will run with a wrong behavior. The second option is harder to debug.

2024-11-06 18:32 UTC, alxbilger commented
@hugtalbot @epernod let me know what you think of the new version

2024-11-12 16:43 UTC, bakpaul approved these changes

2024-11-14 06:50 UTC, merged