[main] Changes screenshots and config directories location
sofa-framework/sofa pull request #5096
Opened 2024-11-05 17:36 UTC by EulalieCoevoet

The directories `screenshots` and `config` are currently created in the `build` directory of SOFA. When installing the software on a machine, those can end up in a read-only directory. 

To avoid this problem, this PR changes:

On Linux:
- `screenshots` location to: `~/SOFAData/screenshots/`
- `config` location to: `~/.config/SOFA/config/` 

On Windows:
- `screenshots` location to: `~/SOFAData/screenshots/`
- `config` location to: `~/AppData/Local/.config/SOFA/config/` 

On MacOS:
- `screenshots` location to: `~/Library/Application Support/SOFAData/screenshots/`
- `config` location to: `~/Library/Application Support/.config/SOFA/config/` 

These changes have only been tested on Linux. I'm not familiar with MacOS so I don't know what would be the best location.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

2024-11-06 00:25 UTC, fredroy commented on Sofa/framework/Helper/src/sofa/helper/Utils.cpp
> +            homeDir = getpwuid(getuid())->pw_dir;
`getpwuid()` and `getuid()` are POSIX system calls so it is not supported with Win32 API

2024-12-04 09:56 UTC, damienmarchal commented
Hi @EulalieCoevoet 

Thank for the PR. 
It is unclear to me if the choices of directory is the best one. 
I would expect the screenshots to be in the "current" directory (the one from which the application is started. 
If they don't go there... I would have expected something more like:

On Linux:
    screenshots location to: ~/.sofa/screenshots/
    config location to: ~/.sofa/config/SOFA/config/
or
    screenshots location to: ~/.sofa/screenshots/
    config location to: ~/.config/sofa/

On Windows:
    screenshots location to: ~/AppData/Local/sofa/screenshots/
    config location to: ~/AppData/Local/.config/sofa/config/
or 
    screenshots location to: ~/AppData/Local/sofa/screenshots/
    config location to: ~/AppData/Local/sofa/config/

On MacOS:
    screenshots location to: ~/Library/Application Support/sofa/screenshots/
    config location to: ~/Library/Application Support/.config/sofa
 or   
    screenshots location to: ~/Library/Application Support/sofa/screenshots/
    config location to: ~/Library/Application Support/sofa/config/

2024-12-04 10:16 UTC, EulalieCoevoet commented
I'm okay with all your suggestions. If I had to choose, I'll go for:

On Linux:
`~/sofa/screenshots/` (we should not _hide_ this directory)
`~/sofa/config/`

On Windows:
`~/AppData/Local/sofa/screenshots/`
`~/AppData/Local/sofa/config/`

On MacOS:
`~/Library/Application Support/sofa/screenshots/`
`~/Library/Application Support/sofa/config/`

2024-12-16 09:20 UTC, bakpaul commented
Having it in a hidden directory is better in my opinion: for the three other platform, it is kind of hidden by the fact that it is in folders dedicated for such files. Here in linux we are polluting the home of the user. I would then advocate for the use of hidden folder.

2024-12-16 09:38 UTC, alxbilger requested changes
Would it be possible to add tests for `getUserHomeDirectory` and `getSofaDataDirectory` in `Sofa/framework/Helper/test/Utils_test.cpp`?

2024-12-16 09:38 UTC, alxbilger commented on applications/projects/runSofa/Main.cpp
> +    BaseGUI::setScreenshotDirectoryPath(Utils::getSofaDataDirectory() + "/screenshots", true);
```suggestion
    BaseGUI::setConfigDirectoryPath(FileSystem::append(Utils::getSofaUserLocalDirectory(), "config"), true);
    BaseGUI::setScreenshotDirectoryPath(FileSystem::append(Utils::getSofaDataDirectory(), "screenshots"), true);
```
to ensure exactly one directory separator (/).

2024-12-16 09:38 UTC, alxbilger commented on Sofa/framework/Helper/src/sofa/helper/Utils.cpp
> +            return getUserHomeDirectory() + std::string("/.config");
```suggestion
            return FileSystem::append(getUserHomeDirectory(), ".config");
```

2025-01-24 13:47 UTC, EulalieCoevoet commented
Can we run the CI to check the tests?

2025-01-28 10:40 UTC, fredroy commented
[ci-build][with-all-tests]

2025-02-04 09:45 UTC, EulalieCoevoet commented
For the test of getUserHomeDirectory() on Windows. 
Do you know if it should be `J:\jenkins2` or `J:/0` ? Or should I print the results in the CI ?

2025-02-25 14:53 UTC, EulalieCoevoet commented
Can we run the CI to check the tests?

2025-03-12 10:41 UTC, EulalieCoevoet commented
[ci-build][with-all-tests]

2025-03-14 08:45 UTC, EulalieCoevoet commented
[ci-build][with-all-tests]

2025-03-27 09:37 UTC, EulalieCoevoet commented
[ci-build][with-all-tests]

2025-03-28 14:45 UTC, EulalieCoevoet commented
I'm done with the tests. This is ready.

2025-03-31 01:02 UTC, fredroy commented
[ci-build][with-all-tests][force-full-build]

2025-03-31 02:14 UTC, fredroy requested changes

2025-03-31 02:14 UTC, fredroy commented on Sofa/framework/Helper/src/sofa/helper/Utils.cpp
> +    static std::string sofaDataDirectory = FileSystem::cleanPath(FileSystem::findOrCreateAValidPath(
Maybe the error on the linux unit-tests come from the deprecated usage of `findOrCreateAValidPath`?
In any case `findOrCreateAValidPath()` is deprecated and will be removed so it needs to be replaced.

```suggestion
    static std::string sofaDataDirectory = FileSystem::cleanPath(FileSystem::ensureFolderExists(
```

2025-03-31 16:13 UTC, EulalieCoevoet commented
Looks like the home path of the CI is changing, preventing from doing such tests. 
Can I remove the tests ?

2025-04-02 09:05 UTC, bakpaul commented
SOFA-dev metting comments:

The unit test failing outside of the CI is not something we want. The best solution would be to determine the home folder during the build to modify the test accordingly. But in any cases, we can remove this test.  

Failure may come from the fact that Ubuntu is using docker. To be investigated. Scene tests have still to be fixed

2025-04-02 09:52 UTC, EulalieCoevoet commented
I've removed the test.

2025-04-07 06:01 UTC, fredroy requested changes
It feels wrong that for macOS, user home directory == user local directory 🥸

I made you a PR to fix that @EulalieCoevoet 
so on macOS, screenshots will be in `/Users/<username>/SOFADdata` (i.e `~/SOFAData/screenshots/`) which is consistent with Windows and Linux

https://github.com/EulalieCoevoet/sofa/pull/1

2025-04-07 06:03 UTC, fredroy commented
And I really dont see why, on the CI for linux, it tries to create a `/home/ci` directory, whereas the home directory of the user `ci` has been defined as `/builds` (defined in /etc/passwd) 🤔

2025-04-07 23:31 UTC, fredroy commented
[ci-build][with-all-tests][force-full-build]

2025-04-08 00:22 UTC, fredroy commented
> And I really dont see why, on the CI for linux, it tries to create a `/home/ci` directory, whereas the home directory of the user `ci` has been defined as `/builds` (defined in /etc/passwd) 🤔

```
docker/sofabuilder_ubuntu/Dockerfile:RUN useradd --no-log-init ci --uid 1000 --home /home/ci --create-home --shell /bin/bash
docker/sofabuilder_ubuntu/Dockerfile:ENV HOME="/home/ci"
```
OK everything is inside docker 💡

I detect some docker/container BS because
- main.cpp calls `setDirectoryPath()`. 
`setDirectoryPath()` checks if the folder exists, if it does not, it creates it. 
But in this case, it tries to create (so it is supposed to not exist) but fails because it exists 🥴
- it happens randomly (the list of failing tests is always different) 🫢

2025-04-08 02:03 UTC, fredroy commented
Last commits "fix" the problem by using `std::filesystem` instead of the internal `sofa::helper::system::FileSystem`. 
But effectively the only difference is that create_directories does not throw an error if the directory already exists...

2025-04-10 02:07 UTC, fredroy commented
> Are you both open to merge the PR @EulalieCoevoet @fredroy ?

everything is passing now so... 👍

2025-04-10 02:07 UTC, fredroy approved these changes

2025-04-16 13:26 UTC, fredroy commented
[ci-build][with-all-tests]

2025-04-23 12:12 UTC, fredroy commented
[ci-build]

2025-04-23 12:33 UTC, alxbilger approved these changes

2025-04-23 22:19 UTC, fredroy commented
[ci-build][with-all-tests]

2025-04-24 01:20 UTC, merged