[all] Unifying the way we report file related errors
sofa-framework/sofa pull request #639
Opened 2018-04-17 06:44 UTC by gaurab4163

For consistency purpose, added a helper function to handle the file related errors for loaders and components.

To use it: 
```
 FILE *f = fopen(filename.c_str(), "r");
 msg_error_when(!f)<<sofa::helper::message::UnableToOpenFile(filename.c_str());
```

Modified the usage in only "MeshTrian.cpp". With feedback, if I am in right direction, I will make changes to other loader and component accordingly.Solving issue #197 

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2018-04-17 08:31 UTC, guparan commented
Thanks for your PR @gaurab4163 :+1: 

I'm not sure about the place (file and namespace) this function should be. @damienmarchal you have a clearer vision of logging and messages in SOFA, what do you think?

2018-04-17 08:32 UTC, guparan commented on examples/Components/loader/temp2.scn.view
> +<?xml version="1.0" ?>
This file should not be added.

2018-04-17 08:32 UTC, guparan commented on examples/Demos/caduceus.scn.log
> +
This file should not be added.

2018-04-17 09:13 UTC, damienmarchal commented on SofaKernel/framework/sofa/helper/logging/Messaging.h
> +#define FILEINFO(filename, line) sofa::helper::logging::FileInfo(filename, line)  //rewritten again. delete this?
Probably, 
it is surprising that the compiler does not complains about redefining something.

2018-04-17 09:14 UTC, gaurab4163 commented on examples/Components/loader/temp2.scn.view
> +<?xml version="1.0" ?>
oh yeah. missed it. will remove

2018-04-17 09:22 UTC, damienmarchal commented
Nice, 

I'm happy someone make some proposal on this topic. I think we should factor the common messages, I don't think message.h/cpp is the right place for that. 

I would put that either in separated place like containing only message: 
- SofaCore/MessageLoader.cpp/h
- SofaCore/MessageBaseObject.cpp/h 
Or in the source code in the base class for the loaders.  

Alternative: use a real text-framework that is suppose to externalise all the texts from the source code (to internationalize Sofa...but this wuold be time consuming work)

DM.

2018-04-17 10:10 UTC, gaurab4163 commented
@damienmarchal 
source code of base class for loader sounds right. Working on it :+1: 

btw, i wondered why not use `if` and `cout()` than `msg_error()` and `msg_error_when()`. then came across #190 . It was very impressive. :+1:

2018-04-17 14:52 UTC, gaurab4163 commented
Moved the function to base class for loaders in last commit. Please review.

2018-04-18 13:01 UTC, guparan commented
Why did you revert a commit in https://github.com/sofa-framework/sofa/pull/639/commits/ce882f37c3ade741d8bb47160dc42d0007cfc60f ?

We discussed this PR during our weekly dev meeting. The content is good, the placement is still perfectible. We agreed on creating a new class `FileMessage` in `SofaKernel/framework/sofa/helper/messaging/FileMessage.{h,cpp}` (new files) to contain your static function.

Is that ok for you? Could you implement it?
Thank you for your reactivity :wink:

2018-04-18 15:47 UTC, gaurab4163 commented
Oh... when I made last commit, I meant to revert a37ba08. Had been awake for more than 40 hours(academics, tests, etc.) and evidently, wasn't thinking properly. (Slept like a baby right after last commit. :grin: ) Will adjust this in next commit.

Creating new files sounds right. I have another exam tomorrow. Will do right after it. :+1:

2018-04-25 08:44 UTC, guparan commented
Hey @gaurab4163, do you have some time to continue this work?

2018-04-28 16:24 UTC, gaurab4163 commented
Hey @guparan ,  my final exams started last thursday and will continue until this friday(4th may). Just been crazy busy in last month overall. So, I ll get to it right after it.

2018-05-05 04:51 UTC, gaurab4163 commented
@guparan there is no `messaging` folder. did you mean
`SofaKernel/framework/sofa/helper/logging/FileMessage.{h,cpp}`   instead of
`SofaKernel/framework/sofa/helper/messaging/FileMessage.{h,cpp}`

2018-05-09 08:31 UTC, epernod commented
@gaurab4163 
yes sorry for the missunderstood, the files should be placed in a new folder named:  SofaKernel/framework/sofa/helper/messaging/
not in logging/
Could you change your commit and move the files. Thx.

2018-05-09 09:07 UTC, gaurab4163 commented
@epernod sure. just to make sure, the class will be placed in `sofa::helper::messaging` namespace too, right?

2018-05-09 09:15 UTC, epernod commented
yes

2018-05-10 13:48 UTC, epernod commented
thanks @gaurab4163 for the change. Could you just check the reviews, there is 2 files to remove: a .log and .view
Then it is ok to go I think.

2018-05-15 08:37 UTC, damienmarchal commented
[ci-build][with-scene-tests]

2018-05-15 08:39 UTC, epernod commented
"37 seconds" faster than me ;)

2018-05-16 08:34 UTC, epernod approved these changes

2018-05-16 08:46 UTC, epernod requested changes

2018-05-16 08:46 UTC, epernod commented on SofaKernel/modules/SofaBaseCollision/DiscreteIntersection.cpp
> +
I think you had a bad merge here. Could you double check with the current master branch but I think this is reverting a fix.

2018-05-16 08:46 UTC, epernod commented on SofaKernel/modules/SofaBaseCollision/MinProximityIntersection.cpp
> +template class SOFA_BASE_COLLISION_API IntersectorFactory<component::collision::MinProximityIntersection>;
same here. thanks.

2018-05-31 07:35 UTC, damienmarchal commented
This PR has been re-open in #669,
So i  close it, thank all for the work.

2018-05-31 07:35 UTC, closed without merging