[SofaConstraint]: add a force data field in SlidingConstraint
sofa-framework/sofa pull request #780
Opened 2018-09-21 11:58 UTC by TMorzadec

This data holds the force applied to satisfy the SlidingConstraint

Rename some data with more explicit names following Sofa conventions

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2018-09-21 12:46 UTC, TMorzadec commented
You are welcome! 

Are you interested in SOFA? 

> De: "nikohansen" <notifications@github.com>
> À: "sofa-framework/sofa" <sofa@noreply.github.com>
> Cc: "Thomas Morzadec" <thomas.morzadec@inria.fr>, "Author"
> <author@noreply.github.com>
> Envoyé: Vendredi 21 Septembre 2018 14:40:07
> Objet: Re: [sofa-framework/sofa] [SofaConstraint]: add a force data field in
> SlidingConstraint (#780)

> Thank you Thomas for this nice PR!

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, [
> https://github.com/sofa-framework/sofa/pull/780#issuecomment-423517271 | view
> it on GitHub ] , or [
> https://github.com/notifications/unsubscribe-auth/AeS7MGhDN5T4wjREVewFtjcbualUT15Pks5udN4ngaJpZM4W0Aq0
> | mute the thread ] .

2018-10-10 09:08 UTC, guparan requested changes

2018-10-10 09:08 UTC, guparan commented on modules/SofaConstraint/SlidingConstraint.h
> +    Data<Deriv> mforce; ///< interaction force
Please use `d_` prefix for Data members even if it's not (yet) consistent with existing Data members.
See https://github.com/sofa-framework/sofa/blob/master/GUIDELINES.md#naming

2018-10-10 09:08 UTC, guparan commented on modules/SofaConstraint/SlidingConstraint.h
> +    //typedef typename DataTypes::MultiVecDerivId MultiVecDerivId;
To be removed if not needed.

2018-10-10 09:19 UTC, damienmarchal commented on modules/SofaConstraint/SlidingConstraint.inl
> +    Deriv m_dirAxe = B - A;
This line redefine m_dirAxe which is already defined as a class member.
So the change on this function on m_dirAxe are not stored into the class member but only on this local variable. 

The consequence is that in the line in the store lambda function:
```cpp
 mforce.setValue( m_dirProj* lamb1 + m_dirOrtho * lamb2 + m_dirAxe * lamb3);
```
is not working as expected as the m_dirAxe never change.

2018-10-10 18:42 UTC, damienmarchal commented
@guparan, @hugtalbot  the bug was fixed. Do we set it to ready without waiting next week ?

2018-10-11 09:36 UTC, guparan commented
Sure, feel free to do it if you reviewed the latest changes.
Let's not forget the [ci-build][with-scene-tests] though :wink:

2018-10-25 14:18 UTC, damienmarchal commented
Hey...this PR has not been reviewed since the last request for change. Anyone can do that.

2018-11-14 09:12 UTC, guparan commented
[ci-build][with-scene-tests]

2018-11-16 14:34 UTC, merged