[Multithreading] Move TaskScheduler files from MultiThreading plugin to SofaKernel. TaskScheduler Tests included
sofa-framework/sofa pull request #805
Opened 2018-10-29 16:34 UTC by fspadoni

Move TaskScheduler files from Multithreading plugin to Sofa Kernel.

This change allow any plugins to use the TaskScheduler without adding the dependency on the MultiThreading plugin.

The MultiThreading plugin will be a collection of components using the TaskScheduler to parallelize some computation. 

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2018-10-30 19:31 UTC, fspadoni commented
[ci-build][with-scene-tests]

2018-11-14 09:29 UTC, guparan requested changes

2018-11-14 09:29 UTC, guparan commented on applications/plugins/MultiThreading/CMakeLists.txt
> -        add_subdirectory(test)
The entire block can be removed.

2018-11-14 09:30 UTC, guparan requested changes

2018-11-14 09:30 UTC, guparan commented on applications/plugins/MultiThreading/test/CMakeLists.txt
> +#target_include_directories(${PROJECT_NAME} PRIVATE ${SofaSimulationCore_INCLUDE_DIRS})
To be removed if not necessary

2018-11-21 14:05 UTC, guparan approved these changes

2018-11-21 18:22 UTC, merged