Sofa add data to show constranit forces
sofa-framework/sofa pull request #840
Opened 2018-11-23 16:09 UTC by zhongkaidefrost

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2018-11-23 17:00 UTC, guparan requested changes

2018-11-23 17:00 UTC, guparan commented on modules/SofaConstraint/GenericConstraintSolver.h
> +    Data<helper::vector< double >> constraintForces;
Please use `d_` convention when defining new Data.
See [N5] in https://github.com/sofa-framework/sofa/blob/master/GUIDELINES.md#naming

2018-11-23 17:02 UTC, guparan commented
Congrats for your first PR @zhongkaidefrost ! :clap: 
I just suggested a change, please check it when you have a few minutes :-)

2018-11-27 15:34 UTC, guparan approved these changes

2018-11-28 10:10 UTC, epernod commented
@zhongkaidefrost thanks for your PR.
I'm not sure to understand what the Data constraintForces is used for as it is filled but never used. 
Could you explain in the description of your PR why you introduced this new Data.

In the same idea, it would be nice if you could add an inline doxygen comment to your Data.

2018-11-30 13:32 UTC, zhongkaidefrost commented
The Data constraintForces is used to provide the intensities of contact forces in the simulation.

2018-12-04 10:04 UTC, epernod approved these changes

2018-12-05 09:39 UTC, epernod approved these changes

2018-12-11 10:10 UTC, damienmarchal commented
[ci-build] (because of weird CI-failure)

2018-12-11 23:09 UTC, epernod commented
[ci-build][with-all-tests]

2018-12-12 16:16 UTC, guparan commented
@damienmarchal Do you still plan to change the variable name?

2018-12-12 19:41 UTC, damienmarchal commented
I forgot :)

2018-12-13 09:22 UTC, damienmarchal commented
@guparan ready/merge ?

2018-12-13 15:39 UTC, merged