Add new input datafields to SparseLDLSolver
sofa-framework/sofa pull request #845
Opened 2018-11-30 16:04 UTC by mthieffry

If savingMatrixToFile is set to true, the system matrix is saved during each time step with the name "MatrixInLDL_%04d", where %d is the value of the time.
I added two new input data:

- savingFilename
	The filename where the matrix is stored can be changed using the input data d_filename. 
	If it contains "%d", it will keep the previously described behavior, else it will always save in the same file overwriting it.

- savingPrecision
	The second new input is d_precision. It is the precision with which the matrix will be stored.

These options are useful to save the system matrix from SOFA and read it from another software.                                      

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2018-12-05 10:00 UTC, guparan requested changes

2018-12-05 10:00 UTC, guparan commented on modules/SofaSparseSolver/src/SofaSparseSolver/SparseLDLSolver.inl
> +using namespace std;
Please remove this :-)

2018-12-05 10:05 UTC, guparan commented on modules/SofaSparseSolver/src/SofaSparseSolver/SparseLDLSolver.h
> +    Data<bool> f_saveMatrixToFile;      ///< save matrix to a text file (can be very slow, as full matrix is stored)
Please use `d_` prefix for Datas

2018-12-05 10:07 UTC, guparan commented
[ci-build][with-scene-tests]

2018-12-05 10:20 UTC, jnbrunet commented on modules/SofaSparseSolver/src/SofaSparseSolver/SparseLDLSolver.h
> +    virtual void solve (Matrix& M, Vector& x, Vector& b) override ;
No need for the virtual specifier when override is used.

2018-12-10 15:52 UTC, mthieffry commented
@guparan I made the changes. can you switch the pull request to "to review" ?

2018-12-12 12:28 UTC, damienmarchal commented on modules/SofaSparseSolver/src/SofaSparseSolver/SparseLDLSolver.h
> +    virtual void solve (Matrix& M, Vector& x, Vector& b) override ;
We discuss about that at Defrost and we agree with dropping the virtual specifier when override is there, because it is simply less typing.

2018-12-12 12:29 UTC, merged