minor cleaning of warnings and bugfix
sofa-framework/sofa pull request #886
Opened 2019-01-13 21:16 UTC by hugtalbot

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2019-01-16 10:18 UTC, damienmarchal commented on SofaKernel/framework/sofa/simulation/DefaultTaskScheduler.h
> +            std::thread* create_and_attach(DefaultTaskScheduler* const& /*taskScheduler*/);
Here I would have let the variables.

2019-01-16 10:18 UTC, damienmarchal commented on SofaKernel/framework/sofa/simulation/TaskScheduler.cpp
> +        bool runThreadSpecificTask(const Task* /*task*/)
use SOFA_UNUSED() instead of commenting the name attribute.

2019-01-16 10:21 UTC, epernod requested changes

2019-01-16 10:21 UTC, epernod commented on modules/SofaMiscForceField/GearSpringForceField.inl
> +            typename DataTypes::CPos v1 = p2[springs[i].m2].getOrientation().rotate(vec) + v0;
why change p2 in p1 ? This will change the use of mstate1 and mstate2

2019-01-16 10:23 UTC, epernod commented on modules/SofaMiscForceField/GearSpringForceField.inl
> +            typename DataTypes::CPos v1 = p2[springs[i].m2].getOrientation().rotate(vec) + v0;
maybe rewrite the whole switch loop to avoid all the cases

2019-01-22 13:54 UTC, epernod commented on modules/SofaMiscForceField/GearSpringForceField.inl
> +            typename DataTypes::CPos v1 = p2[springs[i].m2].getOrientation().rotate(vec) + v0;
@hugtalbot answer? The Sofa users want to know! :+1:

2019-01-23 09:21 UTC, epernod approved these changes

2019-01-24 09:01 UTC, merged