[AttachCOnstraint] Fix while using FreeMotionAnimationLoop
sofa-framework/sofa pull request #949
Opened 2019-02-25 17:50 UTC by tgaugry

- Fix Attachconstraint for use with FreeMotionAnimationLoop - credit to @hugtalbot #940
- refactor of parameters to use `SOFA_UNUSED`
- fix dynamicConstraintFactor

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2019-02-26 10:23 UTC, damienmarchal requested changes

2019-02-26 10:23 UTC, damienmarchal commented on modules/SofaGeneralObjectInteraction/AttachConstraint.h
> +            Deriv corr = (dx2-dx1)*0.5*d_responseFactor.getValue()*getConstraintFactor(index);
Try to keep the data_field out of loops. Here the projectResponse function is called n-time...wile d_responseFactor is "assumed" constant during the time step. So pass the response factor as an argument.

2019-02-26 10:23 UTC, damienmarchal commented on modules/SofaGeneralObjectInteraction/AttachConstraint.inl
> +    m_dynamicConstraintFactor = !d_constraintFactor.isSet();
Shouldn't this thing go in reinit ?

2019-03-06 08:49 UTC, damienmarchal approved these changes

2019-03-13 09:26 UTC, tgaugry commented on modules/SofaGeneralObjectInteraction/AttachConstraint.inl
> +            msg_warning() << "Size of vector constraintFactor, do not fit number of indices attached (" << constraintFactor.size() << " != " << f_indices2.getValue().size() << ").";
Not having an error can lead to crash if the the number of indices isn't the same

2019-03-20 15:45 UTC, merged