[install] FIX Could not install plugin resources
sofa-framework/sofa pull request #959
Opened 2019-03-07 19:07 UTC by vmagno

There was an error in the name of the (origin) directory to install. Not sure about the destination though. This fix has no impact on building Sofa, only on its installation.

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

2019-03-08 10:02 UTC, jnbrunet commented
Haaa now it makes sense! We got this bug yesterday.

Thanks Vincent !

2019-03-08 10:47 UTC, guparan commented
Hi, this is not a bug but a new feature I introduced in https://github.com/sofa-framework/sofa/pull/913 to provide (in build and install dirs) a folder that shall always be scanned by PluginManager when searching for a plugin.

The idea was to get an easy way to add/remove plugin binaries in an installed SOFA **without polluting the bin/ folder** which contains stuff I'm not supposed to touch (or scared to touch).

The typical use case is: 
I have SOFA binaries (downloaded from sofa-framework.org or provided by someone) and I have a plugin binaries. How to run the examples of the plugin in runSofa?

Many ways to do that:
1. launch runSofa, open Plugin Manager, load the plugin, open the scene
2. edit the scene to add `<AddPluginRepository path="/path/to/the/plugin"/>` and `<RequiredPlugin name="the_plugin"/>`, launch the scene in runSofa 
3. copy/paste the plugin (library or complete folder) in the bin/ folder of SOFA, add `<RequiredPlugin name="the_plugin"/>` or add the_plugin in bin/plugin_list.conf.default, launch the scene in runSofa 
4. **[NEW]** copy/paste the plugin (library or complete folder) in the plugins/ folder of SOFA, add `<RequiredPlugin name="the_plugin"/>` or add the_plugin in bin/plugin_list.conf.default, launch the scene in runSofa 

(1) is perfect for a new user but becomes heavy quite soon
(2) is more agile but has limitations for plugins that need to be loaded **before** the scene creation (e.g. for Python env init)
(3) solves the limitation of (2) if we use plugin_list.conf but, as I said, putting stuff in bin/ is scary
(4) is what I proposed to separate "plugins that came with SOFA" from "plugins I add myself"


So now about this PR. What you proposed here is to install ALL the sources of applications/plugins into this new plugins folder. Why? 
@jnbrunet You got a bug yesterday, what was it?

2019-03-08 12:59 UTC, guparan requested changes

2019-03-08 12:59 UTC, guparan commented on CMakeLists.txt
> +install(DIRECTORY applications/plugins/ DESTINATION plugins COMPONENT resources)
Actually the bug is real, as stated by @jnbrunet and @marques-bruno but the fix should be
`install(DIRECTORY ${CMAKE_BINARY_DIR}/plugins/ DESTINATION plugins COMPONENT resources)`

2019-03-13 08:43 UTC, guparan approved these changes

2019-03-14 10:59 UTC, merged