Newtests week49
sofa-framework/sofa pull request #97
Opened 2016-12-09 14:21 UTC by bcarrez

New batch of tests from DEFROST team. This branch only contains new tests, no new feature.

2016-12-12 16:06 UTC, guparan requested changes

2016-12-12 16:06 UTC, guparan commented on SofaKernel/framework/framework_test/CMakeLists.txt
> +    helper/io/ImagePNG_test.cpp
Conflict resolution went wrong here. We should not have ImagePNG_test on line 18.
See 67f714f3

2016-12-13 10:43 UTC, damienmarchal commented on SofaKernel/framework/framework_test/CMakeLists.txt
> +    helper/io/ImagePNG_test.cpp
Thanks for the feedback @guparan  
I will fix that asap.

2016-12-13 11:55 UTC, damienmarchal commented
@guparan Done

2016-12-13 12:25 UTC, matthieu-nesme commented
hooray to the defrost team ;)

2016-12-13 15:49 UTC, guparan approved these changes

2016-12-13 16:01 UTC, guparan commented
Could you please manually rebase your branch to the updated upstream/master? Some changes on master prevent GitHub from auto-rebasing.
```
git checkout newtests_week49
git fetch upstream/master
git rebase upstream/master
```

2016-12-14 08:37 UTC, merged